/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as types from "../../types/primitives.js";
import * as models from "../index.js";
import { BotShieldError } from "./bot-shield-error.js";

/**
 * Invalid input
 */
export type InvalidInputErrorData = {
  message: string;
  input: { [k: string]: any };
  errors: Array<models.InvalidInputErrorError>;
};

/**
 * Invalid input
 */
export class InvalidInputError extends BotShieldError {
  input: { [k: string]: any };
  errors: Array<models.InvalidInputErrorError>;

  /** The original data that was passed to this error instance. */
  data$: InvalidInputErrorData;

  constructor(
    err: InvalidInputErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.input = err.input;
    this.errors = err.errors;

    this.name = "InvalidInputError";
  }
}

/** @internal */
export const InvalidInputError$inboundSchema: z.ZodType<
  InvalidInputError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: types.string(),
  input: z.record(z.any()),
  errors: z.array(z.lazy(() => models.InvalidInputErrorError$inboundSchema)),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InvalidInputError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InvalidInputError$Outbound = {
  message: string;
  input: { [k: string]: any };
  errors: Array<models.InvalidInputErrorError$Outbound>;
};

/** @internal */
export const InvalidInputError$outboundSchema: z.ZodType<
  InvalidInputError$Outbound,
  z.ZodTypeDef,
  InvalidInputError
> = z.instanceof(InvalidInputError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    input: z.record(z.any()),
    errors: z.array(z.lazy(() => models.InvalidInputErrorError$outboundSchema)),
  }));
