/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsCancelAction } from "../../funcs/actions-cancel-action.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ActionsCancelRequest$inboundSchema,
};

export const tool$actionsCancelAction: ToolDefinition<typeof args> = {
  name: "cancel_resolution",
  description:
    `Stand down a queued resolution before the user responds. No-op once terminal; TTL expiry produces no Resolution.`,
  scopes: [
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
  ],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await actionsCancelAction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
