/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsCheckActionStatus } from "../../funcs/actions-check-action-status.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ActionsCheckStatusRequest$inboundSchema,
};

export const tool$actionsCheckActionStatus: ToolDefinition<typeof args> = {
  name: "check_resolution_status",
  description:
    `Poll a proposed resolution (pass wait_seconds up to 25 to long-poll). Terminal states (approved/denied) carry the signed Proof of Resolution JWT — verify against BotShield's JWKS; the request_id is the JWT jti.`,
  scopes: [
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
    "queue",
  ],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await actionsCheckActionStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
