/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsProposeAction } from "../../funcs/actions-propose-action.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ActionsProposeRequest$inboundSchema,
};

export const tool$actionsProposeAction: ToolDefinition<typeof args> = {
  name: "propose_action",
  description:
    `Queue a human-presence-gated action for a BotShield user. Returns a card_id immediately; the signed Proof of Resolution arrives async via the agent's registered callback.`,
  scopes: ["queue", "queue"],
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await actionsProposeAction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
