/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { BotShieldCore } from "../core.js";
import { encodeFormQuery } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { resolveSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { BotShieldError } from "../models/errors/bot-shield-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import { ResponseValidationError } from "../models/errors/response-validation-error.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Get partner configuration
 *
 * @remarks
 * Returns enabled integrations (Turnstile, etc.) for a site key. Public config only — secret keys never exposed.
 */
export function sdkGetPartnerConfig(
  client: BotShieldCore,
  security: operations.SDKGetPartnerConfigSecurity,
  request: operations.SDKGetPartnerConfigRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    operations.SDKGetPartnerConfigResponse,
    | BotShieldError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    security,
    request,
    options,
  ));
}

async function $do(
  client: BotShieldCore,
  security: operations.SDKGetPartnerConfigSecurity,
  request: operations.SDKGetPartnerConfigRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      operations.SDKGetPartnerConfigResponse,
      | BotShieldError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      operations.SDKGetPartnerConfigRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = null;

  const path = pathToFunc("/sdk/partner-config")();

  const query = encodeFormQuery({
    "site_key": payload.site_key,
  });

  const headers = new Headers(compactMap({
    Accept: "application/json",
  }));

  const requestSecurity = resolveSecurity(
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth1,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth2,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth3,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth4,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth5,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth6,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth7,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth8,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth9,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth10,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth11,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth12,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth13,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth14,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth15,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth16,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth17,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth18,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth19,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth20,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth21,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth22,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth23,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth24,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth25,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth26,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth27,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth28,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth29,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth30,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth31,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth32,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth33,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth34,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth35,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth36,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth37,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth38,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth39,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth40,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth41,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth42,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth43,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth44,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth45,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth46,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth47,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth48,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth49,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth50,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth51,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth52,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth53,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth54,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth55,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth56,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth57,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth58,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth59,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth60,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth61,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth62,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth63,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth64,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth65,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth66,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth67,
      },
    ],
    [
      {
        fieldName: "Authorization",
        type: "apiKey:header",
        value: security?.apiKeyAuth68,
      },
    ],
  );

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "SdkGetPartnerConfig",
    oAuth2Scopes: null,

    resolvedSecurity: requestSecurity,

    securitySource: security,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "GET",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const [result] = await M.match<
    operations.SDKGetPartnerConfigResponse,
    | BotShieldError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, operations.SDKGetPartnerConfigResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req);
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
