/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsCancelAction } from "../funcs/actions-cancel-action.js";
import { actionsCheckActionStatus } from "../funcs/actions-check-action-status.js";
import { actionsProposeAction } from "../funcs/actions-propose-action.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Actions extends ClientSDK {
  /**
   * Propose an action for human confirmation
   *
   * @remarks
   * Queue a human-presence-gated action for a BotShield user. The user receives the card in the BotShield app (Agents Ask), confirms or denies with a biometric ceremony, and BotShield delivers a signed Proof of Resolution JWT to your registered callback URL (or poll check-status). Identify the user by opaque_id — the pairwise id from the bind ceremony. Authentication: agent key (bs_agent_<name>__<secret>) in the Authorization header.
   */
  async proposeAction(
    request: operations.ActionsProposeRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsProposeResponse> {
    return unwrapAsync(actionsProposeAction(
      this,
      request,
      options,
    ));
  }

  /**
   * Check action proposal status
   *
   * @remarks
   * Poll the state of a proposed action. Terminal states (approved/denied) carry the signed Proof of Resolution JWT (ES256; verify against /.well-known/jwks.json — the request_id is the JWT jti). Pass wait_seconds to long-poll: the call holds up to 25s and returns as soon as the card leaves queued.
   */
  async checkActionStatus(
    request: operations.ActionsCheckStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsCheckStatusResponse> {
    return unwrapAsync(actionsCheckActionStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a queued action proposal
   *
   * @remarks
   * Stand down a queued action before the user responds. Idempotent: if the card is already terminal, returns its current status with already_resolved=true (TTL expiry produces no Resolution).
   */
  async cancelAction(
    request: operations.ActionsCancelRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsCancelResponse> {
    return unwrapAsync(actionsCancelAction(
      this,
      request,
      options,
    ));
  }
}
