/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { actionsCancelAction } from "../funcs/actions-cancel-action.js";
import { actionsCheckActionStatus } from "../funcs/actions-check-action-status.js";
import { actionsProposeAction } from "../funcs/actions-propose-action.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Actions extends ClientSDK {
  /**
   * Propose a BotShield Action
   *
   * @remarks
   * Queue a human-presence-gated action for a BotShield user. The user receives a card on their iOS app, attests via biometric ceremony, and BotShield delivers a signed Resolution JWT to your registered callback URL. Authentication: agent key (bs_agent_<name>__<secret>) in Authorization header.
   */
  async proposeAction(
    request: operations.ActionsProposeRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsProposeResponse> {
    return unwrapAsync(actionsProposeAction(
      this,
      request,
      options,
    ));
  }

  /**
   * Check action proposal status
   *
   * @remarks
   * Poll the current state of a previously-proposed action. For terminal states (approved/denied), the response carries the signed Resolution JWT.
   */
  async checkActionStatus(
    request: operations.ActionsCheckStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsCheckStatusResponse> {
    return unwrapAsync(actionsCheckActionStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Cancel a queued action proposal
   *
   * @remarks
   * Stand down a queued action before the user responds. No-op if the proposal is already in a terminal state (TTL is cancel — silent expiry produces no Resolution).
   */
  async cancelAction(
    request: operations.ActionsCancelRequest,
    options?: RequestOptions,
  ): Promise<operations.ActionsCancelResponse> {
    return unwrapAsync(actionsCancelAction(
      this,
      request,
      options,
    ));
  }
}
