/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { censusCreateSession } from "../funcs/census-create-session.js";
import { censusCreateVerificationLink } from "../funcs/census-create-verification-link.js";
import { censusGetPartnerConfig } from "../funcs/census-get-partner-config.js";
import { censusLogout } from "../funcs/census-logout.js";
import { censusRevokeVerification } from "../funcs/census-revoke-verification.js";
import { censusStoreSignal } from "../funcs/census-store-signal.js";
import { censusValidateSignal } from "../funcs/census-validate-signal.js";
import { censusVerifyToken } from "../funcs/census-verify-token.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Census extends ClientSDK {
  /**
   * Create an Anchor Grant Window
   *
   * @remarks
   * Creates a short-lived anchor grant token (5 minutes) from an API token or site key. Use this to get a token before creating verification links.
   */
  async createSession(
    security: operations.SDKCreateSessionSecurity,
    request: operations.SDKCreateSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKCreateSessionResponse> {
    return unwrapAsync(censusCreateSession(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a verification request
   *
   * @remarks
   * Creates a verification request (deep link, web URL, QR code) for a gate. Requires an anchor grant token from create-session. Returns 409 when a pending request already exists for the same gate and user.
   */
  async createVerificationLink(
    security: operations.SDKCreateVerificationLinkSecurity,
    request: operations.SDKCreateVerificationLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKCreateVerificationLinkResponse> {
    return unwrapAsync(censusCreateVerificationLink(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Validate a verification token
   *
   * @remarks
   * Validates a BotShield attestation JWT — the primary server-side check. Attestations are ES256-signed; the public key is published at /.well-known/jwks.json (kid in the header), so you may also verify locally with any JWT library. Claims are anonymous by construction: the token attests the event, never the person.
   */
  async verifyToken(
    security: operations.SDKVerifyTokenSecurity,
    request: operations.SDKVerifyTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKVerifyTokenResponse> {
    return unwrapAsync(censusVerifyToken(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Store a Signal Pixel bot score
   *
   * @remarks
   * Stores a behavioral fingerprint score server-side and returns an opaque signal_token (bs_sig_...). The client-side score can be spoofed — the signal_token maps to the real score in BotShield's database. Called by the CDN worker; no partner credential is required.
   */
  async storeSignal(
    request: operations.SDKStoreSignalRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKStoreSignalResponse> {
    return unwrapAsync(censusStoreSignal(
      this,
      request,
      options,
    ));
  }

  /**
   * Validate a signal token
   *
   * @remarks
   * Validates a signal_token and returns the real server-side bot score. One-time use, 10-minute expiry. This is the tamper-proof check.
   */
  async validateSignal(
    request: operations.SDKValidateSignalRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKValidateSignalResponse> {
    return unwrapAsync(censusValidateSignal(
      this,
      request,
      options,
    ));
  }

  /**
   * Get partner configuration
   *
   * @remarks
   * Returns enabled integrations (Turnstile, etc.) for a site key. Public config only — secret keys never exposed.
   */
  async getPartnerConfig(
    security: operations.SDKGetPartnerConfigSecurity,
    request: operations.SDKGetPartnerConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKGetPartnerConfigResponse> {
    return unwrapAsync(censusGetPartnerConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Revoke a pending verification
   *
   * @remarks
   * Soft-expires a pending verification for a gate and user. Use when create-verification-link returns 409.
   */
  async revokeVerification(
    security: operations.SDKRevokeVerificationSecurity,
    request: operations.SDKRevokeVerificationRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKRevokeVerificationResponse> {
    return unwrapAsync(censusRevokeVerification(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Revoke an Anchor Grant Window token
   */
  async logout(
    security: operations.SDKLogoutSecurity,
    request: operations.SDKLogoutRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKLogoutResponse> {
    return unwrapAsync(censusLogout(
      this,
      security,
      request,
      options,
    ));
  }
}
