/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Actions } from "./actions.js";
import { Census } from "./census.js";
import { Verification } from "./verification.js";

export class BotShield extends ClientSDK {
  private _census?: Census;
  get census(): Census {
    return (this._census ??= new Census(this._options));
  }

  private _verification?: Verification;
  get verification(): Verification {
    return (this._verification ??= new Verification(this._options));
  }

  private _actions?: Actions;
  get actions(): Actions {
    return (this._actions ??= new Actions(this._options));
  }
}
