/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sdkCreateSession } from "../funcs/sdk-create-session.js";
import { sdkCreateVerificationLink } from "../funcs/sdk-create-verification-link.js";
import { sdkGetPartnerConfig } from "../funcs/sdk-get-partner-config.js";
import { sdkLogout } from "../funcs/sdk-logout.js";
import { sdkRevokeVerification } from "../funcs/sdk-revoke-verification.js";
import { sdkStoreSignal } from "../funcs/sdk-store-signal.js";
import { sdkValidateSignal } from "../funcs/sdk-validate-signal.js";
import { sdkVerifyToken } from "../funcs/sdk-verify-token.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SDK extends ClientSDK {
  /**
   * Create an Anchor Grant Window
   *
   * @remarks
   * Creates a short-lived anchor grant token (5 minutes) from an API token or site key. Use this to get a token before creating verification links.
   */
  async createSession(
    security: operations.SDKCreateSessionSecurity,
    request: operations.SDKCreateSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKCreateSessionResponse> {
    return unwrapAsync(sdkCreateSession(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a verification request
   *
   * @remarks
   * Creates a verification request with deep link, web URL, and QR code. Requires an anchor grant token from create-session.
   */
  async createVerificationLink(
    security: operations.SDKCreateVerificationLinkSecurity,
    request: operations.SDKCreateVerificationLinkRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKCreateVerificationLinkResponse> {
    return unwrapAsync(sdkCreateVerificationLink(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Validate a verification token
   *
   * @remarks
   * Validates a signed JWT verification receipt. This is the primary server-side check. Optionally include signal_token for combined confidence scoring with Signal Pixel + Turnstile + passkey results.
   */
  async verifyToken(
    security: operations.SDKVerifyTokenSecurity,
    request: operations.SDKVerifyTokenRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKVerifyTokenResponse> {
    return unwrapAsync(sdkVerifyToken(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Store a Signal Pixel bot score
   *
   * @remarks
   * Stores a behavioral fingerprint score server-side and returns an opaque signal_token (bs_sig_...). The client-side score can be spoofed — the signal_token maps to the real score in BotShield's database.
   */
  async storeSignal(
    security: operations.SDKStoreSignalSecurity,
    request: operations.SDKStoreSignalRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKStoreSignalResponse> {
    return unwrapAsync(sdkStoreSignal(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Validate a signal token
   *
   * @remarks
   * Validates a signal_token and returns the real server-side bot score. One-time use, 10-minute expiry. This is the tamper-proof check.
   */
  async validateSignal(
    security: operations.SDKValidateSignalSecurity,
    request: operations.SDKValidateSignalRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKValidateSignalResponse> {
    return unwrapAsync(sdkValidateSignal(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get partner configuration
   *
   * @remarks
   * Returns enabled integrations (Turnstile, etc.) for a site key. Public config only — secret keys never exposed.
   */
  async getPartnerConfig(
    security: operations.SDKGetPartnerConfigSecurity,
    request: operations.SDKGetPartnerConfigRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKGetPartnerConfigResponse> {
    return unwrapAsync(sdkGetPartnerConfig(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Revoke a pending verification
   *
   * @remarks
   * Soft-expires a pending verification for a scope and user. Use when create-verification-link returns 409.
   */
  async revokeVerification(
    security: operations.SDKRevokeVerificationSecurity,
    request: operations.SDKRevokeVerificationRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKRevokeVerificationResponse> {
    return unwrapAsync(sdkRevokeVerification(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Revoke an Anchor Grant Window token
   */
  async logout(
    security: operations.SDKLogoutSecurity,
    request: operations.SDKLogoutRequest,
    options?: RequestOptions,
  ): Promise<operations.SDKLogoutResponse> {
    return unwrapAsync(sdkLogout(
      this,
      security,
      request,
      options,
    ));
  }
}
