/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { verificationGetStatus } from "../funcs/verification-get-status.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Verification extends ClientSDK {
  /**
   * Check verification status
   *
   * @remarks
   * Poll a verification request. Carries the signed attestation on completion and NO identity — no user_email, partner_user_id, auth_mode, or botshield_user_id ever cross this boundary.
   */
  async getStatus(
    security: operations.VerificationGetStatusSecurity,
    request: operations.VerificationGetStatusRequest,
    options?: RequestOptions,
  ): Promise<operations.VerificationGetStatusResponse> {
    return unwrapAsync(verificationGetStatus(
      this,
      security,
      request,
      options,
    ));
  }
}
