/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the botshield-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx sdkCreateSession.example.ts
 */

import { BotShield } from "botshield-sdk";

const botShield = new BotShield();

async function main() {
  const result = await botShield.sdk.createSession({
    apiKeyAuth: "<YOUR_API_KEY_HERE>",
  }, {});

  console.log(result);
}

main().catch(console.error);
