workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    botshield-oas:
        inputs:
            - location: registry.speakeasyapi.dev/botshield/sdk/botshield-oas
        overlays:
            - location: ./.speakeasy/overlays/botshield-surface.yaml
        registry:
            location: registry.speakeasyapi.dev/botshield/sdk/botshield-oas
targets:
    botshield-sdk-ts:
        target: typescript
        source: botshield-oas
        publish:
            npm:
                token: $NPM_TOKEN
