/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { buildCommand, numberParser } from "@stricli/core";
import * as z from "zod/v3";
import { consoleLoggerLevels } from "../../console-logger.js";
import { mcpScopes } from "../../scopes.js";

export const startCommand = buildCommand({
  loader: async () => {
    const { main } = await import("./impl.js");
    return main;
  },
  parameters: {
    flags: {
      transport: {
        kind: "enum",
        brief: "The transport to use for communicating with the server",
        default: "stdio",
        values: ["stdio", "sse"],
      },
      port: {
        kind: "parsed",
        brief: "The port to use when the SSE transport is enabled",
        default: "2718",
        parse: (val: string) =>
          z.coerce.number().int().gte(0).lt(65536).parse(val),
      },
      tool: {
        kind: "parsed",
        brief: "Specify tools to mount on the server",
        optional: true,
        variadic: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      scope: {
        kind: "enum",
        brief: "Mount tools/resources that match given scope (repeatable flag)",
        values: mcpScopes,
        variadic: true,
        optional: true,
      },
      "agent-key-auth": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth1": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth1 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth2": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth2 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth3": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth3 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth4": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth4 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth5": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth5 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth6": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth6 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth7": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth7 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth8": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth8 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth9": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth9 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth10": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth10 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth11": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth11 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth12": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth12 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth13": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth13 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth14": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth14 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth15": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth15 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth16": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth16 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth17": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth17 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth18": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth18 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth19": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth19 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth20": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth20 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth21": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth21 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth22": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth22 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth23": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth23 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth24": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth24 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth25": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth25 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth26": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth26 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth27": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth27 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth28": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth28 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth29": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth29 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth30": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth30 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth31": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth31 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth32": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth32 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth33": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth33 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth34": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth34 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth35": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth35 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth36": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth36 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth37": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth37 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth38": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth38 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth39": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth39 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth40": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth40 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth41": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth41 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth42": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth42 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth43": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth43 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth44": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth44 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth45": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth45 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth46": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth46 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth47": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth47 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth48": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth48 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth49": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth49 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth50": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth50 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth51": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth51 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth52": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth52 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth53": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth53 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth54": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth54 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth55": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth55 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth56": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth56 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth57": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth57 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth58": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth58 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth59": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth59 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth60": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth60 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth61": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth61 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "agent-key-auth62": {
        kind: "parsed",
        brief: "Sets the agentKeyAuth62 auth field for the API",
        optional: true,
        parse: (value) => {
          return z.string().parse(value);
        },
      },
      "server-url": {
        kind: "parsed",
        brief: "Overrides the default server URL used by the SDK",
        optional: true,
        parse: (value) => new URL(value).toString(),
      },
      "server-index": {
        kind: "parsed",
        brief: "Selects a predefined server used by the SDK",
        optional: true,
        parse: numberParser,
      },
      "log-level": {
        kind: "enum",
        brief: "The log level to use for the server",
        default: "info",
        values: consoleLoggerLevels,
      },
      env: {
        kind: "parsed",
        brief: "Environment variables made available to the server",
        optional: true,
        variadic: true,
        parse: (val: string) => {
          const sepIdx = val.indexOf("=");
          if (sepIdx === -1) {
            throw new Error("Invalid environment variable format");
          }

          const key = val.slice(0, sepIdx);
          const value = val.slice(sepIdx + 1);

          return [
            z.string().nonempty({
              message: "Environment variable key must be a non-empty string",
            }).parse(key),
            z.string().nonempty({
              message: "Environment variable value must be a non-empty string",
            }).parse(value),
          ] satisfies [string, string];
        },
      },
    },
  },
  docs: {
    brief: "Run the Model Context Protocol server",
  },
});
