/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SSEServerTransport } from "@modelcontextprotocol/sdk/server/sse.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import express from "express";
import { SDKOptions } from "../../../lib/config.js";
import { LocalContext } from "../../cli.js";
import {
  ConsoleLoggerLevel,
  createConsoleLogger,
} from "../../console-logger.js";
import { MCPScope } from "../../scopes.js";
import { createMCPServer } from "../../server.js";

interface StartCommandFlags {
  readonly transport: "stdio" | "sse";
  readonly port: number;
  readonly tool?: string[];
  readonly scope?: MCPScope[];
  readonly "agent-key-auth"?: string | undefined;
  readonly "agent-key-auth1"?: string | undefined;
  readonly "agent-key-auth2"?: string | undefined;
  readonly "agent-key-auth3"?: string | undefined;
  readonly "agent-key-auth4"?: string | undefined;
  readonly "agent-key-auth5"?: string | undefined;
  readonly "agent-key-auth6"?: string | undefined;
  readonly "agent-key-auth7"?: string | undefined;
  readonly "agent-key-auth8"?: string | undefined;
  readonly "agent-key-auth9"?: string | undefined;
  readonly "agent-key-auth10"?: string | undefined;
  readonly "agent-key-auth11"?: string | undefined;
  readonly "agent-key-auth12"?: string | undefined;
  readonly "agent-key-auth13"?: string | undefined;
  readonly "agent-key-auth14"?: string | undefined;
  readonly "agent-key-auth15"?: string | undefined;
  readonly "agent-key-auth16"?: string | undefined;
  readonly "agent-key-auth17"?: string | undefined;
  readonly "agent-key-auth18"?: string | undefined;
  readonly "agent-key-auth19"?: string | undefined;
  readonly "agent-key-auth20"?: string | undefined;
  readonly "agent-key-auth21"?: string | undefined;
  readonly "agent-key-auth22"?: string | undefined;
  readonly "agent-key-auth23"?: string | undefined;
  readonly "agent-key-auth24"?: string | undefined;
  readonly "agent-key-auth25"?: string | undefined;
  readonly "agent-key-auth26"?: string | undefined;
  readonly "agent-key-auth27"?: string | undefined;
  readonly "agent-key-auth28"?: string | undefined;
  readonly "agent-key-auth29"?: string | undefined;
  readonly "agent-key-auth30"?: string | undefined;
  readonly "agent-key-auth31"?: string | undefined;
  readonly "agent-key-auth32"?: string | undefined;
  readonly "agent-key-auth33"?: string | undefined;
  readonly "agent-key-auth34"?: string | undefined;
  readonly "agent-key-auth35"?: string | undefined;
  readonly "agent-key-auth36"?: string | undefined;
  readonly "agent-key-auth37"?: string | undefined;
  readonly "agent-key-auth38"?: string | undefined;
  readonly "agent-key-auth39"?: string | undefined;
  readonly "agent-key-auth40"?: string | undefined;
  readonly "agent-key-auth41"?: string | undefined;
  readonly "agent-key-auth42"?: string | undefined;
  readonly "agent-key-auth43"?: string | undefined;
  readonly "agent-key-auth44"?: string | undefined;
  readonly "agent-key-auth45"?: string | undefined;
  readonly "agent-key-auth46"?: string | undefined;
  readonly "agent-key-auth47"?: string | undefined;
  readonly "agent-key-auth48"?: string | undefined;
  readonly "agent-key-auth49"?: string | undefined;
  readonly "agent-key-auth50"?: string | undefined;
  readonly "agent-key-auth51"?: string | undefined;
  readonly "server-url"?: string;
  readonly "server-index"?: SDKOptions["serverIdx"];
  readonly "log-level": ConsoleLoggerLevel;
  readonly env?: [string, string][];
}

export async function main(this: LocalContext, flags: StartCommandFlags) {
  flags.env?.forEach(([key, value]) => {
    process.env[key] = value;
  });

  switch (flags.transport) {
    case "stdio":
      await startStdio(flags);
      break;
    case "sse":
      await startSSE(flags);
      break;
    default:
      throw new Error(`Invalid transport: ${flags.transport}`);
  }
}

async function startStdio(flags: StartCommandFlags) {
  const logger = createConsoleLogger(flags["log-level"]);
  const transport = new StdioServerTransport();
  const server = createMCPServer({
    logger,
    allowedTools: flags.tool,
    scopes: flags.scope,
    security: {
      agentKeyAuth: flags["agent-key-auth"] ?? "",
      agentKeyAuth1: flags["agent-key-auth1"] ?? "",
      agentKeyAuth2: flags["agent-key-auth2"] ?? "",
      agentKeyAuth3: flags["agent-key-auth3"] ?? "",
      agentKeyAuth4: flags["agent-key-auth4"] ?? "",
      agentKeyAuth5: flags["agent-key-auth5"] ?? "",
      agentKeyAuth6: flags["agent-key-auth6"] ?? "",
      agentKeyAuth7: flags["agent-key-auth7"] ?? "",
      agentKeyAuth8: flags["agent-key-auth8"] ?? "",
      agentKeyAuth9: flags["agent-key-auth9"] ?? "",
      agentKeyAuth10: flags["agent-key-auth10"] ?? "",
      agentKeyAuth11: flags["agent-key-auth11"] ?? "",
      agentKeyAuth12: flags["agent-key-auth12"] ?? "",
      agentKeyAuth13: flags["agent-key-auth13"] ?? "",
      agentKeyAuth14: flags["agent-key-auth14"] ?? "",
      agentKeyAuth15: flags["agent-key-auth15"] ?? "",
      agentKeyAuth16: flags["agent-key-auth16"] ?? "",
      agentKeyAuth17: flags["agent-key-auth17"] ?? "",
      agentKeyAuth18: flags["agent-key-auth18"] ?? "",
      agentKeyAuth19: flags["agent-key-auth19"] ?? "",
      agentKeyAuth20: flags["agent-key-auth20"] ?? "",
      agentKeyAuth21: flags["agent-key-auth21"] ?? "",
      agentKeyAuth22: flags["agent-key-auth22"] ?? "",
      agentKeyAuth23: flags["agent-key-auth23"] ?? "",
      agentKeyAuth24: flags["agent-key-auth24"] ?? "",
      agentKeyAuth25: flags["agent-key-auth25"] ?? "",
      agentKeyAuth26: flags["agent-key-auth26"] ?? "",
      agentKeyAuth27: flags["agent-key-auth27"] ?? "",
      agentKeyAuth28: flags["agent-key-auth28"] ?? "",
      agentKeyAuth29: flags["agent-key-auth29"] ?? "",
      agentKeyAuth30: flags["agent-key-auth30"] ?? "",
      agentKeyAuth31: flags["agent-key-auth31"] ?? "",
      agentKeyAuth32: flags["agent-key-auth32"] ?? "",
      agentKeyAuth33: flags["agent-key-auth33"] ?? "",
      agentKeyAuth34: flags["agent-key-auth34"] ?? "",
      agentKeyAuth35: flags["agent-key-auth35"] ?? "",
      agentKeyAuth36: flags["agent-key-auth36"] ?? "",
      agentKeyAuth37: flags["agent-key-auth37"] ?? "",
      agentKeyAuth38: flags["agent-key-auth38"] ?? "",
      agentKeyAuth39: flags["agent-key-auth39"] ?? "",
      agentKeyAuth40: flags["agent-key-auth40"] ?? "",
      agentKeyAuth41: flags["agent-key-auth41"] ?? "",
      agentKeyAuth42: flags["agent-key-auth42"] ?? "",
      agentKeyAuth43: flags["agent-key-auth43"] ?? "",
      agentKeyAuth44: flags["agent-key-auth44"] ?? "",
      agentKeyAuth45: flags["agent-key-auth45"] ?? "",
      agentKeyAuth46: flags["agent-key-auth46"] ?? "",
      agentKeyAuth47: flags["agent-key-auth47"] ?? "",
      agentKeyAuth48: flags["agent-key-auth48"] ?? "",
      agentKeyAuth49: flags["agent-key-auth49"] ?? "",
      agentKeyAuth50: flags["agent-key-auth50"] ?? "",
      agentKeyAuth51: flags["agent-key-auth51"] ?? "",
    },
    serverURL: flags["server-url"],
    serverIdx: flags["server-index"],
  });
  await server.connect(transport);

  const abort = async () => {
    await server.close();
    process.exit(0);
  };
  process.on("SIGTERM", abort);
  process.on("SIGINT", abort);
}

async function startSSE(flags: StartCommandFlags) {
  const logger = createConsoleLogger(flags["log-level"]);
  const app = express();
  const mcpServer = createMCPServer({
    logger,
    allowedTools: flags.tool,
    scopes: flags.scope,
    security: {
      agentKeyAuth: flags["agent-key-auth"] ?? "",
      agentKeyAuth1: flags["agent-key-auth1"] ?? "",
      agentKeyAuth2: flags["agent-key-auth2"] ?? "",
      agentKeyAuth3: flags["agent-key-auth3"] ?? "",
      agentKeyAuth4: flags["agent-key-auth4"] ?? "",
      agentKeyAuth5: flags["agent-key-auth5"] ?? "",
      agentKeyAuth6: flags["agent-key-auth6"] ?? "",
      agentKeyAuth7: flags["agent-key-auth7"] ?? "",
      agentKeyAuth8: flags["agent-key-auth8"] ?? "",
      agentKeyAuth9: flags["agent-key-auth9"] ?? "",
      agentKeyAuth10: flags["agent-key-auth10"] ?? "",
      agentKeyAuth11: flags["agent-key-auth11"] ?? "",
      agentKeyAuth12: flags["agent-key-auth12"] ?? "",
      agentKeyAuth13: flags["agent-key-auth13"] ?? "",
      agentKeyAuth14: flags["agent-key-auth14"] ?? "",
      agentKeyAuth15: flags["agent-key-auth15"] ?? "",
      agentKeyAuth16: flags["agent-key-auth16"] ?? "",
      agentKeyAuth17: flags["agent-key-auth17"] ?? "",
      agentKeyAuth18: flags["agent-key-auth18"] ?? "",
      agentKeyAuth19: flags["agent-key-auth19"] ?? "",
      agentKeyAuth20: flags["agent-key-auth20"] ?? "",
      agentKeyAuth21: flags["agent-key-auth21"] ?? "",
      agentKeyAuth22: flags["agent-key-auth22"] ?? "",
      agentKeyAuth23: flags["agent-key-auth23"] ?? "",
      agentKeyAuth24: flags["agent-key-auth24"] ?? "",
      agentKeyAuth25: flags["agent-key-auth25"] ?? "",
      agentKeyAuth26: flags["agent-key-auth26"] ?? "",
      agentKeyAuth27: flags["agent-key-auth27"] ?? "",
      agentKeyAuth28: flags["agent-key-auth28"] ?? "",
      agentKeyAuth29: flags["agent-key-auth29"] ?? "",
      agentKeyAuth30: flags["agent-key-auth30"] ?? "",
      agentKeyAuth31: flags["agent-key-auth31"] ?? "",
      agentKeyAuth32: flags["agent-key-auth32"] ?? "",
      agentKeyAuth33: flags["agent-key-auth33"] ?? "",
      agentKeyAuth34: flags["agent-key-auth34"] ?? "",
      agentKeyAuth35: flags["agent-key-auth35"] ?? "",
      agentKeyAuth36: flags["agent-key-auth36"] ?? "",
      agentKeyAuth37: flags["agent-key-auth37"] ?? "",
      agentKeyAuth38: flags["agent-key-auth38"] ?? "",
      agentKeyAuth39: flags["agent-key-auth39"] ?? "",
      agentKeyAuth40: flags["agent-key-auth40"] ?? "",
      agentKeyAuth41: flags["agent-key-auth41"] ?? "",
      agentKeyAuth42: flags["agent-key-auth42"] ?? "",
      agentKeyAuth43: flags["agent-key-auth43"] ?? "",
      agentKeyAuth44: flags["agent-key-auth44"] ?? "",
      agentKeyAuth45: flags["agent-key-auth45"] ?? "",
      agentKeyAuth46: flags["agent-key-auth46"] ?? "",
      agentKeyAuth47: flags["agent-key-auth47"] ?? "",
      agentKeyAuth48: flags["agent-key-auth48"] ?? "",
      agentKeyAuth49: flags["agent-key-auth49"] ?? "",
      agentKeyAuth50: flags["agent-key-auth50"] ?? "",
      agentKeyAuth51: flags["agent-key-auth51"] ?? "",
    },
    serverURL: flags["server-url"],
    serverIdx: flags["server-index"],
  });
  let transport: SSEServerTransport | undefined;
  const controller = new AbortController();

  app.get("/sse", async (_req, res) => {
    transport = new SSEServerTransport("/message", res);

    await mcpServer.connect(transport);

    mcpServer.server.onclose = async () => {
      res.end();
    };
  });

  app.post("/message", async (req, res) => {
    if (!transport) {
      throw new Error("Server transport not initialized");
    }

    await transport.handlePostMessage(req, res);
  });

  const httpServer = app.listen(flags.port, "0.0.0.0", () => {
    const ha = httpServer.address();
    const host = typeof ha === "string" ? ha : `${ha?.address}:${ha?.port}`;
    logger.info("MCP HTTP server started", { host });
  });

  let closing = false;
  controller.signal.addEventListener("abort", async () => {
    if (closing) {
      logger.info("Received second signal. Forcing shutdown.");
      process.exit(1);
    }
    closing = true;

    logger.info("Shutting down MCP server");

    await mcpServer.close();

    logger.info("Shutting down HTTP server");

    const timer = setTimeout(() => {
      logger.info("Forcing shutdown");
      process.exit(1);
    }, 5000);

    httpServer.close(() => {
      clearTimeout(timer);
      logger.info("Graceful shutdown complete");
      process.exit(0);
    });
  });

  const abort = () => controller.abort();
  process.on("SIGTERM", abort);
  process.on("SIGINT", abort);
}
