/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ActionsCheckStatusRequest = {
  requestId: string;
  /**
   * Long-poll hold, in seconds (0–25). Set your HTTP timeout above this.
   */
  waitSeconds?: number | undefined;
};

export const ActionsCheckStatusStatus = {
  Queued: "queued",
  Approved: "approved",
  Denied: "denied",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
export type ActionsCheckStatusStatus = OpenEnum<
  typeof ActionsCheckStatusStatus
>;

/**
 * null until status is approved or denied.
 */
export const Verdict = {
  Approve: "approve",
  Denied: "denied",
} as const;
/**
 * null until status is approved or denied.
 */
export type Verdict = OpenEnum<typeof Verdict>;

export type ActionsCheckStatusDataData = {
  status: ActionsCheckStatusStatus;
  ttlAt?: Date | null | undefined;
  resolvedAt?: Date | null | undefined;
  ceremonyId?: string | null | undefined;
  /**
   * BotShield-signed Proof of Resolution JWT. null until status is approved or denied.
   */
  resolutionJwt?: string | null | undefined;
  /**
   * null until status is approved or denied.
   */
  verdict?: Verdict | null | undefined;
  /**
   * Whether the callback webhook has been confirmed delivered.
   */
  delivered?: boolean | undefined;
  callbackAttempts?: number | undefined;
};

export type ActionsCheckStatusData = {
  data?: ActionsCheckStatusDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Current proposal state. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: 401, 404 (request_id not found), 500.
 */
export type ActionsCheckStatusResponse = {
  data: ActionsCheckStatusData;
};

/** @internal */
export const ActionsCheckStatusRequest$inboundSchema: z.ZodType<
  ActionsCheckStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
  wait_seconds: types.optional(types.number()),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "wait_seconds": "waitSeconds",
  });
});
/** @internal */
export type ActionsCheckStatusRequest$Outbound = {
  request_id: string;
  wait_seconds?: number | undefined;
};

/** @internal */
export const ActionsCheckStatusRequest$outboundSchema: z.ZodType<
  ActionsCheckStatusRequest$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusRequest
> = z.object({
  requestId: z.string(),
  waitSeconds: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    waitSeconds: "wait_seconds",
  });
});

export function actionsCheckStatusRequestToJSON(
  actionsCheckStatusRequest: ActionsCheckStatusRequest,
): string {
  return JSON.stringify(
    ActionsCheckStatusRequest$outboundSchema.parse(actionsCheckStatusRequest),
  );
}
export function actionsCheckStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusRequest' from JSON`,
  );
}

/** @internal */
export const ActionsCheckStatusStatus$inboundSchema: z.ZodType<
  ActionsCheckStatusStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ActionsCheckStatusStatus);
/** @internal */
export const ActionsCheckStatusStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ActionsCheckStatusStatus
> = openEnums.outboundSchema(ActionsCheckStatusStatus);

/** @internal */
export const Verdict$inboundSchema: z.ZodType<Verdict, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Verdict);
/** @internal */
export const Verdict$outboundSchema: z.ZodType<string, z.ZodTypeDef, Verdict> =
  openEnums.outboundSchema(Verdict);

/** @internal */
export const ActionsCheckStatusDataData$inboundSchema: z.ZodType<
  ActionsCheckStatusDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ActionsCheckStatusStatus$inboundSchema,
  ttl_at: z.nullable(types.date()).optional(),
  resolved_at: z.nullable(types.date()).optional(),
  ceremony_id: z.nullable(types.string()).optional(),
  resolution_jwt: z.nullable(types.string()).optional(),
  verdict: z.nullable(Verdict$inboundSchema).optional(),
  delivered: types.optional(types.boolean()),
  callback_attempts: types.optional(types.number()),
}).transform((v) => {
  return remap$(v, {
    "ttl_at": "ttlAt",
    "resolved_at": "resolvedAt",
    "ceremony_id": "ceremonyId",
    "resolution_jwt": "resolutionJwt",
    "callback_attempts": "callbackAttempts",
  });
});
/** @internal */
export type ActionsCheckStatusDataData$Outbound = {
  status: string;
  ttl_at?: string | null | undefined;
  resolved_at?: string | null | undefined;
  ceremony_id?: string | null | undefined;
  resolution_jwt?: string | null | undefined;
  verdict?: string | null | undefined;
  delivered?: boolean | undefined;
  callback_attempts?: number | undefined;
};

/** @internal */
export const ActionsCheckStatusDataData$outboundSchema: z.ZodType<
  ActionsCheckStatusDataData$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusDataData
> = z.object({
  status: ActionsCheckStatusStatus$outboundSchema,
  ttlAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  resolvedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  ceremonyId: z.nullable(z.string()).optional(),
  resolutionJwt: z.nullable(z.string()).optional(),
  verdict: z.nullable(Verdict$outboundSchema).optional(),
  delivered: z.boolean().optional(),
  callbackAttempts: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    ttlAt: "ttl_at",
    resolvedAt: "resolved_at",
    ceremonyId: "ceremony_id",
    resolutionJwt: "resolution_jwt",
    callbackAttempts: "callback_attempts",
  });
});

export function actionsCheckStatusDataDataToJSON(
  actionsCheckStatusDataData: ActionsCheckStatusDataData,
): string {
  return JSON.stringify(
    ActionsCheckStatusDataData$outboundSchema.parse(actionsCheckStatusDataData),
  );
}
export function actionsCheckStatusDataDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusDataData' from JSON`,
  );
}

/** @internal */
export const ActionsCheckStatusData$inboundSchema: z.ZodType<
  ActionsCheckStatusData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => ActionsCheckStatusDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type ActionsCheckStatusData$Outbound = {
  data?: ActionsCheckStatusDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const ActionsCheckStatusData$outboundSchema: z.ZodType<
  ActionsCheckStatusData$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusData
> = z.object({
  data: z.lazy(() => ActionsCheckStatusDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function actionsCheckStatusDataToJSON(
  actionsCheckStatusData: ActionsCheckStatusData,
): string {
  return JSON.stringify(
    ActionsCheckStatusData$outboundSchema.parse(actionsCheckStatusData),
  );
}
export function actionsCheckStatusDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusData' from JSON`,
  );
}

/** @internal */
export const ActionsCheckStatusResponse$inboundSchema: z.ZodType<
  ActionsCheckStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ActionsCheckStatusData$inboundSchema),
});
/** @internal */
export type ActionsCheckStatusResponse$Outbound = {
  data: ActionsCheckStatusData$Outbound;
};

/** @internal */
export const ActionsCheckStatusResponse$outboundSchema: z.ZodType<
  ActionsCheckStatusResponse$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusResponse
> = z.object({
  data: z.lazy(() => ActionsCheckStatusData$outboundSchema),
});

export function actionsCheckStatusResponseToJSON(
  actionsCheckStatusResponse: ActionsCheckStatusResponse,
): string {
  return JSON.stringify(
    ActionsCheckStatusResponse$outboundSchema.parse(actionsCheckStatusResponse),
  );
}
export function actionsCheckStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusResponse' from JSON`,
  );
}
