/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Primary KPI shown on the card chrome.
 */
export type SummaryDetail = {
  label?: string | undefined;
  value?: string | undefined;
};

export type Action = {
  /**
   * Plain-English action description shown on the card (e.g. 'Has an Uber ride ready to book').
   */
  summaryTitle: string;
  /**
   * Primary KPI shown on the card chrome.
   */
  summaryDetail?: SummaryDetail | undefined;
  /**
   * Must be in agent.allowed_action_categories AND in the partner's approved scopes for this environment.
   */
  category: string;
  /**
   * Optional link to the user's trusted account.
   */
  trustedAccountId?: string | undefined;
};

export type ActionsProposeRequest = {
  /**
   * Agent-supplied UUID for idempotency. Re-proposing with the same request_id returns the existing card_id.
   */
  requestId: string;
  /**
   * CANONICAL. The pairwise id this agent holds for the human, obtained once via the bind ceremony (agent/bind-session → claim → check-binding). Meaningless to any other agent. Provide exactly one of opaque_id, botshield_user_id, user_email.
   */
  opaqueId?: string | undefined;
  /**
   * The user's global BotShield id. Prefer opaque_id — this key is identical across agents and can correlate a human between integrations.
   */
  botshieldUserId?: string | undefined;
  /**
   * **Deprecated.** Address the proposal with `opaque_id` (the pairwise id from the bind
   *
   * @remarks
   * ceremony) instead. Will be removed in the next major version.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  userEmail?: string | undefined;
  action: Action;
  /**
   * Optional Adaptive Card v1.5 JSON shown when the user expands the card. Allowlist: TextBlock, FactSet, ColumnSet, Container, Table, Image (bundled-asset only).
   */
  adaptiveCardPayload?: { [k: string]: any } | undefined;
  /**
   * How long the user has to respond before the proposal expires (60–86400; default 600). Out-of-range values are rejected with ttl_below_floor / ttl_above_ceiling.
   */
  ttlSeconds?: number | undefined;
};

/**
 * 'queued' on first proposal. On an idempotent replay (same request_id) the card's CURRENT status.
 */
export const ActionsProposeStatus = {
  Queued: "queued",
  Approved: "approved",
  Denied: "denied",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
/**
 * 'queued' on first proposal. On an idempotent replay (same request_id) the card's CURRENT status.
 */
export type ActionsProposeStatus = OpenEnum<typeof ActionsProposeStatus>;

export type ActionsProposeDataData = {
  /**
   * 'queued' on first proposal. On an idempotent replay (same request_id) the card's CURRENT status.
   */
  status: ActionsProposeStatus;
  cardId: string;
  /**
   * Present on first proposal only.
   */
  ttlAt?: Date | undefined;
  /**
   * true when this request_id was already proposed; no new card was created.
   */
  idempotentReplay?: boolean | undefined;
};

export type ActionsProposeData = {
  data?: ActionsProposeDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Action proposal queued (or replayed). NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: 401, 403 (category_not_allowed), 404 (no binding for opaque_id / user not found), 422 (Adaptive Card rejected, see violations), 400 with code ttl_below_floor | ttl_above_ceiling, 500, 502 (user lookup failed).
 */
export type ActionsProposeResponse = {
  data: ActionsProposeData;
};

/** @internal */
export const SummaryDetail$inboundSchema: z.ZodType<
  SummaryDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: types.optional(types.string()),
  value: types.optional(types.string()),
});
/** @internal */
export type SummaryDetail$Outbound = {
  label?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const SummaryDetail$outboundSchema: z.ZodType<
  SummaryDetail$Outbound,
  z.ZodTypeDef,
  SummaryDetail
> = z.object({
  label: z.string().optional(),
  value: z.string().optional(),
});

export function summaryDetailToJSON(summaryDetail: SummaryDetail): string {
  return JSON.stringify(SummaryDetail$outboundSchema.parse(summaryDetail));
}
export function summaryDetailFromJSON(
  jsonString: string,
): SafeParseResult<SummaryDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SummaryDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SummaryDetail' from JSON`,
  );
}

/** @internal */
export const Action$inboundSchema: z.ZodType<Action, z.ZodTypeDef, unknown> = z
  .object({
    summary_title: types.string(),
    summary_detail: types.optional(z.lazy(() => SummaryDetail$inboundSchema)),
    category: types.string(),
    trusted_account_id: types.optional(types.string()),
  }).transform((v) => {
    return remap$(v, {
      "summary_title": "summaryTitle",
      "summary_detail": "summaryDetail",
      "trusted_account_id": "trustedAccountId",
    });
  });
/** @internal */
export type Action$Outbound = {
  summary_title: string;
  summary_detail?: SummaryDetail$Outbound | undefined;
  category: string;
  trusted_account_id?: string | undefined;
};

/** @internal */
export const Action$outboundSchema: z.ZodType<
  Action$Outbound,
  z.ZodTypeDef,
  Action
> = z.object({
  summaryTitle: z.string(),
  summaryDetail: z.lazy(() => SummaryDetail$outboundSchema).optional(),
  category: z.string(),
  trustedAccountId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    summaryTitle: "summary_title",
    summaryDetail: "summary_detail",
    trustedAccountId: "trusted_account_id",
  });
});

export function actionToJSON(action: Action): string {
  return JSON.stringify(Action$outboundSchema.parse(action));
}
export function actionFromJSON(
  jsonString: string,
): SafeParseResult<Action, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Action$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Action' from JSON`,
  );
}

/** @internal */
export const ActionsProposeRequest$inboundSchema: z.ZodType<
  ActionsProposeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
  opaque_id: types.optional(types.string()),
  botshield_user_id: types.optional(types.string()),
  user_email: types.optional(types.string()),
  action: z.lazy(() => Action$inboundSchema),
  adaptive_card_payload: types.optional(z.record(z.any())),
  ttl_seconds: types.number().default(600),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "opaque_id": "opaqueId",
    "botshield_user_id": "botshieldUserId",
    "user_email": "userEmail",
    "adaptive_card_payload": "adaptiveCardPayload",
    "ttl_seconds": "ttlSeconds",
  });
});
/** @internal */
export type ActionsProposeRequest$Outbound = {
  request_id: string;
  opaque_id?: string | undefined;
  botshield_user_id?: string | undefined;
  user_email?: string | undefined;
  action: Action$Outbound;
  adaptive_card_payload?: { [k: string]: any } | undefined;
  ttl_seconds: number;
};

/** @internal */
export const ActionsProposeRequest$outboundSchema: z.ZodType<
  ActionsProposeRequest$Outbound,
  z.ZodTypeDef,
  ActionsProposeRequest
> = z.object({
  requestId: z.string(),
  opaqueId: z.string().optional(),
  botshieldUserId: z.string().optional(),
  userEmail: z.string().optional(),
  action: z.lazy(() => Action$outboundSchema),
  adaptiveCardPayload: z.record(z.any()).optional(),
  ttlSeconds: z.number().int().default(600),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    opaqueId: "opaque_id",
    botshieldUserId: "botshield_user_id",
    userEmail: "user_email",
    adaptiveCardPayload: "adaptive_card_payload",
    ttlSeconds: "ttl_seconds",
  });
});

export function actionsProposeRequestToJSON(
  actionsProposeRequest: ActionsProposeRequest,
): string {
  return JSON.stringify(
    ActionsProposeRequest$outboundSchema.parse(actionsProposeRequest),
  );
}
export function actionsProposeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeRequest' from JSON`,
  );
}

/** @internal */
export const ActionsProposeStatus$inboundSchema: z.ZodType<
  ActionsProposeStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ActionsProposeStatus);
/** @internal */
export const ActionsProposeStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ActionsProposeStatus
> = openEnums.outboundSchema(ActionsProposeStatus);

/** @internal */
export const ActionsProposeDataData$inboundSchema: z.ZodType<
  ActionsProposeDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ActionsProposeStatus$inboundSchema,
  card_id: types.string(),
  ttl_at: types.optional(types.date()),
  idempotent_replay: types.optional(types.boolean()),
}).transform((v) => {
  return remap$(v, {
    "card_id": "cardId",
    "ttl_at": "ttlAt",
    "idempotent_replay": "idempotentReplay",
  });
});
/** @internal */
export type ActionsProposeDataData$Outbound = {
  status: string;
  card_id: string;
  ttl_at?: string | undefined;
  idempotent_replay?: boolean | undefined;
};

/** @internal */
export const ActionsProposeDataData$outboundSchema: z.ZodType<
  ActionsProposeDataData$Outbound,
  z.ZodTypeDef,
  ActionsProposeDataData
> = z.object({
  status: ActionsProposeStatus$outboundSchema,
  cardId: z.string(),
  ttlAt: z.date().transform(v => v.toISOString()).optional(),
  idempotentReplay: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    cardId: "card_id",
    ttlAt: "ttl_at",
    idempotentReplay: "idempotent_replay",
  });
});

export function actionsProposeDataDataToJSON(
  actionsProposeDataData: ActionsProposeDataData,
): string {
  return JSON.stringify(
    ActionsProposeDataData$outboundSchema.parse(actionsProposeDataData),
  );
}
export function actionsProposeDataDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeDataData' from JSON`,
  );
}

/** @internal */
export const ActionsProposeData$inboundSchema: z.ZodType<
  ActionsProposeData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => ActionsProposeDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type ActionsProposeData$Outbound = {
  data?: ActionsProposeDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const ActionsProposeData$outboundSchema: z.ZodType<
  ActionsProposeData$Outbound,
  z.ZodTypeDef,
  ActionsProposeData
> = z.object({
  data: z.lazy(() => ActionsProposeDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function actionsProposeDataToJSON(
  actionsProposeData: ActionsProposeData,
): string {
  return JSON.stringify(
    ActionsProposeData$outboundSchema.parse(actionsProposeData),
  );
}
export function actionsProposeDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeData' from JSON`,
  );
}

/** @internal */
export const ActionsProposeResponse$inboundSchema: z.ZodType<
  ActionsProposeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ActionsProposeData$inboundSchema),
});
/** @internal */
export type ActionsProposeResponse$Outbound = {
  data: ActionsProposeData$Outbound;
};

/** @internal */
export const ActionsProposeResponse$outboundSchema: z.ZodType<
  ActionsProposeResponse$Outbound,
  z.ZodTypeDef,
  ActionsProposeResponse
> = z.object({
  data: z.lazy(() => ActionsProposeData$outboundSchema),
});

export function actionsProposeResponseToJSON(
  actionsProposeResponse: ActionsProposeResponse,
): string {
  return JSON.stringify(
    ActionsProposeResponse$outboundSchema.parse(actionsProposeResponse),
  );
}
export function actionsProposeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeResponse' from JSON`,
  );
}
