/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ActionsCheckStatusRequest = {
  requestId: string;
};

export const ActionsCheckStatusStatus = {
  Queued: "queued",
  Approved: "approved",
  Denied: "denied",
  Expired: "expired",
  Cancelled: "cancelled",
} as const;
export type ActionsCheckStatusStatus = OpenEnum<
  typeof ActionsCheckStatusStatus
>;

/**
 * Present only when status is approved or denied.
 */
export const Verdict = {
  Approve: "approve",
  Denied: "denied",
} as const;
/**
 * Present only when status is approved or denied.
 */
export type Verdict = OpenEnum<typeof Verdict>;

export type ActionsCheckStatusData = {
  status: ActionsCheckStatusStatus;
  /**
   * Present only when status is approved or denied.
   */
  verdict?: Verdict | undefined;
  /**
   * BotShield-signed Resolution JWT. Present only when status is approved or denied. Verify with BotShield's public key.
   */
  resolutionJwt?: string | undefined;
  ceremonyId?: string | undefined;
  /**
   * Whether the callback webhook has been confirmed delivered.
   */
  delivered?: boolean | undefined;
};

/**
 * Current proposal state
 */
export type ActionsCheckStatusResponse = {
  data: ActionsCheckStatusData;
};

/** @internal */
export const ActionsCheckStatusRequest$inboundSchema: z.ZodType<
  ActionsCheckStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type ActionsCheckStatusRequest$Outbound = {
  request_id: string;
};

/** @internal */
export const ActionsCheckStatusRequest$outboundSchema: z.ZodType<
  ActionsCheckStatusRequest$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusRequest
> = z.object({
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function actionsCheckStatusRequestToJSON(
  actionsCheckStatusRequest: ActionsCheckStatusRequest,
): string {
  return JSON.stringify(
    ActionsCheckStatusRequest$outboundSchema.parse(actionsCheckStatusRequest),
  );
}
export function actionsCheckStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusRequest' from JSON`,
  );
}

/** @internal */
export const ActionsCheckStatusStatus$inboundSchema: z.ZodType<
  ActionsCheckStatusStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ActionsCheckStatusStatus);
/** @internal */
export const ActionsCheckStatusStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ActionsCheckStatusStatus
> = openEnums.outboundSchema(ActionsCheckStatusStatus);

/** @internal */
export const Verdict$inboundSchema: z.ZodType<Verdict, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Verdict);
/** @internal */
export const Verdict$outboundSchema: z.ZodType<string, z.ZodTypeDef, Verdict> =
  openEnums.outboundSchema(Verdict);

/** @internal */
export const ActionsCheckStatusData$inboundSchema: z.ZodType<
  ActionsCheckStatusData,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ActionsCheckStatusStatus$inboundSchema,
  verdict: types.optional(Verdict$inboundSchema),
  resolution_jwt: types.optional(types.string()),
  ceremony_id: types.optional(types.string()),
  delivered: types.optional(types.boolean()),
}).transform((v) => {
  return remap$(v, {
    "resolution_jwt": "resolutionJwt",
    "ceremony_id": "ceremonyId",
  });
});
/** @internal */
export type ActionsCheckStatusData$Outbound = {
  status: string;
  verdict?: string | undefined;
  resolution_jwt?: string | undefined;
  ceremony_id?: string | undefined;
  delivered?: boolean | undefined;
};

/** @internal */
export const ActionsCheckStatusData$outboundSchema: z.ZodType<
  ActionsCheckStatusData$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusData
> = z.object({
  status: ActionsCheckStatusStatus$outboundSchema,
  verdict: Verdict$outboundSchema.optional(),
  resolutionJwt: z.string().optional(),
  ceremonyId: z.string().optional(),
  delivered: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    resolutionJwt: "resolution_jwt",
    ceremonyId: "ceremony_id",
  });
});

export function actionsCheckStatusDataToJSON(
  actionsCheckStatusData: ActionsCheckStatusData,
): string {
  return JSON.stringify(
    ActionsCheckStatusData$outboundSchema.parse(actionsCheckStatusData),
  );
}
export function actionsCheckStatusDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusData' from JSON`,
  );
}

/** @internal */
export const ActionsCheckStatusResponse$inboundSchema: z.ZodType<
  ActionsCheckStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ActionsCheckStatusData$inboundSchema),
});
/** @internal */
export type ActionsCheckStatusResponse$Outbound = {
  data: ActionsCheckStatusData$Outbound;
};

/** @internal */
export const ActionsCheckStatusResponse$outboundSchema: z.ZodType<
  ActionsCheckStatusResponse$Outbound,
  z.ZodTypeDef,
  ActionsCheckStatusResponse
> = z.object({
  data: z.lazy(() => ActionsCheckStatusData$outboundSchema),
});

export function actionsCheckStatusResponseToJSON(
  actionsCheckStatusResponse: ActionsCheckStatusResponse,
): string {
  return JSON.stringify(
    ActionsCheckStatusResponse$outboundSchema.parse(actionsCheckStatusResponse),
  );
}
export function actionsCheckStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCheckStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCheckStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCheckStatusResponse' from JSON`,
  );
}
