/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type ActionsCancelRequest = {
  requestId: string;
};

export type ActionsCancelData = {
  cancelled?: boolean | undefined;
  alreadyTerminal?: boolean | undefined;
};

/**
 * Cancellation result
 */
export type ActionsCancelResponse = {
  data: ActionsCancelData;
};

/** @internal */
export const ActionsCancelRequest$inboundSchema: z.ZodType<
  ActionsCancelRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type ActionsCancelRequest$Outbound = {
  request_id: string;
};

/** @internal */
export const ActionsCancelRequest$outboundSchema: z.ZodType<
  ActionsCancelRequest$Outbound,
  z.ZodTypeDef,
  ActionsCancelRequest
> = z.object({
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function actionsCancelRequestToJSON(
  actionsCancelRequest: ActionsCancelRequest,
): string {
  return JSON.stringify(
    ActionsCancelRequest$outboundSchema.parse(actionsCancelRequest),
  );
}
export function actionsCancelRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCancelRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCancelRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCancelRequest' from JSON`,
  );
}

/** @internal */
export const ActionsCancelData$inboundSchema: z.ZodType<
  ActionsCancelData,
  z.ZodTypeDef,
  unknown
> = z.object({
  cancelled: types.optional(types.boolean()),
  already_terminal: types.optional(types.boolean()),
}).transform((v) => {
  return remap$(v, {
    "already_terminal": "alreadyTerminal",
  });
});
/** @internal */
export type ActionsCancelData$Outbound = {
  cancelled?: boolean | undefined;
  already_terminal?: boolean | undefined;
};

/** @internal */
export const ActionsCancelData$outboundSchema: z.ZodType<
  ActionsCancelData$Outbound,
  z.ZodTypeDef,
  ActionsCancelData
> = z.object({
  cancelled: z.boolean().optional(),
  alreadyTerminal: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    alreadyTerminal: "already_terminal",
  });
});

export function actionsCancelDataToJSON(
  actionsCancelData: ActionsCancelData,
): string {
  return JSON.stringify(
    ActionsCancelData$outboundSchema.parse(actionsCancelData),
  );
}
export function actionsCancelDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCancelData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCancelData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCancelData' from JSON`,
  );
}

/** @internal */
export const ActionsCancelResponse$inboundSchema: z.ZodType<
  ActionsCancelResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ActionsCancelData$inboundSchema),
});
/** @internal */
export type ActionsCancelResponse$Outbound = {
  data: ActionsCancelData$Outbound;
};

/** @internal */
export const ActionsCancelResponse$outboundSchema: z.ZodType<
  ActionsCancelResponse$Outbound,
  z.ZodTypeDef,
  ActionsCancelResponse
> = z.object({
  data: z.lazy(() => ActionsCancelData$outboundSchema),
});

export function actionsCancelResponseToJSON(
  actionsCancelResponse: ActionsCancelResponse,
): string {
  return JSON.stringify(
    ActionsCancelResponse$outboundSchema.parse(actionsCancelResponse),
  );
}
export function actionsCancelResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionsCancelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsCancelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsCancelResponse' from JSON`,
  );
}
