/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Primary KPI shown on the card chrome.
 */
export type SummaryDetail = {
  label?: string | undefined;
  value?: string | undefined;
};

export type Action = {
  /**
   * Plain-English action description shown on the card (e.g. 'Has an Uber ride ready to book').
   */
  summaryTitle: string;
  /**
   * Primary KPI shown on the card chrome.
   */
  summaryDetail?: SummaryDetail | undefined;
  /**
   * Must be in agent.allowed_action_categories AND in the partner's approved scopes for this environment.
   */
  category: string;
  /**
   * Optional link to the user's MultiPass-linked account.
   */
  trustedAccountId?: string | undefined;
};

export type ActionsProposeRequest = {
  /**
   * Agent-supplied UUID for idempotency. Re-proposing with the same request_id returns the existing card_id.
   */
  requestId: string;
  /**
   * Email of the BotShield user to receive this proposal.
   */
  userEmail: string;
  action: Action;
  /**
   * Optional Adaptive Card v1.5 JSON shown when the user expands the card. Allowlist: TextBlock, FactSet, ColumnSet, Container, Table, Image (bundled-asset only).
   */
  adaptiveCardPayload?: { [k: string]: any } | undefined;
  /**
   * How long the user has to respond before the proposal expires. Bounds locked by V3 spec §3.4.
   */
  ttlSeconds?: number | undefined;
};

export const ActionsProposeStatus = {
  Queued: "queued",
} as const;
export type ActionsProposeStatus = ClosedEnum<typeof ActionsProposeStatus>;

export type ActionsProposeData = {
  status: ActionsProposeStatus;
  cardId: string;
  ttlAt: Date;
};

/**
 * Action proposal queued
 */
export type ActionsProposeResponse = {
  data: ActionsProposeData;
};

/** @internal */
export const SummaryDetail$inboundSchema: z.ZodType<
  SummaryDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  label: types.optional(types.string()),
  value: types.optional(types.string()),
});
/** @internal */
export type SummaryDetail$Outbound = {
  label?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const SummaryDetail$outboundSchema: z.ZodType<
  SummaryDetail$Outbound,
  z.ZodTypeDef,
  SummaryDetail
> = z.object({
  label: z.string().optional(),
  value: z.string().optional(),
});

export function summaryDetailToJSON(summaryDetail: SummaryDetail): string {
  return JSON.stringify(SummaryDetail$outboundSchema.parse(summaryDetail));
}
export function summaryDetailFromJSON(
  jsonString: string,
): SafeParseResult<SummaryDetail, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SummaryDetail$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SummaryDetail' from JSON`,
  );
}

/** @internal */
export const Action$inboundSchema: z.ZodType<Action, z.ZodTypeDef, unknown> = z
  .object({
    summary_title: types.string(),
    summary_detail: types.optional(z.lazy(() => SummaryDetail$inboundSchema)),
    category: types.string(),
    trusted_account_id: types.optional(types.string()),
  }).transform((v) => {
    return remap$(v, {
      "summary_title": "summaryTitle",
      "summary_detail": "summaryDetail",
      "trusted_account_id": "trustedAccountId",
    });
  });
/** @internal */
export type Action$Outbound = {
  summary_title: string;
  summary_detail?: SummaryDetail$Outbound | undefined;
  category: string;
  trusted_account_id?: string | undefined;
};

/** @internal */
export const Action$outboundSchema: z.ZodType<
  Action$Outbound,
  z.ZodTypeDef,
  Action
> = z.object({
  summaryTitle: z.string(),
  summaryDetail: z.lazy(() => SummaryDetail$outboundSchema).optional(),
  category: z.string(),
  trustedAccountId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    summaryTitle: "summary_title",
    summaryDetail: "summary_detail",
    trustedAccountId: "trusted_account_id",
  });
});

export function actionToJSON(action: Action): string {
  return JSON.stringify(Action$outboundSchema.parse(action));
}
export function actionFromJSON(
  jsonString: string,
): SafeParseResult<Action, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Action$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Action' from JSON`,
  );
}

/** @internal */
export const ActionsProposeRequest$inboundSchema: z.ZodType<
  ActionsProposeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
  user_email: types.string(),
  action: z.lazy(() => Action$inboundSchema),
  adaptive_card_payload: types.optional(z.record(z.any())),
  ttl_seconds: types.number().default(600),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "user_email": "userEmail",
    "adaptive_card_payload": "adaptiveCardPayload",
    "ttl_seconds": "ttlSeconds",
  });
});
/** @internal */
export type ActionsProposeRequest$Outbound = {
  request_id: string;
  user_email: string;
  action: Action$Outbound;
  adaptive_card_payload?: { [k: string]: any } | undefined;
  ttl_seconds: number;
};

/** @internal */
export const ActionsProposeRequest$outboundSchema: z.ZodType<
  ActionsProposeRequest$Outbound,
  z.ZodTypeDef,
  ActionsProposeRequest
> = z.object({
  requestId: z.string(),
  userEmail: z.string(),
  action: z.lazy(() => Action$outboundSchema),
  adaptiveCardPayload: z.record(z.any()).optional(),
  ttlSeconds: z.number().int().default(600),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    userEmail: "user_email",
    adaptiveCardPayload: "adaptive_card_payload",
    ttlSeconds: "ttl_seconds",
  });
});

export function actionsProposeRequestToJSON(
  actionsProposeRequest: ActionsProposeRequest,
): string {
  return JSON.stringify(
    ActionsProposeRequest$outboundSchema.parse(actionsProposeRequest),
  );
}
export function actionsProposeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeRequest' from JSON`,
  );
}

/** @internal */
export const ActionsProposeStatus$inboundSchema: z.ZodNativeEnum<
  typeof ActionsProposeStatus
> = z.nativeEnum(ActionsProposeStatus);
/** @internal */
export const ActionsProposeStatus$outboundSchema: z.ZodNativeEnum<
  typeof ActionsProposeStatus
> = ActionsProposeStatus$inboundSchema;

/** @internal */
export const ActionsProposeData$inboundSchema: z.ZodType<
  ActionsProposeData,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ActionsProposeStatus$inboundSchema,
  card_id: types.string(),
  ttl_at: types.date(),
}).transform((v) => {
  return remap$(v, {
    "card_id": "cardId",
    "ttl_at": "ttlAt",
  });
});
/** @internal */
export type ActionsProposeData$Outbound = {
  status: string;
  card_id: string;
  ttl_at: string;
};

/** @internal */
export const ActionsProposeData$outboundSchema: z.ZodType<
  ActionsProposeData$Outbound,
  z.ZodTypeDef,
  ActionsProposeData
> = z.object({
  status: ActionsProposeStatus$outboundSchema,
  cardId: z.string(),
  ttlAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    cardId: "card_id",
    ttlAt: "ttl_at",
  });
});

export function actionsProposeDataToJSON(
  actionsProposeData: ActionsProposeData,
): string {
  return JSON.stringify(
    ActionsProposeData$outboundSchema.parse(actionsProposeData),
  );
}
export function actionsProposeDataFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeData' from JSON`,
  );
}

/** @internal */
export const ActionsProposeResponse$inboundSchema: z.ZodType<
  ActionsProposeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => ActionsProposeData$inboundSchema),
});
/** @internal */
export type ActionsProposeResponse$Outbound = {
  data: ActionsProposeData$Outbound;
};

/** @internal */
export const ActionsProposeResponse$outboundSchema: z.ZodType<
  ActionsProposeResponse$Outbound,
  z.ZodTypeDef,
  ActionsProposeResponse
> = z.object({
  data: z.lazy(() => ActionsProposeData$outboundSchema),
});

export function actionsProposeResponseToJSON(
  actionsProposeResponse: ActionsProposeResponse,
): string {
  return JSON.stringify(
    ActionsProposeResponse$outboundSchema.parse(actionsProposeResponse),
  );
}
export function actionsProposeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActionsProposeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActionsProposeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActionsProposeResponse' from JSON`,
  );
}
