/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKGetPartnerConfigSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
  apiKeyAuth32?: string | undefined;
  apiKeyAuth33?: string | undefined;
  apiKeyAuth34?: string | undefined;
  apiKeyAuth35?: string | undefined;
  apiKeyAuth36?: string | undefined;
  apiKeyAuth37?: string | undefined;
  apiKeyAuth38?: string | undefined;
  apiKeyAuth39?: string | undefined;
  apiKeyAuth40?: string | undefined;
  apiKeyAuth41?: string | undefined;
  apiKeyAuth42?: string | undefined;
  apiKeyAuth43?: string | undefined;
  apiKeyAuth44?: string | undefined;
  apiKeyAuth45?: string | undefined;
  apiKeyAuth46?: string | undefined;
  apiKeyAuth47?: string | undefined;
  apiKeyAuth48?: string | undefined;
  apiKeyAuth49?: string | undefined;
  apiKeyAuth50?: string | undefined;
  apiKeyAuth51?: string | undefined;
  apiKeyAuth52?: string | undefined;
  apiKeyAuth53?: string | undefined;
  apiKeyAuth54?: string | undefined;
  apiKeyAuth55?: string | undefined;
  apiKeyAuth56?: string | undefined;
  apiKeyAuth57?: string | undefined;
  apiKeyAuth58?: string | undefined;
  apiKeyAuth59?: string | undefined;
  apiKeyAuth60?: string | undefined;
  apiKeyAuth61?: string | undefined;
  apiKeyAuth62?: string | undefined;
};

export type SDKGetPartnerConfigRequest = {
  siteKey: string;
};

export type Integrations = {
  enabled?: boolean | undefined;
  siteKey?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

export const Environment = {
  Test: "test",
  Live: "live",
} as const;
export type Environment = OpenEnum<typeof Environment>;

/**
 * Partner configuration
 */
export type SDKGetPartnerConfigResponse = {
  integrations?: { [k: string]: Integrations } | undefined;
  environment?: Environment | undefined;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$inboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
  apiKeyAuth3: types.optional(types.string()),
  apiKeyAuth4: types.optional(types.string()),
  apiKeyAuth5: types.optional(types.string()),
  apiKeyAuth6: types.optional(types.string()),
  apiKeyAuth7: types.optional(types.string()),
  apiKeyAuth8: types.optional(types.string()),
  apiKeyAuth9: types.optional(types.string()),
  apiKeyAuth10: types.optional(types.string()),
  apiKeyAuth11: types.optional(types.string()),
  apiKeyAuth12: types.optional(types.string()),
  apiKeyAuth13: types.optional(types.string()),
  apiKeyAuth14: types.optional(types.string()),
  apiKeyAuth15: types.optional(types.string()),
  apiKeyAuth16: types.optional(types.string()),
  apiKeyAuth17: types.optional(types.string()),
  apiKeyAuth18: types.optional(types.string()),
  apiKeyAuth19: types.optional(types.string()),
  apiKeyAuth20: types.optional(types.string()),
  apiKeyAuth21: types.optional(types.string()),
  apiKeyAuth22: types.optional(types.string()),
  apiKeyAuth23: types.optional(types.string()),
  apiKeyAuth24: types.optional(types.string()),
  apiKeyAuth25: types.optional(types.string()),
  apiKeyAuth26: types.optional(types.string()),
  apiKeyAuth27: types.optional(types.string()),
  apiKeyAuth28: types.optional(types.string()),
  apiKeyAuth29: types.optional(types.string()),
  apiKeyAuth30: types.optional(types.string()),
  apiKeyAuth31: types.optional(types.string()),
  apiKeyAuth32: types.optional(types.string()),
  apiKeyAuth33: types.optional(types.string()),
  apiKeyAuth34: types.optional(types.string()),
  apiKeyAuth35: types.optional(types.string()),
  apiKeyAuth36: types.optional(types.string()),
  apiKeyAuth37: types.optional(types.string()),
  apiKeyAuth38: types.optional(types.string()),
  apiKeyAuth39: types.optional(types.string()),
  apiKeyAuth40: types.optional(types.string()),
  apiKeyAuth41: types.optional(types.string()),
  apiKeyAuth42: types.optional(types.string()),
  apiKeyAuth43: types.optional(types.string()),
  apiKeyAuth44: types.optional(types.string()),
  apiKeyAuth45: types.optional(types.string()),
  apiKeyAuth46: types.optional(types.string()),
  apiKeyAuth47: types.optional(types.string()),
  apiKeyAuth48: types.optional(types.string()),
  apiKeyAuth49: types.optional(types.string()),
  apiKeyAuth50: types.optional(types.string()),
  apiKeyAuth51: types.optional(types.string()),
  apiKeyAuth52: types.optional(types.string()),
  apiKeyAuth53: types.optional(types.string()),
  apiKeyAuth54: types.optional(types.string()),
  apiKeyAuth55: types.optional(types.string()),
  apiKeyAuth56: types.optional(types.string()),
  apiKeyAuth57: types.optional(types.string()),
  apiKeyAuth58: types.optional(types.string()),
  apiKeyAuth59: types.optional(types.string()),
  apiKeyAuth60: types.optional(types.string()),
  apiKeyAuth61: types.optional(types.string()),
  apiKeyAuth62: types.optional(types.string()),
});
/** @internal */
export type SDKGetPartnerConfigSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
  apiKeyAuth32?: string | undefined;
  apiKeyAuth33?: string | undefined;
  apiKeyAuth34?: string | undefined;
  apiKeyAuth35?: string | undefined;
  apiKeyAuth36?: string | undefined;
  apiKeyAuth37?: string | undefined;
  apiKeyAuth38?: string | undefined;
  apiKeyAuth39?: string | undefined;
  apiKeyAuth40?: string | undefined;
  apiKeyAuth41?: string | undefined;
  apiKeyAuth42?: string | undefined;
  apiKeyAuth43?: string | undefined;
  apiKeyAuth44?: string | undefined;
  apiKeyAuth45?: string | undefined;
  apiKeyAuth46?: string | undefined;
  apiKeyAuth47?: string | undefined;
  apiKeyAuth48?: string | undefined;
  apiKeyAuth49?: string | undefined;
  apiKeyAuth50?: string | undefined;
  apiKeyAuth51?: string | undefined;
  apiKeyAuth52?: string | undefined;
  apiKeyAuth53?: string | undefined;
  apiKeyAuth54?: string | undefined;
  apiKeyAuth55?: string | undefined;
  apiKeyAuth56?: string | undefined;
  apiKeyAuth57?: string | undefined;
  apiKeyAuth58?: string | undefined;
  apiKeyAuth59?: string | undefined;
  apiKeyAuth60?: string | undefined;
  apiKeyAuth61?: string | undefined;
  apiKeyAuth62?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$outboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
  apiKeyAuth3: z.string().optional(),
  apiKeyAuth4: z.string().optional(),
  apiKeyAuth5: z.string().optional(),
  apiKeyAuth6: z.string().optional(),
  apiKeyAuth7: z.string().optional(),
  apiKeyAuth8: z.string().optional(),
  apiKeyAuth9: z.string().optional(),
  apiKeyAuth10: z.string().optional(),
  apiKeyAuth11: z.string().optional(),
  apiKeyAuth12: z.string().optional(),
  apiKeyAuth13: z.string().optional(),
  apiKeyAuth14: z.string().optional(),
  apiKeyAuth15: z.string().optional(),
  apiKeyAuth16: z.string().optional(),
  apiKeyAuth17: z.string().optional(),
  apiKeyAuth18: z.string().optional(),
  apiKeyAuth19: z.string().optional(),
  apiKeyAuth20: z.string().optional(),
  apiKeyAuth21: z.string().optional(),
  apiKeyAuth22: z.string().optional(),
  apiKeyAuth23: z.string().optional(),
  apiKeyAuth24: z.string().optional(),
  apiKeyAuth25: z.string().optional(),
  apiKeyAuth26: z.string().optional(),
  apiKeyAuth27: z.string().optional(),
  apiKeyAuth28: z.string().optional(),
  apiKeyAuth29: z.string().optional(),
  apiKeyAuth30: z.string().optional(),
  apiKeyAuth31: z.string().optional(),
  apiKeyAuth32: z.string().optional(),
  apiKeyAuth33: z.string().optional(),
  apiKeyAuth34: z.string().optional(),
  apiKeyAuth35: z.string().optional(),
  apiKeyAuth36: z.string().optional(),
  apiKeyAuth37: z.string().optional(),
  apiKeyAuth38: z.string().optional(),
  apiKeyAuth39: z.string().optional(),
  apiKeyAuth40: z.string().optional(),
  apiKeyAuth41: z.string().optional(),
  apiKeyAuth42: z.string().optional(),
  apiKeyAuth43: z.string().optional(),
  apiKeyAuth44: z.string().optional(),
  apiKeyAuth45: z.string().optional(),
  apiKeyAuth46: z.string().optional(),
  apiKeyAuth47: z.string().optional(),
  apiKeyAuth48: z.string().optional(),
  apiKeyAuth49: z.string().optional(),
  apiKeyAuth50: z.string().optional(),
  apiKeyAuth51: z.string().optional(),
  apiKeyAuth52: z.string().optional(),
  apiKeyAuth53: z.string().optional(),
  apiKeyAuth54: z.string().optional(),
  apiKeyAuth55: z.string().optional(),
  apiKeyAuth56: z.string().optional(),
  apiKeyAuth57: z.string().optional(),
  apiKeyAuth58: z.string().optional(),
  apiKeyAuth59: z.string().optional(),
  apiKeyAuth60: z.string().optional(),
  apiKeyAuth61: z.string().optional(),
  apiKeyAuth62: z.string().optional(),
});

export function sdkGetPartnerConfigSecurityToJSON(
  sdkGetPartnerConfigSecurity: SDKGetPartnerConfigSecurity,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigSecurity$outboundSchema.parse(
      sdkGetPartnerConfigSecurity,
    ),
  );
}
export function sdkGetPartnerConfigSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigSecurity' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigRequest$inboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  site_key: types.string(),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type SDKGetPartnerConfigRequest$Outbound = {
  site_key: string;
};

/** @internal */
export const SDKGetPartnerConfigRequest$outboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigRequest
> = z.object({
  siteKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function sdkGetPartnerConfigRequestToJSON(
  sdkGetPartnerConfigRequest: SDKGetPartnerConfigRequest,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigRequest$outboundSchema.parse(sdkGetPartnerConfigRequest),
  );
}
export function sdkGetPartnerConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigRequest' from JSON`,
  );
}

/** @internal */
export const Integrations$inboundSchema: z.ZodType<
  Integrations,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  site_key: types.optional(types.string()),
  config: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type Integrations$Outbound = {
  enabled?: boolean | undefined;
  site_key?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

/** @internal */
export const Integrations$outboundSchema: z.ZodType<
  Integrations$Outbound,
  z.ZodTypeDef,
  Integrations
> = z.object({
  enabled: z.boolean().optional(),
  siteKey: z.string().optional(),
  config: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function integrationsToJSON(integrations: Integrations): string {
  return JSON.stringify(Integrations$outboundSchema.parse(integrations));
}
export function integrationsFromJSON(
  jsonString: string,
): SafeParseResult<Integrations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Integrations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Integrations' from JSON`,
  );
}

/** @internal */
export const Environment$inboundSchema: z.ZodType<
  Environment,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Environment);
/** @internal */
export const Environment$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  Environment
> = openEnums.outboundSchema(Environment);

/** @internal */
export const SDKGetPartnerConfigResponse$inboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  integrations: types.optional(
    z.record(z.lazy(() => Integrations$inboundSchema)),
  ),
  environment: types.optional(Environment$inboundSchema),
});
/** @internal */
export type SDKGetPartnerConfigResponse$Outbound = {
  integrations?: { [k: string]: Integrations$Outbound } | undefined;
  environment?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigResponse$outboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigResponse
> = z.object({
  integrations: z.record(z.lazy(() => Integrations$outboundSchema)).optional(),
  environment: Environment$outboundSchema.optional(),
});

export function sdkGetPartnerConfigResponseToJSON(
  sdkGetPartnerConfigResponse: SDKGetPartnerConfigResponse,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigResponse$outboundSchema.parse(
      sdkGetPartnerConfigResponse,
    ),
  );
}
export function sdkGetPartnerConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigResponse' from JSON`,
  );
}
