/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKLogoutSecurity = {
  apiKeyAuth: string;
};

export type SDKLogoutRequest = {
  /**
   * The anchor grant token (bss_*) to revoke
   */
  sessionToken: string;
};

/**
 * Token revoked
 */
export type SDKLogoutResponse = {
  success?: boolean | undefined;
  message?: string | undefined;
  tokenFound?: boolean | undefined;
  revokedAt?: Date | undefined;
};

/** @internal */
export const SDKLogoutSecurity$inboundSchema: z.ZodType<
  SDKLogoutSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKLogoutSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKLogoutSecurity$outboundSchema: z.ZodType<
  SDKLogoutSecurity$Outbound,
  z.ZodTypeDef,
  SDKLogoutSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkLogoutSecurityToJSON(
  sdkLogoutSecurity: SDKLogoutSecurity,
): string {
  return JSON.stringify(
    SDKLogoutSecurity$outboundSchema.parse(sdkLogoutSecurity),
  );
}
export function sdkLogoutSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKLogoutSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKLogoutSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKLogoutSecurity' from JSON`,
  );
}

/** @internal */
export const SDKLogoutRequest$inboundSchema: z.ZodType<
  SDKLogoutRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  session_token: types.string(),
}).transform((v) => {
  return remap$(v, {
    "session_token": "sessionToken",
  });
});
/** @internal */
export type SDKLogoutRequest$Outbound = {
  session_token: string;
};

/** @internal */
export const SDKLogoutRequest$outboundSchema: z.ZodType<
  SDKLogoutRequest$Outbound,
  z.ZodTypeDef,
  SDKLogoutRequest
> = z.object({
  sessionToken: z.string(),
}).transform((v) => {
  return remap$(v, {
    sessionToken: "session_token",
  });
});

export function sdkLogoutRequestToJSON(
  sdkLogoutRequest: SDKLogoutRequest,
): string {
  return JSON.stringify(
    SDKLogoutRequest$outboundSchema.parse(sdkLogoutRequest),
  );
}
export function sdkLogoutRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKLogoutRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKLogoutRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKLogoutRequest' from JSON`,
  );
}

/** @internal */
export const SDKLogoutResponse$inboundSchema: z.ZodType<
  SDKLogoutResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  message: types.optional(types.string()),
  token_found: types.optional(types.boolean()),
  revoked_at: types.optional(types.date()),
}).transform((v) => {
  return remap$(v, {
    "token_found": "tokenFound",
    "revoked_at": "revokedAt",
  });
});
/** @internal */
export type SDKLogoutResponse$Outbound = {
  success?: boolean | undefined;
  message?: string | undefined;
  token_found?: boolean | undefined;
  revoked_at?: string | undefined;
};

/** @internal */
export const SDKLogoutResponse$outboundSchema: z.ZodType<
  SDKLogoutResponse$Outbound,
  z.ZodTypeDef,
  SDKLogoutResponse
> = z.object({
  success: z.boolean().optional(),
  message: z.string().optional(),
  tokenFound: z.boolean().optional(),
  revokedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    tokenFound: "token_found",
    revokedAt: "revoked_at",
  });
});

export function sdkLogoutResponseToJSON(
  sdkLogoutResponse: SDKLogoutResponse,
): string {
  return JSON.stringify(
    SDKLogoutResponse$outboundSchema.parse(sdkLogoutResponse),
  );
}
export function sdkLogoutResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKLogoutResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKLogoutResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKLogoutResponse' from JSON`,
  );
}
