/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKGetPartnerConfigSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
};

export type SDKGetPartnerConfigRequest = {
  siteKey: string;
};

export type Integrations = {
  enabled?: boolean | undefined;
  siteKey?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

export const Environment = {
  Test: "test",
  Live: "live",
} as const;
export type Environment = OpenEnum<typeof Environment>;

/**
 * Partner configuration
 */
export type SDKGetPartnerConfigResponse = {
  integrations?: { [k: string]: Integrations } | undefined;
  environment?: Environment | undefined;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$inboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
});
/** @internal */
export type SDKGetPartnerConfigSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$outboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
});

export function sdkGetPartnerConfigSecurityToJSON(
  sdkGetPartnerConfigSecurity: SDKGetPartnerConfigSecurity,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigSecurity$outboundSchema.parse(
      sdkGetPartnerConfigSecurity,
    ),
  );
}
export function sdkGetPartnerConfigSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigSecurity' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigRequest$inboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  site_key: types.string(),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type SDKGetPartnerConfigRequest$Outbound = {
  site_key: string;
};

/** @internal */
export const SDKGetPartnerConfigRequest$outboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigRequest
> = z.object({
  siteKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function sdkGetPartnerConfigRequestToJSON(
  sdkGetPartnerConfigRequest: SDKGetPartnerConfigRequest,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigRequest$outboundSchema.parse(sdkGetPartnerConfigRequest),
  );
}
export function sdkGetPartnerConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigRequest' from JSON`,
  );
}

/** @internal */
export const Integrations$inboundSchema: z.ZodType<
  Integrations,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  site_key: types.optional(types.string()),
  config: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type Integrations$Outbound = {
  enabled?: boolean | undefined;
  site_key?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

/** @internal */
export const Integrations$outboundSchema: z.ZodType<
  Integrations$Outbound,
  z.ZodTypeDef,
  Integrations
> = z.object({
  enabled: z.boolean().optional(),
  siteKey: z.string().optional(),
  config: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function integrationsToJSON(integrations: Integrations): string {
  return JSON.stringify(Integrations$outboundSchema.parse(integrations));
}
export function integrationsFromJSON(
  jsonString: string,
): SafeParseResult<Integrations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Integrations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Integrations' from JSON`,
  );
}

/** @internal */
export const Environment$inboundSchema: z.ZodType<
  Environment,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(Environment);
/** @internal */
export const Environment$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  Environment
> = openEnums.outboundSchema(Environment);

/** @internal */
export const SDKGetPartnerConfigResponse$inboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  integrations: types.optional(
    z.record(z.lazy(() => Integrations$inboundSchema)),
  ),
  environment: types.optional(Environment$inboundSchema),
});
/** @internal */
export type SDKGetPartnerConfigResponse$Outbound = {
  integrations?: { [k: string]: Integrations$Outbound } | undefined;
  environment?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigResponse$outboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigResponse
> = z.object({
  integrations: z.record(z.lazy(() => Integrations$outboundSchema)).optional(),
  environment: Environment$outboundSchema.optional(),
});

export function sdkGetPartnerConfigResponseToJSON(
  sdkGetPartnerConfigResponse: SDKGetPartnerConfigResponse,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigResponse$outboundSchema.parse(
      sdkGetPartnerConfigResponse,
    ),
  );
}
export function sdkGetPartnerConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigResponse' from JSON`,
  );
}
