/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKCreateVerificationLinkSecurity = {
  apiKeyAuth: string;
};

export const SDKTypeRequest = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type SDKTypeRequest = ClosedEnum<typeof SDKTypeRequest>;

/**
 * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
 */
export const Mode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
/**
 * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
 */
export type Mode = ClosedEnum<typeof Mode>;

export type SDKCreateVerificationLinkRequest = {
  /**
   * **Deprecated.** Ignored — the value is discarded and never stored. Identity does not
   *
   * @remarks
   * reach BotShield: verification is keyed on an opaque identifier. Use `partner_user_ref`
   * if you need to correlate the verification with your own user. Will be removed in the
   * next major version.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  userEmail?: string | undefined;
  /**
   * Where the web flow returns after verification.
   */
  returnUrl?: string | undefined;
  webhookUrl?: string | undefined;
  /**
   * The gate this request runs (the gate's action name, as listed in the Console under BotShield Census).
   */
  scope?: string | undefined;
  sdkType?: SDKTypeRequest | undefined;
  /**
   * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
   */
  mode?: Mode | undefined;
  /**
   * Returning user ID to skip onboarding
   */
  botshieldUserId?: string | undefined;
  /**
   * Your own reference for this user (hashed at rest, never returned). Enables BotShield ID continuity: on later visits a returning human evaluates as human_verified without a ceremony.
   */
  partnerUserRef?: string | undefined;
  /**
   * Write the partner_user_ref ↔ BotShield ID linkage after a successful verification. Set false as a compliance escape hatch.
   */
  linkOnVerify?: boolean | undefined;
  /**
   * The req_* id returned by the client pre-check (signal/evaluate) when this request is its presence ceremony; correlates the two events.
   */
  parentRequestId?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export const SDKCreateVerificationLinkSDKTypeResponse = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type SDKCreateVerificationLinkSDKTypeResponse = OpenEnum<
  typeof SDKCreateVerificationLinkSDKTypeResponse
>;

export const AuthMode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
export type AuthMode = OpenEnum<typeof AuthMode>;

export type SDKCreateVerificationLinkOrganization = {
  id?: string | undefined;
};

export type SDKCreateVerificationLinkDataData = {
  requestId: string;
  deepLink: string;
  webUrl: string;
  qrCodeUrl: string;
  expiresAt: Date;
  sdkType?: SDKCreateVerificationLinkSDKTypeResponse | undefined;
  authMode?: AuthMode | undefined;
  scope?: string | undefined;
  organization?: SDKCreateVerificationLinkOrganization | undefined;
  /**
   * Number of the user's registered devices the request was pushed to (0 when the user is unknown or has no devices).
   */
  pushedToDevices: number;
};

export type SDKCreateVerificationLinkData = {
  data?: SDKCreateVerificationLinkDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Verification link created. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: 400 (partner not found / gate not active), 401, 403 (gate not in the token allowlist), 409 (pending request already exists — call revoke-verification).
 */
export type SDKCreateVerificationLinkResponse = {
  data: SDKCreateVerificationLinkData;
};

/** @internal */
export const SDKCreateVerificationLinkSecurity$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKCreateVerificationLinkSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKCreateVerificationLinkSecurity$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkSecurity$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkCreateVerificationLinkSecurityToJSON(
  sdkCreateVerificationLinkSecurity: SDKCreateVerificationLinkSecurity,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkSecurity$outboundSchema.parse(
      sdkCreateVerificationLinkSecurity,
    ),
  );
}
export function sdkCreateVerificationLinkSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkSecurity' from JSON`,
  );
}

/** @internal */
export const SDKTypeRequest$inboundSchema: z.ZodNativeEnum<
  typeof SDKTypeRequest
> = z.nativeEnum(SDKTypeRequest);
/** @internal */
export const SDKTypeRequest$outboundSchema: z.ZodNativeEnum<
  typeof SDKTypeRequest
> = SDKTypeRequest$inboundSchema;

/** @internal */
export const Mode$inboundSchema: z.ZodNativeEnum<typeof Mode> = z.nativeEnum(
  Mode,
);
/** @internal */
export const Mode$outboundSchema: z.ZodNativeEnum<typeof Mode> =
  Mode$inboundSchema;

/** @internal */
export const SDKCreateVerificationLinkRequest$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_email: types.optional(types.string()),
  return_url: types.optional(types.string()),
  webhook_url: types.optional(types.string()),
  scope: types.optional(types.string()),
  sdk_type: types.optional(SDKTypeRequest$inboundSchema),
  mode: Mode$inboundSchema.default("linked-account"),
  botshield_user_id: types.optional(types.string()),
  partner_user_ref: types.optional(types.string()),
  link_on_verify: types.boolean().default(true),
  parent_request_id: types.optional(types.string()),
  metadata: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "user_email": "userEmail",
    "return_url": "returnUrl",
    "webhook_url": "webhookUrl",
    "sdk_type": "sdkType",
    "botshield_user_id": "botshieldUserId",
    "partner_user_ref": "partnerUserRef",
    "link_on_verify": "linkOnVerify",
    "parent_request_id": "parentRequestId",
  });
});
/** @internal */
export type SDKCreateVerificationLinkRequest$Outbound = {
  user_email?: string | undefined;
  return_url?: string | undefined;
  webhook_url?: string | undefined;
  scope?: string | undefined;
  sdk_type?: string | undefined;
  mode: string;
  botshield_user_id?: string | undefined;
  partner_user_ref?: string | undefined;
  link_on_verify: boolean;
  parent_request_id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkRequest$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkRequest$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkRequest
> = z.object({
  userEmail: z.string().optional(),
  returnUrl: z.string().optional(),
  webhookUrl: z.string().optional(),
  scope: z.string().optional(),
  sdkType: SDKTypeRequest$outboundSchema.optional(),
  mode: Mode$outboundSchema.default("linked-account"),
  botshieldUserId: z.string().optional(),
  partnerUserRef: z.string().optional(),
  linkOnVerify: z.boolean().default(true),
  parentRequestId: z.string().optional(),
  metadata: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    userEmail: "user_email",
    returnUrl: "return_url",
    webhookUrl: "webhook_url",
    sdkType: "sdk_type",
    botshieldUserId: "botshield_user_id",
    partnerUserRef: "partner_user_ref",
    linkOnVerify: "link_on_verify",
    parentRequestId: "parent_request_id",
  });
});

export function sdkCreateVerificationLinkRequestToJSON(
  sdkCreateVerificationLinkRequest: SDKCreateVerificationLinkRequest,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkRequest$outboundSchema.parse(
      sdkCreateVerificationLinkRequest,
    ),
  );
}
export function sdkCreateVerificationLinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkRequest' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkSDKTypeResponse$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkSDKTypeResponse,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SDKCreateVerificationLinkSDKTypeResponse);
/** @internal */
export const SDKCreateVerificationLinkSDKTypeResponse$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SDKCreateVerificationLinkSDKTypeResponse
> = openEnums.outboundSchema(SDKCreateVerificationLinkSDKTypeResponse);

/** @internal */
export const AuthMode$inboundSchema: z.ZodType<
  AuthMode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(AuthMode);
/** @internal */
export const AuthMode$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  AuthMode
> = openEnums.outboundSchema(AuthMode);

/** @internal */
export const SDKCreateVerificationLinkOrganization$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.optional(types.string()),
});
/** @internal */
export type SDKCreateVerificationLinkOrganization$Outbound = {
  id?: string | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkOrganization$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkOrganization$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkOrganization
> = z.object({
  id: z.string().optional(),
});

export function sdkCreateVerificationLinkOrganizationToJSON(
  sdkCreateVerificationLinkOrganization: SDKCreateVerificationLinkOrganization,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkOrganization$outboundSchema.parse(
      sdkCreateVerificationLinkOrganization,
    ),
  );
}
export function sdkCreateVerificationLinkOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDKCreateVerificationLinkOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkOrganization' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkDataData$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
  deep_link: types.string(),
  web_url: types.string(),
  qr_code_url: types.string(),
  expires_at: types.date(),
  sdk_type: types.optional(
    SDKCreateVerificationLinkSDKTypeResponse$inboundSchema,
  ),
  auth_mode: types.optional(AuthMode$inboundSchema),
  scope: types.optional(types.string()),
  organization: types.optional(
    z.lazy(() => SDKCreateVerificationLinkOrganization$inboundSchema),
  ),
  pushed_to_devices: types.number(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "deep_link": "deepLink",
    "web_url": "webUrl",
    "qr_code_url": "qrCodeUrl",
    "expires_at": "expiresAt",
    "sdk_type": "sdkType",
    "auth_mode": "authMode",
    "pushed_to_devices": "pushedToDevices",
  });
});
/** @internal */
export type SDKCreateVerificationLinkDataData$Outbound = {
  request_id: string;
  deep_link: string;
  web_url: string;
  qr_code_url: string;
  expires_at: string;
  sdk_type?: string | undefined;
  auth_mode?: string | undefined;
  scope?: string | undefined;
  organization?: SDKCreateVerificationLinkOrganization$Outbound | undefined;
  pushed_to_devices: number;
};

/** @internal */
export const SDKCreateVerificationLinkDataData$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkDataData$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkDataData
> = z.object({
  requestId: z.string(),
  deepLink: z.string(),
  webUrl: z.string(),
  qrCodeUrl: z.string(),
  expiresAt: z.date().transform(v => v.toISOString()),
  sdkType: SDKCreateVerificationLinkSDKTypeResponse$outboundSchema.optional(),
  authMode: AuthMode$outboundSchema.optional(),
  scope: z.string().optional(),
  organization: z.lazy(() =>
    SDKCreateVerificationLinkOrganization$outboundSchema
  ).optional(),
  pushedToDevices: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    deepLink: "deep_link",
    webUrl: "web_url",
    qrCodeUrl: "qr_code_url",
    expiresAt: "expires_at",
    sdkType: "sdk_type",
    authMode: "auth_mode",
    pushedToDevices: "pushed_to_devices",
  });
});

export function sdkCreateVerificationLinkDataDataToJSON(
  sdkCreateVerificationLinkDataData: SDKCreateVerificationLinkDataData,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkDataData$outboundSchema.parse(
      sdkCreateVerificationLinkDataData,
    ),
  );
}
export function sdkCreateVerificationLinkDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkDataData' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkData$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(
    z.lazy(() => SDKCreateVerificationLinkDataData$inboundSchema),
  ),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKCreateVerificationLinkData$Outbound = {
  data?: SDKCreateVerificationLinkDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkData$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkData$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkData
> = z.object({
  data: z.lazy(() => SDKCreateVerificationLinkDataData$outboundSchema)
    .optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkCreateVerificationLinkDataToJSON(
  sdkCreateVerificationLinkData: SDKCreateVerificationLinkData,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkData$outboundSchema.parse(
      sdkCreateVerificationLinkData,
    ),
  );
}
export function sdkCreateVerificationLinkDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkData' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkResponse$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKCreateVerificationLinkData$inboundSchema),
});
/** @internal */
export type SDKCreateVerificationLinkResponse$Outbound = {
  data: SDKCreateVerificationLinkData$Outbound;
};

/** @internal */
export const SDKCreateVerificationLinkResponse$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkResponse$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkResponse
> = z.object({
  data: z.lazy(() => SDKCreateVerificationLinkData$outboundSchema),
});

export function sdkCreateVerificationLinkResponseToJSON(
  sdkCreateVerificationLinkResponse: SDKCreateVerificationLinkResponse,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkResponse$outboundSchema.parse(
      sdkCreateVerificationLinkResponse,
    ),
  );
}
export function sdkCreateVerificationLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkResponse' from JSON`,
  );
}
