/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKCreateVerificationLinkSecurity = {
  apiKeyAuth: string;
};

export const SDKTypeRequest = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type SDKTypeRequest = ClosedEnum<typeof SDKTypeRequest>;

/**
 * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
 */
export const Mode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
/**
 * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
 */
export type Mode = ClosedEnum<typeof Mode>;

export type SDKCreateVerificationLinkRequest = {
  userEmail?: string | undefined;
  returnUrl?: string | undefined;
  webhookUrl?: string | undefined;
  scope?: string | undefined;
  sdkType?: SDKTypeRequest | undefined;
  /**
   * linked-account = OAuth+passkey, private = direct WebAuthn (no PII)
   */
  mode?: Mode | undefined;
  /**
   * Returning user ID to skip onboarding
   */
  botshieldUserId?: string | undefined;
  /**
   * Tamper-proof Signal Pixel token (bs_sig_...) for server-side score correlation
   */
  signalToken?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

export const DataSDKType = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type DataSDKType = OpenEnum<typeof DataSDKType>;

export const SDKCreateVerificationLinkAuthMode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
export type SDKCreateVerificationLinkAuthMode = OpenEnum<
  typeof SDKCreateVerificationLinkAuthMode
>;

export type SDKCreateVerificationLinkOrganization = {
  id?: string | undefined;
};

export type SDKCreateVerificationLinkData = {
  requestId: string;
  deepLink: string;
  webUrl: string;
  qrCodeUrl: string;
  expiresAt: Date;
  sdkType?: DataSDKType | undefined;
  authMode?: SDKCreateVerificationLinkAuthMode | undefined;
  scope?: string | undefined;
  organization?: SDKCreateVerificationLinkOrganization | undefined;
};

/**
 * Verification link created
 */
export type SDKCreateVerificationLinkResponse = {
  data: SDKCreateVerificationLinkData;
};

/** @internal */
export const SDKCreateVerificationLinkSecurity$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKCreateVerificationLinkSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKCreateVerificationLinkSecurity$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkSecurity$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkCreateVerificationLinkSecurityToJSON(
  sdkCreateVerificationLinkSecurity: SDKCreateVerificationLinkSecurity,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkSecurity$outboundSchema.parse(
      sdkCreateVerificationLinkSecurity,
    ),
  );
}
export function sdkCreateVerificationLinkSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkSecurity' from JSON`,
  );
}

/** @internal */
export const SDKTypeRequest$inboundSchema: z.ZodNativeEnum<
  typeof SDKTypeRequest
> = z.nativeEnum(SDKTypeRequest);
/** @internal */
export const SDKTypeRequest$outboundSchema: z.ZodNativeEnum<
  typeof SDKTypeRequest
> = SDKTypeRequest$inboundSchema;

/** @internal */
export const Mode$inboundSchema: z.ZodNativeEnum<typeof Mode> = z.nativeEnum(
  Mode,
);
/** @internal */
export const Mode$outboundSchema: z.ZodNativeEnum<typeof Mode> =
  Mode$inboundSchema;

/** @internal */
export const SDKCreateVerificationLinkRequest$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_email: types.optional(types.string()),
  return_url: types.optional(types.string()),
  webhook_url: types.optional(types.string()),
  scope: types.optional(types.string()),
  sdk_type: types.optional(SDKTypeRequest$inboundSchema),
  mode: Mode$inboundSchema.default("linked-account"),
  botshield_user_id: types.optional(types.string()),
  signal_token: types.optional(types.string()),
  metadata: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "user_email": "userEmail",
    "return_url": "returnUrl",
    "webhook_url": "webhookUrl",
    "sdk_type": "sdkType",
    "botshield_user_id": "botshieldUserId",
    "signal_token": "signalToken",
  });
});
/** @internal */
export type SDKCreateVerificationLinkRequest$Outbound = {
  user_email?: string | undefined;
  return_url?: string | undefined;
  webhook_url?: string | undefined;
  scope?: string | undefined;
  sdk_type?: string | undefined;
  mode: string;
  botshield_user_id?: string | undefined;
  signal_token?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkRequest$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkRequest$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkRequest
> = z.object({
  userEmail: z.string().optional(),
  returnUrl: z.string().optional(),
  webhookUrl: z.string().optional(),
  scope: z.string().optional(),
  sdkType: SDKTypeRequest$outboundSchema.optional(),
  mode: Mode$outboundSchema.default("linked-account"),
  botshieldUserId: z.string().optional(),
  signalToken: z.string().optional(),
  metadata: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    userEmail: "user_email",
    returnUrl: "return_url",
    webhookUrl: "webhook_url",
    sdkType: "sdk_type",
    botshieldUserId: "botshield_user_id",
    signalToken: "signal_token",
  });
});

export function sdkCreateVerificationLinkRequestToJSON(
  sdkCreateVerificationLinkRequest: SDKCreateVerificationLinkRequest,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkRequest$outboundSchema.parse(
      sdkCreateVerificationLinkRequest,
    ),
  );
}
export function sdkCreateVerificationLinkRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkRequest' from JSON`,
  );
}

/** @internal */
export const DataSDKType$inboundSchema: z.ZodType<
  DataSDKType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(DataSDKType);
/** @internal */
export const DataSDKType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  DataSDKType
> = openEnums.outboundSchema(DataSDKType);

/** @internal */
export const SDKCreateVerificationLinkAuthMode$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkAuthMode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SDKCreateVerificationLinkAuthMode);
/** @internal */
export const SDKCreateVerificationLinkAuthMode$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SDKCreateVerificationLinkAuthMode
> = openEnums.outboundSchema(SDKCreateVerificationLinkAuthMode);

/** @internal */
export const SDKCreateVerificationLinkOrganization$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.optional(types.string()),
});
/** @internal */
export type SDKCreateVerificationLinkOrganization$Outbound = {
  id?: string | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkOrganization$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkOrganization$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkOrganization
> = z.object({
  id: z.string().optional(),
});

export function sdkCreateVerificationLinkOrganizationToJSON(
  sdkCreateVerificationLinkOrganization: SDKCreateVerificationLinkOrganization,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkOrganization$outboundSchema.parse(
      sdkCreateVerificationLinkOrganization,
    ),
  );
}
export function sdkCreateVerificationLinkOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SDKCreateVerificationLinkOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkOrganization' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkData$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkData,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
  deep_link: types.string(),
  web_url: types.string(),
  qr_code_url: types.string(),
  expires_at: types.date(),
  sdk_type: types.optional(DataSDKType$inboundSchema),
  auth_mode: types.optional(SDKCreateVerificationLinkAuthMode$inboundSchema),
  scope: types.optional(types.string()),
  organization: types.optional(
    z.lazy(() => SDKCreateVerificationLinkOrganization$inboundSchema),
  ),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "deep_link": "deepLink",
    "web_url": "webUrl",
    "qr_code_url": "qrCodeUrl",
    "expires_at": "expiresAt",
    "sdk_type": "sdkType",
    "auth_mode": "authMode",
  });
});
/** @internal */
export type SDKCreateVerificationLinkData$Outbound = {
  request_id: string;
  deep_link: string;
  web_url: string;
  qr_code_url: string;
  expires_at: string;
  sdk_type?: string | undefined;
  auth_mode?: string | undefined;
  scope?: string | undefined;
  organization?: SDKCreateVerificationLinkOrganization$Outbound | undefined;
};

/** @internal */
export const SDKCreateVerificationLinkData$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkData$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkData
> = z.object({
  requestId: z.string(),
  deepLink: z.string(),
  webUrl: z.string(),
  qrCodeUrl: z.string(),
  expiresAt: z.date().transform(v => v.toISOString()),
  sdkType: DataSDKType$outboundSchema.optional(),
  authMode: SDKCreateVerificationLinkAuthMode$outboundSchema.optional(),
  scope: z.string().optional(),
  organization: z.lazy(() =>
    SDKCreateVerificationLinkOrganization$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    deepLink: "deep_link",
    webUrl: "web_url",
    qrCodeUrl: "qr_code_url",
    expiresAt: "expires_at",
    sdkType: "sdk_type",
    authMode: "auth_mode",
  });
});

export function sdkCreateVerificationLinkDataToJSON(
  sdkCreateVerificationLinkData: SDKCreateVerificationLinkData,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkData$outboundSchema.parse(
      sdkCreateVerificationLinkData,
    ),
  );
}
export function sdkCreateVerificationLinkDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkData' from JSON`,
  );
}

/** @internal */
export const SDKCreateVerificationLinkResponse$inboundSchema: z.ZodType<
  SDKCreateVerificationLinkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKCreateVerificationLinkData$inboundSchema),
});
/** @internal */
export type SDKCreateVerificationLinkResponse$Outbound = {
  data: SDKCreateVerificationLinkData$Outbound;
};

/** @internal */
export const SDKCreateVerificationLinkResponse$outboundSchema: z.ZodType<
  SDKCreateVerificationLinkResponse$Outbound,
  z.ZodTypeDef,
  SDKCreateVerificationLinkResponse
> = z.object({
  data: z.lazy(() => SDKCreateVerificationLinkData$outboundSchema),
});

export function sdkCreateVerificationLinkResponseToJSON(
  sdkCreateVerificationLinkResponse: SDKCreateVerificationLinkResponse,
): string {
  return JSON.stringify(
    SDKCreateVerificationLinkResponse$outboundSchema.parse(
      sdkCreateVerificationLinkResponse,
    ),
  );
}
export function sdkCreateVerificationLinkResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateVerificationLinkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateVerificationLinkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateVerificationLinkResponse' from JSON`,
  );
}
