/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKRevokeVerificationSecurity = {
  apiKeyAuth: string;
};

export type SDKRevokeVerificationRequest = {
  /**
   * The gate's action name.
   */
  scope: string;
  /**
   * **Deprecated.** Use `partner_user_id` to identify whose verification to revoke.
   *
   * @remarks
   * Will be removed in the next major version.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  userEmail?: string | undefined;
  partnerUserId?: string | undefined;
};

export type SDKRevokeVerificationDataData = {
  success?: boolean | undefined;
  revokedCount?: number | undefined;
  message?: string | undefined;
};

export type SDKRevokeVerificationData = {
  data?: SDKRevokeVerificationDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Revocation result. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: 401.
 */
export type SDKRevokeVerificationResponse = {
  data: SDKRevokeVerificationData;
};

/** @internal */
export const SDKRevokeVerificationSecurity$inboundSchema: z.ZodType<
  SDKRevokeVerificationSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKRevokeVerificationSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKRevokeVerificationSecurity$outboundSchema: z.ZodType<
  SDKRevokeVerificationSecurity$Outbound,
  z.ZodTypeDef,
  SDKRevokeVerificationSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkRevokeVerificationSecurityToJSON(
  sdkRevokeVerificationSecurity: SDKRevokeVerificationSecurity,
): string {
  return JSON.stringify(
    SDKRevokeVerificationSecurity$outboundSchema.parse(
      sdkRevokeVerificationSecurity,
    ),
  );
}
export function sdkRevokeVerificationSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKRevokeVerificationSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKRevokeVerificationSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKRevokeVerificationSecurity' from JSON`,
  );
}

/** @internal */
export const SDKRevokeVerificationRequest$inboundSchema: z.ZodType<
  SDKRevokeVerificationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  scope: types.string(),
  user_email: types.optional(types.string()),
  partner_user_id: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "user_email": "userEmail",
    "partner_user_id": "partnerUserId",
  });
});
/** @internal */
export type SDKRevokeVerificationRequest$Outbound = {
  scope: string;
  user_email?: string | undefined;
  partner_user_id?: string | undefined;
};

/** @internal */
export const SDKRevokeVerificationRequest$outboundSchema: z.ZodType<
  SDKRevokeVerificationRequest$Outbound,
  z.ZodTypeDef,
  SDKRevokeVerificationRequest
> = z.object({
  scope: z.string(),
  userEmail: z.string().optional(),
  partnerUserId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    userEmail: "user_email",
    partnerUserId: "partner_user_id",
  });
});

export function sdkRevokeVerificationRequestToJSON(
  sdkRevokeVerificationRequest: SDKRevokeVerificationRequest,
): string {
  return JSON.stringify(
    SDKRevokeVerificationRequest$outboundSchema.parse(
      sdkRevokeVerificationRequest,
    ),
  );
}
export function sdkRevokeVerificationRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKRevokeVerificationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKRevokeVerificationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKRevokeVerificationRequest' from JSON`,
  );
}

/** @internal */
export const SDKRevokeVerificationDataData$inboundSchema: z.ZodType<
  SDKRevokeVerificationDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  revoked_count: types.optional(types.number()),
  message: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "revoked_count": "revokedCount",
  });
});
/** @internal */
export type SDKRevokeVerificationDataData$Outbound = {
  success?: boolean | undefined;
  revoked_count?: number | undefined;
  message?: string | undefined;
};

/** @internal */
export const SDKRevokeVerificationDataData$outboundSchema: z.ZodType<
  SDKRevokeVerificationDataData$Outbound,
  z.ZodTypeDef,
  SDKRevokeVerificationDataData
> = z.object({
  success: z.boolean().optional(),
  revokedCount: z.number().int().optional(),
  message: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    revokedCount: "revoked_count",
  });
});

export function sdkRevokeVerificationDataDataToJSON(
  sdkRevokeVerificationDataData: SDKRevokeVerificationDataData,
): string {
  return JSON.stringify(
    SDKRevokeVerificationDataData$outboundSchema.parse(
      sdkRevokeVerificationDataData,
    ),
  );
}
export function sdkRevokeVerificationDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKRevokeVerificationDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKRevokeVerificationDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKRevokeVerificationDataData' from JSON`,
  );
}

/** @internal */
export const SDKRevokeVerificationData$inboundSchema: z.ZodType<
  SDKRevokeVerificationData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(
    z.lazy(() => SDKRevokeVerificationDataData$inboundSchema),
  ),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKRevokeVerificationData$Outbound = {
  data?: SDKRevokeVerificationDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKRevokeVerificationData$outboundSchema: z.ZodType<
  SDKRevokeVerificationData$Outbound,
  z.ZodTypeDef,
  SDKRevokeVerificationData
> = z.object({
  data: z.lazy(() => SDKRevokeVerificationDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkRevokeVerificationDataToJSON(
  sdkRevokeVerificationData: SDKRevokeVerificationData,
): string {
  return JSON.stringify(
    SDKRevokeVerificationData$outboundSchema.parse(sdkRevokeVerificationData),
  );
}
export function sdkRevokeVerificationDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKRevokeVerificationData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKRevokeVerificationData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKRevokeVerificationData' from JSON`,
  );
}

/** @internal */
export const SDKRevokeVerificationResponse$inboundSchema: z.ZodType<
  SDKRevokeVerificationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKRevokeVerificationData$inboundSchema),
});
/** @internal */
export type SDKRevokeVerificationResponse$Outbound = {
  data: SDKRevokeVerificationData$Outbound;
};

/** @internal */
export const SDKRevokeVerificationResponse$outboundSchema: z.ZodType<
  SDKRevokeVerificationResponse$Outbound,
  z.ZodTypeDef,
  SDKRevokeVerificationResponse
> = z.object({
  data: z.lazy(() => SDKRevokeVerificationData$outboundSchema),
});

export function sdkRevokeVerificationResponseToJSON(
  sdkRevokeVerificationResponse: SDKRevokeVerificationResponse,
): string {
  return JSON.stringify(
    SDKRevokeVerificationResponse$outboundSchema.parse(
      sdkRevokeVerificationResponse,
    ),
  );
}
export function sdkRevokeVerificationResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKRevokeVerificationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKRevokeVerificationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKRevokeVerificationResponse' from JSON`,
  );
}
