/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKStoreSignalRequest = {
  siteKey: string;
  score: number;
  edgeScore?: number | undefined;
  clientScore?: number | undefined;
  ipHash?: string | undefined;
  uaHash?: string | undefined;
  country?: string | undefined;
  signals?: { [k: string]: any } | undefined;
};

export type SDKStoreSignalDataData = {
  /**
   * Opaque tamper-proof token (bs_sig_...)
   */
  signalToken?: string | undefined;
  expiresAt?: Date | undefined;
  /**
   * Present instead of signal_token when the store failed ('Failed to store signal').
   */
  error?: string | undefined;
};

export type SDKStoreSignalData = {
  data?: SDKStoreSignalDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Signal stored. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: none — a failed store returns data.data.error.
 */
export type SDKStoreSignalResponse = {
  data: SDKStoreSignalData;
};

/** @internal */
export const SDKStoreSignalRequest$inboundSchema: z.ZodType<
  SDKStoreSignalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  site_key: types.string(),
  score: types.number(),
  edge_score: types.optional(types.number()),
  client_score: types.optional(types.number()),
  ip_hash: types.optional(types.string()),
  ua_hash: types.optional(types.string()),
  country: types.optional(types.string()),
  signals: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
    "edge_score": "edgeScore",
    "client_score": "clientScore",
    "ip_hash": "ipHash",
    "ua_hash": "uaHash",
  });
});
/** @internal */
export type SDKStoreSignalRequest$Outbound = {
  site_key: string;
  score: number;
  edge_score?: number | undefined;
  client_score?: number | undefined;
  ip_hash?: string | undefined;
  ua_hash?: string | undefined;
  country?: string | undefined;
  signals?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDKStoreSignalRequest$outboundSchema: z.ZodType<
  SDKStoreSignalRequest$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalRequest
> = z.object({
  siteKey: z.string(),
  score: z.number().int(),
  edgeScore: z.number().int().optional(),
  clientScore: z.number().int().optional(),
  ipHash: z.string().optional(),
  uaHash: z.string().optional(),
  country: z.string().optional(),
  signals: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
    edgeScore: "edge_score",
    clientScore: "client_score",
    ipHash: "ip_hash",
    uaHash: "ua_hash",
  });
});

export function sdkStoreSignalRequestToJSON(
  sdkStoreSignalRequest: SDKStoreSignalRequest,
): string {
  return JSON.stringify(
    SDKStoreSignalRequest$outboundSchema.parse(sdkStoreSignalRequest),
  );
}
export function sdkStoreSignalRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalRequest' from JSON`,
  );
}

/** @internal */
export const SDKStoreSignalDataData$inboundSchema: z.ZodType<
  SDKStoreSignalDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  signal_token: types.optional(types.string()),
  expires_at: types.optional(types.date()),
  error: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "signal_token": "signalToken",
    "expires_at": "expiresAt",
  });
});
/** @internal */
export type SDKStoreSignalDataData$Outbound = {
  signal_token?: string | undefined;
  expires_at?: string | undefined;
  error?: string | undefined;
};

/** @internal */
export const SDKStoreSignalDataData$outboundSchema: z.ZodType<
  SDKStoreSignalDataData$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalDataData
> = z.object({
  signalToken: z.string().optional(),
  expiresAt: z.date().transform(v => v.toISOString()).optional(),
  error: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signalToken: "signal_token",
    expiresAt: "expires_at",
  });
});

export function sdkStoreSignalDataDataToJSON(
  sdkStoreSignalDataData: SDKStoreSignalDataData,
): string {
  return JSON.stringify(
    SDKStoreSignalDataData$outboundSchema.parse(sdkStoreSignalDataData),
  );
}
export function sdkStoreSignalDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalDataData' from JSON`,
  );
}

/** @internal */
export const SDKStoreSignalData$inboundSchema: z.ZodType<
  SDKStoreSignalData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SDKStoreSignalDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKStoreSignalData$Outbound = {
  data?: SDKStoreSignalDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKStoreSignalData$outboundSchema: z.ZodType<
  SDKStoreSignalData$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalData
> = z.object({
  data: z.lazy(() => SDKStoreSignalDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkStoreSignalDataToJSON(
  sdkStoreSignalData: SDKStoreSignalData,
): string {
  return JSON.stringify(
    SDKStoreSignalData$outboundSchema.parse(sdkStoreSignalData),
  );
}
export function sdkStoreSignalDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalData' from JSON`,
  );
}

/** @internal */
export const SDKStoreSignalResponse$inboundSchema: z.ZodType<
  SDKStoreSignalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKStoreSignalData$inboundSchema),
});
/** @internal */
export type SDKStoreSignalResponse$Outbound = {
  data: SDKStoreSignalData$Outbound;
};

/** @internal */
export const SDKStoreSignalResponse$outboundSchema: z.ZodType<
  SDKStoreSignalResponse$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalResponse
> = z.object({
  data: z.lazy(() => SDKStoreSignalData$outboundSchema),
});

export function sdkStoreSignalResponseToJSON(
  sdkStoreSignalResponse: SDKStoreSignalResponse,
): string {
  return JSON.stringify(
    SDKStoreSignalResponse$outboundSchema.parse(sdkStoreSignalResponse),
  );
}
export function sdkStoreSignalResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalResponse' from JSON`,
  );
}
