/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKGetPartnerConfigSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

export type SDKGetPartnerConfigRequest = {
  siteKey: string;
};

export type Integrations = {
  enabled?: boolean | undefined;
  siteKey?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

/**
 * Site key environment. Omitted when the site key is unknown or has no enabled integrations.
 */
export const SDKGetPartnerConfigEnvironment = {
  Test: "test",
  Live: "live",
} as const;
/**
 * Site key environment. Omitted when the site key is unknown or has no enabled integrations.
 */
export type SDKGetPartnerConfigEnvironment = OpenEnum<
  typeof SDKGetPartnerConfigEnvironment
>;

export type SDKGetPartnerConfigDataData = {
  integrations: { [k: string]: Integrations };
  /**
   * Site key environment. Omitted when the site key is unknown or has no enabled integrations.
   */
  environment?: SDKGetPartnerConfigEnvironment | undefined;
};

export type SDKGetPartnerConfigData = {
  data?: SDKGetPartnerConfigDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Partner configuration. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: none — unknown site key returns empty integrations.
 */
export type SDKGetPartnerConfigResponse = {
  data: SDKGetPartnerConfigData;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$inboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
});
/** @internal */
export type SDKGetPartnerConfigSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigSecurity$outboundSchema: z.ZodType<
  SDKGetPartnerConfigSecurity$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
});

export function sdkGetPartnerConfigSecurityToJSON(
  sdkGetPartnerConfigSecurity: SDKGetPartnerConfigSecurity,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigSecurity$outboundSchema.parse(
      sdkGetPartnerConfigSecurity,
    ),
  );
}
export function sdkGetPartnerConfigSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigSecurity' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigRequest$inboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  site_key: types.string(),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type SDKGetPartnerConfigRequest$Outbound = {
  site_key: string;
};

/** @internal */
export const SDKGetPartnerConfigRequest$outboundSchema: z.ZodType<
  SDKGetPartnerConfigRequest$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigRequest
> = z.object({
  siteKey: z.string(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function sdkGetPartnerConfigRequestToJSON(
  sdkGetPartnerConfigRequest: SDKGetPartnerConfigRequest,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigRequest$outboundSchema.parse(sdkGetPartnerConfigRequest),
  );
}
export function sdkGetPartnerConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigRequest' from JSON`,
  );
}

/** @internal */
export const Integrations$inboundSchema: z.ZodType<
  Integrations,
  z.ZodTypeDef,
  unknown
> = z.object({
  enabled: types.optional(types.boolean()),
  site_key: types.optional(types.string()),
  config: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
  });
});
/** @internal */
export type Integrations$Outbound = {
  enabled?: boolean | undefined;
  site_key?: string | undefined;
  config?: { [k: string]: any } | undefined;
};

/** @internal */
export const Integrations$outboundSchema: z.ZodType<
  Integrations$Outbound,
  z.ZodTypeDef,
  Integrations
> = z.object({
  enabled: z.boolean().optional(),
  siteKey: z.string().optional(),
  config: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
  });
});

export function integrationsToJSON(integrations: Integrations): string {
  return JSON.stringify(Integrations$outboundSchema.parse(integrations));
}
export function integrationsFromJSON(
  jsonString: string,
): SafeParseResult<Integrations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Integrations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Integrations' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigEnvironment$inboundSchema: z.ZodType<
  SDKGetPartnerConfigEnvironment,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SDKGetPartnerConfigEnvironment);
/** @internal */
export const SDKGetPartnerConfigEnvironment$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SDKGetPartnerConfigEnvironment
> = openEnums.outboundSchema(SDKGetPartnerConfigEnvironment);

/** @internal */
export const SDKGetPartnerConfigDataData$inboundSchema: z.ZodType<
  SDKGetPartnerConfigDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  integrations: z.record(z.lazy(() => Integrations$inboundSchema)),
  environment: types.optional(SDKGetPartnerConfigEnvironment$inboundSchema),
});
/** @internal */
export type SDKGetPartnerConfigDataData$Outbound = {
  integrations: { [k: string]: Integrations$Outbound };
  environment?: string | undefined;
};

/** @internal */
export const SDKGetPartnerConfigDataData$outboundSchema: z.ZodType<
  SDKGetPartnerConfigDataData$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigDataData
> = z.object({
  integrations: z.record(z.lazy(() => Integrations$outboundSchema)),
  environment: SDKGetPartnerConfigEnvironment$outboundSchema.optional(),
});

export function sdkGetPartnerConfigDataDataToJSON(
  sdkGetPartnerConfigDataData: SDKGetPartnerConfigDataData,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigDataData$outboundSchema.parse(
      sdkGetPartnerConfigDataData,
    ),
  );
}
export function sdkGetPartnerConfigDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigDataData' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigData$inboundSchema: z.ZodType<
  SDKGetPartnerConfigData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SDKGetPartnerConfigDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKGetPartnerConfigData$Outbound = {
  data?: SDKGetPartnerConfigDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKGetPartnerConfigData$outboundSchema: z.ZodType<
  SDKGetPartnerConfigData$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigData
> = z.object({
  data: z.lazy(() => SDKGetPartnerConfigDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkGetPartnerConfigDataToJSON(
  sdkGetPartnerConfigData: SDKGetPartnerConfigData,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigData$outboundSchema.parse(sdkGetPartnerConfigData),
  );
}
export function sdkGetPartnerConfigDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigData' from JSON`,
  );
}

/** @internal */
export const SDKGetPartnerConfigResponse$inboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKGetPartnerConfigData$inboundSchema),
});
/** @internal */
export type SDKGetPartnerConfigResponse$Outbound = {
  data: SDKGetPartnerConfigData$Outbound;
};

/** @internal */
export const SDKGetPartnerConfigResponse$outboundSchema: z.ZodType<
  SDKGetPartnerConfigResponse$Outbound,
  z.ZodTypeDef,
  SDKGetPartnerConfigResponse
> = z.object({
  data: z.lazy(() => SDKGetPartnerConfigData$outboundSchema),
});

export function sdkGetPartnerConfigResponseToJSON(
  sdkGetPartnerConfigResponse: SDKGetPartnerConfigResponse,
): string {
  return JSON.stringify(
    SDKGetPartnerConfigResponse$outboundSchema.parse(
      sdkGetPartnerConfigResponse,
    ),
  );
}
export function sdkGetPartnerConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKGetPartnerConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKGetPartnerConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKGetPartnerConfigResponse' from JSON`,
  );
}
