/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKCreateSessionSecurity = {
  apiKeyAuth: string;
};

export type SDKCreateSessionRequest = {
  /**
   * Your internal user identifier for correlation
   */
  partnerUserId?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/**
 * Resolved from the credential: API token environment, or site key pk_test_ → development / pk_live_ → production.
 */
export const SDKCreateSessionEnvironment = {
  Development: "development",
  Production: "production",
} as const;
/**
 * Resolved from the credential: API token environment, or site key pk_test_ → development / pk_live_ → production.
 */
export type SDKCreateSessionEnvironment = OpenEnum<
  typeof SDKCreateSessionEnvironment
>;

export type SDKCreateSessionOrganization = {
  id: string;
  /**
   * Resolved from the credential: API token environment, or site key pk_test_ → development / pk_live_ → production.
   */
  environment: SDKCreateSessionEnvironment;
};

export type SDKCreateSessionDataData = {
  /**
   * Canonical grant token (Bearer bss_*)
   */
  anchorGrantToken: string;
  anchorGrantExpiresAt: Date;
  anchorGrantExpiresInSeconds: number;
  /**
   * Legacy alias (backward compatibility)
   */
  sessionToken: string;
  expiresAt: Date;
  expiresInSeconds: number;
  organization: SDKCreateSessionOrganization;
};

export type SDKCreateSessionData = {
  data?: SDKCreateSessionDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Anchor grant window created. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: 401 (bad or missing credential), 403 (origin not allowed for the site key).
 */
export type SDKCreateSessionResponse = {
  data: SDKCreateSessionData;
};

/** @internal */
export const SDKCreateSessionSecurity$inboundSchema: z.ZodType<
  SDKCreateSessionSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKCreateSessionSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKCreateSessionSecurity$outboundSchema: z.ZodType<
  SDKCreateSessionSecurity$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkCreateSessionSecurityToJSON(
  sdkCreateSessionSecurity: SDKCreateSessionSecurity,
): string {
  return JSON.stringify(
    SDKCreateSessionSecurity$outboundSchema.parse(sdkCreateSessionSecurity),
  );
}
export function sdkCreateSessionSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionSecurity' from JSON`,
  );
}

/** @internal */
export const SDKCreateSessionRequest$inboundSchema: z.ZodType<
  SDKCreateSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  partner_user_id: types.optional(types.string()),
  metadata: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "partner_user_id": "partnerUserId",
  });
});
/** @internal */
export type SDKCreateSessionRequest$Outbound = {
  partner_user_id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDKCreateSessionRequest$outboundSchema: z.ZodType<
  SDKCreateSessionRequest$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionRequest
> = z.object({
  partnerUserId: z.string().optional(),
  metadata: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    partnerUserId: "partner_user_id",
  });
});

export function sdkCreateSessionRequestToJSON(
  sdkCreateSessionRequest: SDKCreateSessionRequest,
): string {
  return JSON.stringify(
    SDKCreateSessionRequest$outboundSchema.parse(sdkCreateSessionRequest),
  );
}
export function sdkCreateSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionRequest' from JSON`,
  );
}

/** @internal */
export const SDKCreateSessionEnvironment$inboundSchema: z.ZodType<
  SDKCreateSessionEnvironment,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SDKCreateSessionEnvironment);
/** @internal */
export const SDKCreateSessionEnvironment$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SDKCreateSessionEnvironment
> = openEnums.outboundSchema(SDKCreateSessionEnvironment);

/** @internal */
export const SDKCreateSessionOrganization$inboundSchema: z.ZodType<
  SDKCreateSessionOrganization,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: types.string(),
  environment: SDKCreateSessionEnvironment$inboundSchema,
});
/** @internal */
export type SDKCreateSessionOrganization$Outbound = {
  id: string;
  environment: string;
};

/** @internal */
export const SDKCreateSessionOrganization$outboundSchema: z.ZodType<
  SDKCreateSessionOrganization$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionOrganization
> = z.object({
  id: z.string(),
  environment: SDKCreateSessionEnvironment$outboundSchema,
});

export function sdkCreateSessionOrganizationToJSON(
  sdkCreateSessionOrganization: SDKCreateSessionOrganization,
): string {
  return JSON.stringify(
    SDKCreateSessionOrganization$outboundSchema.parse(
      sdkCreateSessionOrganization,
    ),
  );
}
export function sdkCreateSessionOrganizationFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionOrganization, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionOrganization$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionOrganization' from JSON`,
  );
}

/** @internal */
export const SDKCreateSessionDataData$inboundSchema: z.ZodType<
  SDKCreateSessionDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  anchor_grant_token: types.string(),
  anchor_grant_expires_at: types.date(),
  anchor_grant_expires_in_seconds: types.number(),
  session_token: types.string(),
  expires_at: types.date(),
  expires_in_seconds: types.number(),
  organization: z.lazy(() => SDKCreateSessionOrganization$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "anchor_grant_token": "anchorGrantToken",
    "anchor_grant_expires_at": "anchorGrantExpiresAt",
    "anchor_grant_expires_in_seconds": "anchorGrantExpiresInSeconds",
    "session_token": "sessionToken",
    "expires_at": "expiresAt",
    "expires_in_seconds": "expiresInSeconds",
  });
});
/** @internal */
export type SDKCreateSessionDataData$Outbound = {
  anchor_grant_token: string;
  anchor_grant_expires_at: string;
  anchor_grant_expires_in_seconds: number;
  session_token: string;
  expires_at: string;
  expires_in_seconds: number;
  organization: SDKCreateSessionOrganization$Outbound;
};

/** @internal */
export const SDKCreateSessionDataData$outboundSchema: z.ZodType<
  SDKCreateSessionDataData$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionDataData
> = z.object({
  anchorGrantToken: z.string(),
  anchorGrantExpiresAt: z.date().transform(v => v.toISOString()),
  anchorGrantExpiresInSeconds: z.number().int(),
  sessionToken: z.string(),
  expiresAt: z.date().transform(v => v.toISOString()),
  expiresInSeconds: z.number().int(),
  organization: z.lazy(() => SDKCreateSessionOrganization$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    anchorGrantToken: "anchor_grant_token",
    anchorGrantExpiresAt: "anchor_grant_expires_at",
    anchorGrantExpiresInSeconds: "anchor_grant_expires_in_seconds",
    sessionToken: "session_token",
    expiresAt: "expires_at",
    expiresInSeconds: "expires_in_seconds",
  });
});

export function sdkCreateSessionDataDataToJSON(
  sdkCreateSessionDataData: SDKCreateSessionDataData,
): string {
  return JSON.stringify(
    SDKCreateSessionDataData$outboundSchema.parse(sdkCreateSessionDataData),
  );
}
export function sdkCreateSessionDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionDataData' from JSON`,
  );
}

/** @internal */
export const SDKCreateSessionData$inboundSchema: z.ZodType<
  SDKCreateSessionData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SDKCreateSessionDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKCreateSessionData$Outbound = {
  data?: SDKCreateSessionDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKCreateSessionData$outboundSchema: z.ZodType<
  SDKCreateSessionData$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionData
> = z.object({
  data: z.lazy(() => SDKCreateSessionDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkCreateSessionDataToJSON(
  sdkCreateSessionData: SDKCreateSessionData,
): string {
  return JSON.stringify(
    SDKCreateSessionData$outboundSchema.parse(sdkCreateSessionData),
  );
}
export function sdkCreateSessionDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionData' from JSON`,
  );
}

/** @internal */
export const SDKCreateSessionResponse$inboundSchema: z.ZodType<
  SDKCreateSessionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKCreateSessionData$inboundSchema),
});
/** @internal */
export type SDKCreateSessionResponse$Outbound = {
  data: SDKCreateSessionData$Outbound;
};

/** @internal */
export const SDKCreateSessionResponse$outboundSchema: z.ZodType<
  SDKCreateSessionResponse$Outbound,
  z.ZodTypeDef,
  SDKCreateSessionResponse
> = z.object({
  data: z.lazy(() => SDKCreateSessionData$outboundSchema),
});

export function sdkCreateSessionResponseToJSON(
  sdkCreateSessionResponse: SDKCreateSessionResponse,
): string {
  return JSON.stringify(
    SDKCreateSessionResponse$outboundSchema.parse(sdkCreateSessionResponse),
  );
}
export function sdkCreateSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKCreateSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKCreateSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKCreateSessionResponse' from JSON`,
  );
}
