/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKVerifyTokenSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

export type SDKVerifyTokenRequest = {
  /**
   * JWT verification receipt
   */
  token: string;
};

export type Claims = {
  requestId?: string | undefined;
  verified?: boolean | undefined;
  organizationId?: string | undefined;
  timestamp?: string | undefined;
  nonce?: string | undefined;
  issuedAt?: number | undefined;
  expiresAt?: number | undefined;
};

export type SDKVerifyTokenDataData = {
  valid: boolean;
  /**
   * Present when valid is false.
   */
  reason?: string | undefined;
  /**
   * Present when the token was valid but has expired.
   */
  expiredAt?: Date | null | undefined;
  claims?: Claims | null | undefined;
};

export type SDKVerifyTokenData = {
  data?: SDKVerifyTokenDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Validation result. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: none — an invalid token is a normal result with valid=false.
 */
export type SDKVerifyTokenResponse = {
  data: SDKVerifyTokenData;
};

/** @internal */
export const SDKVerifyTokenSecurity$inboundSchema: z.ZodType<
  SDKVerifyTokenSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
});
/** @internal */
export type SDKVerifyTokenSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

/** @internal */
export const SDKVerifyTokenSecurity$outboundSchema: z.ZodType<
  SDKVerifyTokenSecurity$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
});

export function sdkVerifyTokenSecurityToJSON(
  sdkVerifyTokenSecurity: SDKVerifyTokenSecurity,
): string {
  return JSON.stringify(
    SDKVerifyTokenSecurity$outboundSchema.parse(sdkVerifyTokenSecurity),
  );
}
export function sdkVerifyTokenSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenSecurity' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenRequest$inboundSchema: z.ZodType<
  SDKVerifyTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: types.string(),
});
/** @internal */
export type SDKVerifyTokenRequest$Outbound = {
  token: string;
};

/** @internal */
export const SDKVerifyTokenRequest$outboundSchema: z.ZodType<
  SDKVerifyTokenRequest$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenRequest
> = z.object({
  token: z.string(),
});

export function sdkVerifyTokenRequestToJSON(
  sdkVerifyTokenRequest: SDKVerifyTokenRequest,
): string {
  return JSON.stringify(
    SDKVerifyTokenRequest$outboundSchema.parse(sdkVerifyTokenRequest),
  );
}
export function sdkVerifyTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenRequest' from JSON`,
  );
}

/** @internal */
export const Claims$inboundSchema: z.ZodType<Claims, z.ZodTypeDef, unknown> = z
  .object({
    request_id: types.optional(types.string()),
    verified: types.optional(types.boolean()),
    organization_id: types.optional(types.string()),
    timestamp: types.optional(types.string()),
    nonce: types.optional(types.string()),
    issued_at: types.optional(types.number()),
    expires_at: types.optional(types.number()),
  }).transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "organization_id": "organizationId",
      "issued_at": "issuedAt",
      "expires_at": "expiresAt",
    });
  });
/** @internal */
export type Claims$Outbound = {
  request_id?: string | undefined;
  verified?: boolean | undefined;
  organization_id?: string | undefined;
  timestamp?: string | undefined;
  nonce?: string | undefined;
  issued_at?: number | undefined;
  expires_at?: number | undefined;
};

/** @internal */
export const Claims$outboundSchema: z.ZodType<
  Claims$Outbound,
  z.ZodTypeDef,
  Claims
> = z.object({
  requestId: z.string().optional(),
  verified: z.boolean().optional(),
  organizationId: z.string().optional(),
  timestamp: z.string().optional(),
  nonce: z.string().optional(),
  issuedAt: z.number().optional(),
  expiresAt: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    organizationId: "organization_id",
    issuedAt: "issued_at",
    expiresAt: "expires_at",
  });
});

export function claimsToJSON(claims: Claims): string {
  return JSON.stringify(Claims$outboundSchema.parse(claims));
}
export function claimsFromJSON(
  jsonString: string,
): SafeParseResult<Claims, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Claims$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Claims' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenDataData$inboundSchema: z.ZodType<
  SDKVerifyTokenDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: types.boolean(),
  reason: types.optional(types.string()),
  expired_at: z.nullable(types.date()).optional(),
  claims: z.nullable(z.lazy(() => Claims$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "expired_at": "expiredAt",
  });
});
/** @internal */
export type SDKVerifyTokenDataData$Outbound = {
  valid: boolean;
  reason?: string | undefined;
  expired_at?: string | null | undefined;
  claims?: Claims$Outbound | null | undefined;
};

/** @internal */
export const SDKVerifyTokenDataData$outboundSchema: z.ZodType<
  SDKVerifyTokenDataData$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenDataData
> = z.object({
  valid: z.boolean(),
  reason: z.string().optional(),
  expiredAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  claims: z.nullable(z.lazy(() => Claims$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    expiredAt: "expired_at",
  });
});

export function sdkVerifyTokenDataDataToJSON(
  sdkVerifyTokenDataData: SDKVerifyTokenDataData,
): string {
  return JSON.stringify(
    SDKVerifyTokenDataData$outboundSchema.parse(sdkVerifyTokenDataData),
  );
}
export function sdkVerifyTokenDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenDataData' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenData$inboundSchema: z.ZodType<
  SDKVerifyTokenData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SDKVerifyTokenDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKVerifyTokenData$Outbound = {
  data?: SDKVerifyTokenDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKVerifyTokenData$outboundSchema: z.ZodType<
  SDKVerifyTokenData$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenData
> = z.object({
  data: z.lazy(() => SDKVerifyTokenDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkVerifyTokenDataToJSON(
  sdkVerifyTokenData: SDKVerifyTokenData,
): string {
  return JSON.stringify(
    SDKVerifyTokenData$outboundSchema.parse(sdkVerifyTokenData),
  );
}
export function sdkVerifyTokenDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenData' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenResponse$inboundSchema: z.ZodType<
  SDKVerifyTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKVerifyTokenData$inboundSchema),
});
/** @internal */
export type SDKVerifyTokenResponse$Outbound = {
  data: SDKVerifyTokenData$Outbound;
};

/** @internal */
export const SDKVerifyTokenResponse$outboundSchema: z.ZodType<
  SDKVerifyTokenResponse$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenResponse
> = z.object({
  data: z.lazy(() => SDKVerifyTokenData$outboundSchema),
});

export function sdkVerifyTokenResponseToJSON(
  sdkVerifyTokenResponse: SDKVerifyTokenResponse,
): string {
  return JSON.stringify(
    SDKVerifyTokenResponse$outboundSchema.parse(sdkVerifyTokenResponse),
  );
}
export function sdkVerifyTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenResponse' from JSON`,
  );
}
