/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKVerifyTokenSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
};

export type SDKVerifyTokenRequest = {
  /**
   * JWT verification receipt
   */
  token: string;
  /**
   * Optional Signal Pixel token for combined confidence
   */
  signalToken?: string | undefined;
};

export const SDKVerifyTokenAuthMode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
export type SDKVerifyTokenAuthMode = OpenEnum<typeof SDKVerifyTokenAuthMode>;

export type Claims = {
  requestId?: string | undefined;
  verified?: boolean | undefined;
  botshieldUserId?: string | undefined;
  organizationId?: string | undefined;
  partnerUserId?: string | undefined;
  authMode?: SDKVerifyTokenAuthMode | undefined;
  userEmail?: string | undefined;
  timestamp?: string | undefined;
  issuedAt?: number | undefined;
  expiresAt?: number | undefined;
};

export type Turnstile = {
  success?: boolean | undefined;
};

export type Passkey = {
  verified?: boolean | undefined;
};

export type Signals = {
  /**
   * Signal Pixel score (0-100)
   */
  botshieldScore?: number | undefined;
  turnstile?: Turnstile | undefined;
  passkey?: Passkey | undefined;
};

/**
 * Validation result
 */
export type SDKVerifyTokenResponse = {
  valid?: boolean | undefined;
  reason?: string | undefined;
  /**
   * Combined confidence (passkey + signals + integrations)
   */
  confidence?: number | undefined;
  claims?: Claims | undefined;
  signals?: Signals | undefined;
};

/** @internal */
export const SDKVerifyTokenSecurity$inboundSchema: z.ZodType<
  SDKVerifyTokenSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
  apiKeyAuth3: types.optional(types.string()),
  apiKeyAuth4: types.optional(types.string()),
  apiKeyAuth5: types.optional(types.string()),
  apiKeyAuth6: types.optional(types.string()),
  apiKeyAuth7: types.optional(types.string()),
  apiKeyAuth8: types.optional(types.string()),
  apiKeyAuth9: types.optional(types.string()),
  apiKeyAuth10: types.optional(types.string()),
  apiKeyAuth11: types.optional(types.string()),
  apiKeyAuth12: types.optional(types.string()),
  apiKeyAuth13: types.optional(types.string()),
  apiKeyAuth14: types.optional(types.string()),
  apiKeyAuth15: types.optional(types.string()),
  apiKeyAuth16: types.optional(types.string()),
  apiKeyAuth17: types.optional(types.string()),
  apiKeyAuth18: types.optional(types.string()),
  apiKeyAuth19: types.optional(types.string()),
  apiKeyAuth20: types.optional(types.string()),
  apiKeyAuth21: types.optional(types.string()),
  apiKeyAuth22: types.optional(types.string()),
  apiKeyAuth23: types.optional(types.string()),
  apiKeyAuth24: types.optional(types.string()),
  apiKeyAuth25: types.optional(types.string()),
  apiKeyAuth26: types.optional(types.string()),
  apiKeyAuth27: types.optional(types.string()),
  apiKeyAuth28: types.optional(types.string()),
});
/** @internal */
export type SDKVerifyTokenSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
};

/** @internal */
export const SDKVerifyTokenSecurity$outboundSchema: z.ZodType<
  SDKVerifyTokenSecurity$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
  apiKeyAuth3: z.string().optional(),
  apiKeyAuth4: z.string().optional(),
  apiKeyAuth5: z.string().optional(),
  apiKeyAuth6: z.string().optional(),
  apiKeyAuth7: z.string().optional(),
  apiKeyAuth8: z.string().optional(),
  apiKeyAuth9: z.string().optional(),
  apiKeyAuth10: z.string().optional(),
  apiKeyAuth11: z.string().optional(),
  apiKeyAuth12: z.string().optional(),
  apiKeyAuth13: z.string().optional(),
  apiKeyAuth14: z.string().optional(),
  apiKeyAuth15: z.string().optional(),
  apiKeyAuth16: z.string().optional(),
  apiKeyAuth17: z.string().optional(),
  apiKeyAuth18: z.string().optional(),
  apiKeyAuth19: z.string().optional(),
  apiKeyAuth20: z.string().optional(),
  apiKeyAuth21: z.string().optional(),
  apiKeyAuth22: z.string().optional(),
  apiKeyAuth23: z.string().optional(),
  apiKeyAuth24: z.string().optional(),
  apiKeyAuth25: z.string().optional(),
  apiKeyAuth26: z.string().optional(),
  apiKeyAuth27: z.string().optional(),
  apiKeyAuth28: z.string().optional(),
});

export function sdkVerifyTokenSecurityToJSON(
  sdkVerifyTokenSecurity: SDKVerifyTokenSecurity,
): string {
  return JSON.stringify(
    SDKVerifyTokenSecurity$outboundSchema.parse(sdkVerifyTokenSecurity),
  );
}
export function sdkVerifyTokenSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenSecurity' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenRequest$inboundSchema: z.ZodType<
  SDKVerifyTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  token: types.string(),
  signal_token: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "signal_token": "signalToken",
  });
});
/** @internal */
export type SDKVerifyTokenRequest$Outbound = {
  token: string;
  signal_token?: string | undefined;
};

/** @internal */
export const SDKVerifyTokenRequest$outboundSchema: z.ZodType<
  SDKVerifyTokenRequest$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenRequest
> = z.object({
  token: z.string(),
  signalToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signalToken: "signal_token",
  });
});

export function sdkVerifyTokenRequestToJSON(
  sdkVerifyTokenRequest: SDKVerifyTokenRequest,
): string {
  return JSON.stringify(
    SDKVerifyTokenRequest$outboundSchema.parse(sdkVerifyTokenRequest),
  );
}
export function sdkVerifyTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenRequest' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenAuthMode$inboundSchema: z.ZodType<
  SDKVerifyTokenAuthMode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(SDKVerifyTokenAuthMode);
/** @internal */
export const SDKVerifyTokenAuthMode$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  SDKVerifyTokenAuthMode
> = openEnums.outboundSchema(SDKVerifyTokenAuthMode);

/** @internal */
export const Claims$inboundSchema: z.ZodType<Claims, z.ZodTypeDef, unknown> = z
  .object({
    request_id: types.optional(types.string()),
    verified: types.optional(types.boolean()),
    botshield_user_id: types.optional(types.string()),
    organization_id: types.optional(types.string()),
    partner_user_id: types.optional(types.string()),
    auth_mode: types.optional(SDKVerifyTokenAuthMode$inboundSchema),
    user_email: types.optional(types.string()),
    timestamp: types.optional(types.string()),
    issued_at: types.optional(types.number()),
    expires_at: types.optional(types.number()),
  }).transform((v) => {
    return remap$(v, {
      "request_id": "requestId",
      "botshield_user_id": "botshieldUserId",
      "organization_id": "organizationId",
      "partner_user_id": "partnerUserId",
      "auth_mode": "authMode",
      "user_email": "userEmail",
      "issued_at": "issuedAt",
      "expires_at": "expiresAt",
    });
  });
/** @internal */
export type Claims$Outbound = {
  request_id?: string | undefined;
  verified?: boolean | undefined;
  botshield_user_id?: string | undefined;
  organization_id?: string | undefined;
  partner_user_id?: string | undefined;
  auth_mode?: string | undefined;
  user_email?: string | undefined;
  timestamp?: string | undefined;
  issued_at?: number | undefined;
  expires_at?: number | undefined;
};

/** @internal */
export const Claims$outboundSchema: z.ZodType<
  Claims$Outbound,
  z.ZodTypeDef,
  Claims
> = z.object({
  requestId: z.string().optional(),
  verified: z.boolean().optional(),
  botshieldUserId: z.string().optional(),
  organizationId: z.string().optional(),
  partnerUserId: z.string().optional(),
  authMode: SDKVerifyTokenAuthMode$outboundSchema.optional(),
  userEmail: z.string().optional(),
  timestamp: z.string().optional(),
  issuedAt: z.number().optional(),
  expiresAt: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    botshieldUserId: "botshield_user_id",
    organizationId: "organization_id",
    partnerUserId: "partner_user_id",
    authMode: "auth_mode",
    userEmail: "user_email",
    issuedAt: "issued_at",
    expiresAt: "expires_at",
  });
});

export function claimsToJSON(claims: Claims): string {
  return JSON.stringify(Claims$outboundSchema.parse(claims));
}
export function claimsFromJSON(
  jsonString: string,
): SafeParseResult<Claims, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Claims$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Claims' from JSON`,
  );
}

/** @internal */
export const Turnstile$inboundSchema: z.ZodType<
  Turnstile,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});
/** @internal */
export type Turnstile$Outbound = {
  success?: boolean | undefined;
};

/** @internal */
export const Turnstile$outboundSchema: z.ZodType<
  Turnstile$Outbound,
  z.ZodTypeDef,
  Turnstile
> = z.object({
  success: z.boolean().optional(),
});

export function turnstileToJSON(turnstile: Turnstile): string {
  return JSON.stringify(Turnstile$outboundSchema.parse(turnstile));
}
export function turnstileFromJSON(
  jsonString: string,
): SafeParseResult<Turnstile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Turnstile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Turnstile' from JSON`,
  );
}

/** @internal */
export const Passkey$inboundSchema: z.ZodType<Passkey, z.ZodTypeDef, unknown> =
  z.object({
    verified: types.optional(types.boolean()),
  });
/** @internal */
export type Passkey$Outbound = {
  verified?: boolean | undefined;
};

/** @internal */
export const Passkey$outboundSchema: z.ZodType<
  Passkey$Outbound,
  z.ZodTypeDef,
  Passkey
> = z.object({
  verified: z.boolean().optional(),
});

export function passkeyToJSON(passkey: Passkey): string {
  return JSON.stringify(Passkey$outboundSchema.parse(passkey));
}
export function passkeyFromJSON(
  jsonString: string,
): SafeParseResult<Passkey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Passkey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Passkey' from JSON`,
  );
}

/** @internal */
export const Signals$inboundSchema: z.ZodType<Signals, z.ZodTypeDef, unknown> =
  z.object({
    botshield_score: types.optional(types.number()),
    turnstile: types.optional(z.lazy(() => Turnstile$inboundSchema)),
    passkey: types.optional(z.lazy(() => Passkey$inboundSchema)),
  }).transform((v) => {
    return remap$(v, {
      "botshield_score": "botshieldScore",
    });
  });
/** @internal */
export type Signals$Outbound = {
  botshield_score?: number | undefined;
  turnstile?: Turnstile$Outbound | undefined;
  passkey?: Passkey$Outbound | undefined;
};

/** @internal */
export const Signals$outboundSchema: z.ZodType<
  Signals$Outbound,
  z.ZodTypeDef,
  Signals
> = z.object({
  botshieldScore: z.number().int().optional(),
  turnstile: z.lazy(() => Turnstile$outboundSchema).optional(),
  passkey: z.lazy(() => Passkey$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    botshieldScore: "botshield_score",
  });
});

export function signalsToJSON(signals: Signals): string {
  return JSON.stringify(Signals$outboundSchema.parse(signals));
}
export function signalsFromJSON(
  jsonString: string,
): SafeParseResult<Signals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Signals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Signals' from JSON`,
  );
}

/** @internal */
export const SDKVerifyTokenResponse$inboundSchema: z.ZodType<
  SDKVerifyTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: types.optional(types.boolean()),
  reason: types.optional(types.string()),
  confidence: types.optional(types.number()),
  claims: types.optional(z.lazy(() => Claims$inboundSchema)),
  signals: types.optional(z.lazy(() => Signals$inboundSchema)),
});
/** @internal */
export type SDKVerifyTokenResponse$Outbound = {
  valid?: boolean | undefined;
  reason?: string | undefined;
  confidence?: number | undefined;
  claims?: Claims$Outbound | undefined;
  signals?: Signals$Outbound | undefined;
};

/** @internal */
export const SDKVerifyTokenResponse$outboundSchema: z.ZodType<
  SDKVerifyTokenResponse$Outbound,
  z.ZodTypeDef,
  SDKVerifyTokenResponse
> = z.object({
  valid: z.boolean().optional(),
  reason: z.string().optional(),
  confidence: z.number().optional(),
  claims: z.lazy(() => Claims$outboundSchema).optional(),
  signals: z.lazy(() => Signals$outboundSchema).optional(),
});

export function sdkVerifyTokenResponseToJSON(
  sdkVerifyTokenResponse: SDKVerifyTokenResponse,
): string {
  return JSON.stringify(
    SDKVerifyTokenResponse$outboundSchema.parse(sdkVerifyTokenResponse),
  );
}
export function sdkVerifyTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKVerifyTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKVerifyTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKVerifyTokenResponse' from JSON`,
  );
}
