/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKStoreSignalSecurity = {
  apiKeyAuth: string;
};

export type SDKStoreSignalRequest = {
  siteKey: string;
  score: number;
  edgeScore?: number | undefined;
  clientScore?: number | undefined;
  fpHash?: string | undefined;
  ipHash?: string | undefined;
  uaHash?: string | undefined;
  country?: string | undefined;
  signals?: { [k: string]: any } | undefined;
};

/**
 * Signal stored
 */
export type SDKStoreSignalResponse = {
  /**
   * Opaque tamper-proof token (bs_sig_...)
   */
  signalToken?: string | undefined;
  expiresAt?: Date | undefined;
};

/** @internal */
export const SDKStoreSignalSecurity$inboundSchema: z.ZodType<
  SDKStoreSignalSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKStoreSignalSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKStoreSignalSecurity$outboundSchema: z.ZodType<
  SDKStoreSignalSecurity$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkStoreSignalSecurityToJSON(
  sdkStoreSignalSecurity: SDKStoreSignalSecurity,
): string {
  return JSON.stringify(
    SDKStoreSignalSecurity$outboundSchema.parse(sdkStoreSignalSecurity),
  );
}
export function sdkStoreSignalSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalSecurity' from JSON`,
  );
}

/** @internal */
export const SDKStoreSignalRequest$inboundSchema: z.ZodType<
  SDKStoreSignalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  site_key: types.string(),
  score: types.number(),
  edge_score: types.optional(types.number()),
  client_score: types.optional(types.number()),
  fp_hash: types.optional(types.string()),
  ip_hash: types.optional(types.string()),
  ua_hash: types.optional(types.string()),
  country: types.optional(types.string()),
  signals: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "site_key": "siteKey",
    "edge_score": "edgeScore",
    "client_score": "clientScore",
    "fp_hash": "fpHash",
    "ip_hash": "ipHash",
    "ua_hash": "uaHash",
  });
});
/** @internal */
export type SDKStoreSignalRequest$Outbound = {
  site_key: string;
  score: number;
  edge_score?: number | undefined;
  client_score?: number | undefined;
  fp_hash?: string | undefined;
  ip_hash?: string | undefined;
  ua_hash?: string | undefined;
  country?: string | undefined;
  signals?: { [k: string]: any } | undefined;
};

/** @internal */
export const SDKStoreSignalRequest$outboundSchema: z.ZodType<
  SDKStoreSignalRequest$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalRequest
> = z.object({
  siteKey: z.string(),
  score: z.number().int(),
  edgeScore: z.number().int().optional(),
  clientScore: z.number().int().optional(),
  fpHash: z.string().optional(),
  ipHash: z.string().optional(),
  uaHash: z.string().optional(),
  country: z.string().optional(),
  signals: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    siteKey: "site_key",
    edgeScore: "edge_score",
    clientScore: "client_score",
    fpHash: "fp_hash",
    ipHash: "ip_hash",
    uaHash: "ua_hash",
  });
});

export function sdkStoreSignalRequestToJSON(
  sdkStoreSignalRequest: SDKStoreSignalRequest,
): string {
  return JSON.stringify(
    SDKStoreSignalRequest$outboundSchema.parse(sdkStoreSignalRequest),
  );
}
export function sdkStoreSignalRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalRequest' from JSON`,
  );
}

/** @internal */
export const SDKStoreSignalResponse$inboundSchema: z.ZodType<
  SDKStoreSignalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  signal_token: types.optional(types.string()),
  expires_at: types.optional(types.date()),
}).transform((v) => {
  return remap$(v, {
    "signal_token": "signalToken",
    "expires_at": "expiresAt",
  });
});
/** @internal */
export type SDKStoreSignalResponse$Outbound = {
  signal_token?: string | undefined;
  expires_at?: string | undefined;
};

/** @internal */
export const SDKStoreSignalResponse$outboundSchema: z.ZodType<
  SDKStoreSignalResponse$Outbound,
  z.ZodTypeDef,
  SDKStoreSignalResponse
> = z.object({
  signalToken: z.string().optional(),
  expiresAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    signalToken: "signal_token",
    expiresAt: "expires_at",
  });
});

export function sdkStoreSignalResponseToJSON(
  sdkStoreSignalResponse: SDKStoreSignalResponse,
): string {
  return JSON.stringify(
    SDKStoreSignalResponse$outboundSchema.parse(sdkStoreSignalResponse),
  );
}
export function sdkStoreSignalResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKStoreSignalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKStoreSignalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKStoreSignalResponse' from JSON`,
  );
}
