/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type SDKValidateSignalRequest = {
  signalToken: string;
  verificationEventId?: string | undefined;
};

/**
 * Present when valid is false.
 */
export const Reason = {
  InvalidSignalToken: "invalid_signal_token",
  SignalTokenExpired: "signal_token_expired",
  SignalTokenAlreadyUsed: "signal_token_already_used",
} as const;
/**
 * Present when valid is false.
 */
export type Reason = OpenEnum<typeof Reason>;

export type SDKValidateSignalDataData = {
  valid: boolean;
  /**
   * Present when valid is false.
   */
  reason?: Reason | undefined;
  score?: number | undefined;
  edgeScore?: number | undefined;
  clientScore?: number | undefined;
  country?: string | undefined;
  siteKey?: string | undefined;
  createdAt?: Date | undefined;
};

export type SDKValidateSignalData = {
  data?: SDKValidateSignalDataData | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Validation result. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: none — an invalid token is a normal result with valid=false.
 */
export type SDKValidateSignalResponse = {
  data: SDKValidateSignalData;
};

/** @internal */
export const SDKValidateSignalRequest$inboundSchema: z.ZodType<
  SDKValidateSignalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  signal_token: types.string(),
  verification_event_id: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "signal_token": "signalToken",
    "verification_event_id": "verificationEventId",
  });
});
/** @internal */
export type SDKValidateSignalRequest$Outbound = {
  signal_token: string;
  verification_event_id?: string | undefined;
};

/** @internal */
export const SDKValidateSignalRequest$outboundSchema: z.ZodType<
  SDKValidateSignalRequest$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalRequest
> = z.object({
  signalToken: z.string(),
  verificationEventId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signalToken: "signal_token",
    verificationEventId: "verification_event_id",
  });
});

export function sdkValidateSignalRequestToJSON(
  sdkValidateSignalRequest: SDKValidateSignalRequest,
): string {
  return JSON.stringify(
    SDKValidateSignalRequest$outboundSchema.parse(sdkValidateSignalRequest),
  );
}
export function sdkValidateSignalRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalRequest' from JSON`,
  );
}

/** @internal */
export const Reason$inboundSchema: z.ZodType<Reason, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(Reason);
/** @internal */
export const Reason$outboundSchema: z.ZodType<string, z.ZodTypeDef, Reason> =
  openEnums.outboundSchema(Reason);

/** @internal */
export const SDKValidateSignalDataData$inboundSchema: z.ZodType<
  SDKValidateSignalDataData,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: types.boolean(),
  reason: types.optional(Reason$inboundSchema),
  score: types.optional(types.number()),
  edge_score: types.optional(types.number()),
  client_score: types.optional(types.number()),
  country: types.optional(types.string()),
  site_key: types.optional(types.string()),
  created_at: types.optional(types.date()),
}).transform((v) => {
  return remap$(v, {
    "edge_score": "edgeScore",
    "client_score": "clientScore",
    "site_key": "siteKey",
    "created_at": "createdAt",
  });
});
/** @internal */
export type SDKValidateSignalDataData$Outbound = {
  valid: boolean;
  reason?: string | undefined;
  score?: number | undefined;
  edge_score?: number | undefined;
  client_score?: number | undefined;
  country?: string | undefined;
  site_key?: string | undefined;
  created_at?: string | undefined;
};

/** @internal */
export const SDKValidateSignalDataData$outboundSchema: z.ZodType<
  SDKValidateSignalDataData$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalDataData
> = z.object({
  valid: z.boolean(),
  reason: Reason$outboundSchema.optional(),
  score: z.number().int().optional(),
  edgeScore: z.number().int().optional(),
  clientScore: z.number().int().optional(),
  country: z.string().optional(),
  siteKey: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    edgeScore: "edge_score",
    clientScore: "client_score",
    siteKey: "site_key",
    createdAt: "created_at",
  });
});

export function sdkValidateSignalDataDataToJSON(
  sdkValidateSignalDataData: SDKValidateSignalDataData,
): string {
  return JSON.stringify(
    SDKValidateSignalDataData$outboundSchema.parse(sdkValidateSignalDataData),
  );
}
export function sdkValidateSignalDataDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalDataData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalDataData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalDataData' from JSON`,
  );
}

/** @internal */
export const SDKValidateSignalData$inboundSchema: z.ZodType<
  SDKValidateSignalData,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => SDKValidateSignalDataData$inboundSchema)),
  error: types.optional(models.ErrorBody$inboundSchema),
});
/** @internal */
export type SDKValidateSignalData$Outbound = {
  data?: SDKValidateSignalDataData$Outbound | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const SDKValidateSignalData$outboundSchema: z.ZodType<
  SDKValidateSignalData$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalData
> = z.object({
  data: z.lazy(() => SDKValidateSignalDataData$outboundSchema).optional(),
  error: models.ErrorBody$outboundSchema.optional(),
});

export function sdkValidateSignalDataToJSON(
  sdkValidateSignalData: SDKValidateSignalData,
): string {
  return JSON.stringify(
    SDKValidateSignalData$outboundSchema.parse(sdkValidateSignalData),
  );
}
export function sdkValidateSignalDataFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalData' from JSON`,
  );
}

/** @internal */
export const SDKValidateSignalResponse$inboundSchema: z.ZodType<
  SDKValidateSignalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => SDKValidateSignalData$inboundSchema),
});
/** @internal */
export type SDKValidateSignalResponse$Outbound = {
  data: SDKValidateSignalData$Outbound;
};

/** @internal */
export const SDKValidateSignalResponse$outboundSchema: z.ZodType<
  SDKValidateSignalResponse$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalResponse
> = z.object({
  data: z.lazy(() => SDKValidateSignalData$outboundSchema),
});

export function sdkValidateSignalResponseToJSON(
  sdkValidateSignalResponse: SDKValidateSignalResponse,
): string {
  return JSON.stringify(
    SDKValidateSignalResponse$outboundSchema.parse(sdkValidateSignalResponse),
  );
}
export function sdkValidateSignalResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalResponse' from JSON`,
  );
}
