/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SDKValidateSignalSecurity = {
  apiKeyAuth: string;
};

export type SDKValidateSignalRequest = {
  signalToken: string;
  verificationEventId?: string | undefined;
};

/**
 * Validation result
 */
export type SDKValidateSignalResponse = {
  valid?: boolean | undefined;
  score?: number | undefined;
  edgeScore?: number | undefined;
  clientScore?: number | undefined;
  fpHash?: string | undefined;
  country?: string | undefined;
  siteKey?: string | undefined;
  createdAt?: Date | undefined;
  reason?: string | undefined;
};

/** @internal */
export const SDKValidateSignalSecurity$inboundSchema: z.ZodType<
  SDKValidateSignalSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  ApiKeyAuth: types.string(),
}).transform((v) => {
  return remap$(v, {
    "ApiKeyAuth": "apiKeyAuth",
  });
});
/** @internal */
export type SDKValidateSignalSecurity$Outbound = {
  ApiKeyAuth: string;
};

/** @internal */
export const SDKValidateSignalSecurity$outboundSchema: z.ZodType<
  SDKValidateSignalSecurity$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalSecurity
> = z.object({
  apiKeyAuth: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiKeyAuth: "ApiKeyAuth",
  });
});

export function sdkValidateSignalSecurityToJSON(
  sdkValidateSignalSecurity: SDKValidateSignalSecurity,
): string {
  return JSON.stringify(
    SDKValidateSignalSecurity$outboundSchema.parse(sdkValidateSignalSecurity),
  );
}
export function sdkValidateSignalSecurityFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalSecurity' from JSON`,
  );
}

/** @internal */
export const SDKValidateSignalRequest$inboundSchema: z.ZodType<
  SDKValidateSignalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  signal_token: types.string(),
  verification_event_id: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "signal_token": "signalToken",
    "verification_event_id": "verificationEventId",
  });
});
/** @internal */
export type SDKValidateSignalRequest$Outbound = {
  signal_token: string;
  verification_event_id?: string | undefined;
};

/** @internal */
export const SDKValidateSignalRequest$outboundSchema: z.ZodType<
  SDKValidateSignalRequest$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalRequest
> = z.object({
  signalToken: z.string(),
  verificationEventId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    signalToken: "signal_token",
    verificationEventId: "verification_event_id",
  });
});

export function sdkValidateSignalRequestToJSON(
  sdkValidateSignalRequest: SDKValidateSignalRequest,
): string {
  return JSON.stringify(
    SDKValidateSignalRequest$outboundSchema.parse(sdkValidateSignalRequest),
  );
}
export function sdkValidateSignalRequestFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalRequest' from JSON`,
  );
}

/** @internal */
export const SDKValidateSignalResponse$inboundSchema: z.ZodType<
  SDKValidateSignalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: types.optional(types.boolean()),
  score: types.optional(types.number()),
  edge_score: types.optional(types.number()),
  client_score: types.optional(types.number()),
  fp_hash: types.optional(types.string()),
  country: types.optional(types.string()),
  site_key: types.optional(types.string()),
  created_at: types.optional(types.date()),
  reason: types.optional(types.string()),
}).transform((v) => {
  return remap$(v, {
    "edge_score": "edgeScore",
    "client_score": "clientScore",
    "fp_hash": "fpHash",
    "site_key": "siteKey",
    "created_at": "createdAt",
  });
});
/** @internal */
export type SDKValidateSignalResponse$Outbound = {
  valid?: boolean | undefined;
  score?: number | undefined;
  edge_score?: number | undefined;
  client_score?: number | undefined;
  fp_hash?: string | undefined;
  country?: string | undefined;
  site_key?: string | undefined;
  created_at?: string | undefined;
  reason?: string | undefined;
};

/** @internal */
export const SDKValidateSignalResponse$outboundSchema: z.ZodType<
  SDKValidateSignalResponse$Outbound,
  z.ZodTypeDef,
  SDKValidateSignalResponse
> = z.object({
  valid: z.boolean().optional(),
  score: z.number().int().optional(),
  edgeScore: z.number().int().optional(),
  clientScore: z.number().int().optional(),
  fpHash: z.string().optional(),
  country: z.string().optional(),
  siteKey: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  reason: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    edgeScore: "edge_score",
    clientScore: "client_score",
    fpHash: "fp_hash",
    siteKey: "site_key",
    createdAt: "created_at",
  });
});

export function sdkValidateSignalResponseToJSON(
  sdkValidateSignalResponse: SDKValidateSignalResponse,
): string {
  return JSON.stringify(
    SDKValidateSignalResponse$outboundSchema.parse(sdkValidateSignalResponse),
  );
}
export function sdkValidateSignalResponseFromJSON(
  jsonString: string,
): SafeParseResult<SDKValidateSignalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SDKValidateSignalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SDKValidateSignalResponse' from JSON`,
  );
}
