/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VerificationGetStatusSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
};

export type VerificationGetStatusRequest = {
  requestId: string;
};

export const VerificationGetStatusStatus = {
  Pending: "pending",
  Completed: "completed",
  Expired: "expired",
  Failed: "failed",
  NotFound: "not_found",
} as const;
export type VerificationGetStatusStatus = OpenEnum<
  typeof VerificationGetStatusStatus
>;

export const VerificationGetStatusSDKType = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type VerificationGetStatusSDKType = OpenEnum<
  typeof VerificationGetStatusSDKType
>;

export const VerificationGetStatusAuthMode = {
  LinkedAccount: "linked-account",
  Private: "private",
} as const;
export type VerificationGetStatusAuthMode = OpenEnum<
  typeof VerificationGetStatusAuthMode
>;

/**
 * Verification status
 */
export type VerificationGetStatusResponse = {
  found?: boolean | undefined;
  status?: VerificationGetStatusStatus | undefined;
  requestId?: string | undefined;
  organizationId?: string | undefined;
  partnerUserId?: string | undefined;
  userEmail?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
  verifiedAt?: Date | undefined;
  signedToken?: string | undefined;
  /**
   * Legacy alias
   */
  verificationToken?: string | undefined;
  errorMessage?: string | undefined;
  sdkType?: VerificationGetStatusSDKType | undefined;
  scope?: string | undefined;
  authMode?: VerificationGetStatusAuthMode | undefined;
  presenceAddress?: string | undefined;
  signalScore?: number | undefined;
  confidence?: number | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const VerificationGetStatusSecurity$inboundSchema: z.ZodType<
  VerificationGetStatusSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
  apiKeyAuth3: types.optional(types.string()),
  apiKeyAuth4: types.optional(types.string()),
  apiKeyAuth5: types.optional(types.string()),
  apiKeyAuth6: types.optional(types.string()),
  apiKeyAuth7: types.optional(types.string()),
  apiKeyAuth8: types.optional(types.string()),
  apiKeyAuth9: types.optional(types.string()),
  apiKeyAuth10: types.optional(types.string()),
  apiKeyAuth11: types.optional(types.string()),
  apiKeyAuth12: types.optional(types.string()),
  apiKeyAuth13: types.optional(types.string()),
  apiKeyAuth14: types.optional(types.string()),
  apiKeyAuth15: types.optional(types.string()),
  apiKeyAuth16: types.optional(types.string()),
  apiKeyAuth17: types.optional(types.string()),
  apiKeyAuth18: types.optional(types.string()),
  apiKeyAuth19: types.optional(types.string()),
  apiKeyAuth20: types.optional(types.string()),
  apiKeyAuth21: types.optional(types.string()),
  apiKeyAuth22: types.optional(types.string()),
  apiKeyAuth23: types.optional(types.string()),
  apiKeyAuth24: types.optional(types.string()),
  apiKeyAuth25: types.optional(types.string()),
  apiKeyAuth26: types.optional(types.string()),
  apiKeyAuth27: types.optional(types.string()),
  apiKeyAuth28: types.optional(types.string()),
  apiKeyAuth29: types.optional(types.string()),
  apiKeyAuth30: types.optional(types.string()),
  apiKeyAuth31: types.optional(types.string()),
});
/** @internal */
export type VerificationGetStatusSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
};

/** @internal */
export const VerificationGetStatusSecurity$outboundSchema: z.ZodType<
  VerificationGetStatusSecurity$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
  apiKeyAuth3: z.string().optional(),
  apiKeyAuth4: z.string().optional(),
  apiKeyAuth5: z.string().optional(),
  apiKeyAuth6: z.string().optional(),
  apiKeyAuth7: z.string().optional(),
  apiKeyAuth8: z.string().optional(),
  apiKeyAuth9: z.string().optional(),
  apiKeyAuth10: z.string().optional(),
  apiKeyAuth11: z.string().optional(),
  apiKeyAuth12: z.string().optional(),
  apiKeyAuth13: z.string().optional(),
  apiKeyAuth14: z.string().optional(),
  apiKeyAuth15: z.string().optional(),
  apiKeyAuth16: z.string().optional(),
  apiKeyAuth17: z.string().optional(),
  apiKeyAuth18: z.string().optional(),
  apiKeyAuth19: z.string().optional(),
  apiKeyAuth20: z.string().optional(),
  apiKeyAuth21: z.string().optional(),
  apiKeyAuth22: z.string().optional(),
  apiKeyAuth23: z.string().optional(),
  apiKeyAuth24: z.string().optional(),
  apiKeyAuth25: z.string().optional(),
  apiKeyAuth26: z.string().optional(),
  apiKeyAuth27: z.string().optional(),
  apiKeyAuth28: z.string().optional(),
  apiKeyAuth29: z.string().optional(),
  apiKeyAuth30: z.string().optional(),
  apiKeyAuth31: z.string().optional(),
});

export function verificationGetStatusSecurityToJSON(
  verificationGetStatusSecurity: VerificationGetStatusSecurity,
): string {
  return JSON.stringify(
    VerificationGetStatusSecurity$outboundSchema.parse(
      verificationGetStatusSecurity,
    ),
  );
}
export function verificationGetStatusSecurityFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusSecurity' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusRequest$inboundSchema: z.ZodType<
  VerificationGetStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type VerificationGetStatusRequest$Outbound = {
  request_id: string;
};

/** @internal */
export const VerificationGetStatusRequest$outboundSchema: z.ZodType<
  VerificationGetStatusRequest$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusRequest
> = z.object({
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function verificationGetStatusRequestToJSON(
  verificationGetStatusRequest: VerificationGetStatusRequest,
): string {
  return JSON.stringify(
    VerificationGetStatusRequest$outboundSchema.parse(
      verificationGetStatusRequest,
    ),
  );
}
export function verificationGetStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusRequest' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusStatus$inboundSchema: z.ZodType<
  VerificationGetStatusStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(VerificationGetStatusStatus);
/** @internal */
export const VerificationGetStatusStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  VerificationGetStatusStatus
> = openEnums.outboundSchema(VerificationGetStatusStatus);

/** @internal */
export const VerificationGetStatusSDKType$inboundSchema: z.ZodType<
  VerificationGetStatusSDKType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(VerificationGetStatusSDKType);
/** @internal */
export const VerificationGetStatusSDKType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  VerificationGetStatusSDKType
> = openEnums.outboundSchema(VerificationGetStatusSDKType);

/** @internal */
export const VerificationGetStatusAuthMode$inboundSchema: z.ZodType<
  VerificationGetStatusAuthMode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(VerificationGetStatusAuthMode);
/** @internal */
export const VerificationGetStatusAuthMode$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  VerificationGetStatusAuthMode
> = openEnums.outboundSchema(VerificationGetStatusAuthMode);

/** @internal */
export const VerificationGetStatusResponse$inboundSchema: z.ZodType<
  VerificationGetStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  found: types.optional(types.boolean()),
  status: types.optional(VerificationGetStatusStatus$inboundSchema),
  request_id: types.optional(types.string()),
  organization_id: types.optional(types.string()),
  partner_user_id: types.optional(types.string()),
  user_email: types.optional(types.string()),
  created_at: types.optional(types.date()),
  expires_at: types.optional(types.date()),
  verified_at: types.optional(types.date()),
  signed_token: types.optional(types.string()),
  verification_token: types.optional(types.string()),
  error_message: types.optional(types.string()),
  sdk_type: types.optional(VerificationGetStatusSDKType$inboundSchema),
  scope: types.optional(types.string()),
  auth_mode: types.optional(VerificationGetStatusAuthMode$inboundSchema),
  presence_address: types.optional(types.string()),
  signal_score: types.optional(types.number()),
  confidence: types.optional(types.number()),
  metadata: types.optional(z.record(z.any())),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "organization_id": "organizationId",
    "partner_user_id": "partnerUserId",
    "user_email": "userEmail",
    "created_at": "createdAt",
    "expires_at": "expiresAt",
    "verified_at": "verifiedAt",
    "signed_token": "signedToken",
    "verification_token": "verificationToken",
    "error_message": "errorMessage",
    "sdk_type": "sdkType",
    "auth_mode": "authMode",
    "presence_address": "presenceAddress",
    "signal_score": "signalScore",
  });
});
/** @internal */
export type VerificationGetStatusResponse$Outbound = {
  found?: boolean | undefined;
  status?: string | undefined;
  request_id?: string | undefined;
  organization_id?: string | undefined;
  partner_user_id?: string | undefined;
  user_email?: string | undefined;
  created_at?: string | undefined;
  expires_at?: string | undefined;
  verified_at?: string | undefined;
  signed_token?: string | undefined;
  verification_token?: string | undefined;
  error_message?: string | undefined;
  sdk_type?: string | undefined;
  scope?: string | undefined;
  auth_mode?: string | undefined;
  presence_address?: string | undefined;
  signal_score?: number | undefined;
  confidence?: number | undefined;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const VerificationGetStatusResponse$outboundSchema: z.ZodType<
  VerificationGetStatusResponse$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusResponse
> = z.object({
  found: z.boolean().optional(),
  status: VerificationGetStatusStatus$outboundSchema.optional(),
  requestId: z.string().optional(),
  organizationId: z.string().optional(),
  partnerUserId: z.string().optional(),
  userEmail: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  expiresAt: z.date().transform(v => v.toISOString()).optional(),
  verifiedAt: z.date().transform(v => v.toISOString()).optional(),
  signedToken: z.string().optional(),
  verificationToken: z.string().optional(),
  errorMessage: z.string().optional(),
  sdkType: VerificationGetStatusSDKType$outboundSchema.optional(),
  scope: z.string().optional(),
  authMode: VerificationGetStatusAuthMode$outboundSchema.optional(),
  presenceAddress: z.string().optional(),
  signalScore: z.number().int().optional(),
  confidence: z.number().optional(),
  metadata: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    organizationId: "organization_id",
    partnerUserId: "partner_user_id",
    userEmail: "user_email",
    createdAt: "created_at",
    expiresAt: "expires_at",
    verifiedAt: "verified_at",
    signedToken: "signed_token",
    verificationToken: "verification_token",
    errorMessage: "error_message",
    sdkType: "sdk_type",
    authMode: "auth_mode",
    presenceAddress: "presence_address",
    signalScore: "signal_score",
  });
});

export function verificationGetStatusResponseToJSON(
  verificationGetStatusResponse: VerificationGetStatusResponse,
): string {
  return JSON.stringify(
    VerificationGetStatusResponse$outboundSchema.parse(
      verificationGetStatusResponse,
    ),
  );
}
export function verificationGetStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusResponse' from JSON`,
  );
}
