/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VerificationLookupUserByEmailSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
};

export type VerificationLookupUserByEmailRequest = {
  email: string;
};

export type VerificationLookupUserByEmailData = {
  found?: boolean | undefined;
  clerkUserId?: string | undefined;
  hasPasskey?: boolean | undefined;
  isActive?: boolean | undefined;
};

/**
 * User lookup result
 */
export type VerificationLookupUserByEmailResponse = {
  data: VerificationLookupUserByEmailData;
};

/** @internal */
export const VerificationLookupUserByEmailSecurity$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
  apiKeyAuth3: types.optional(types.string()),
  apiKeyAuth4: types.optional(types.string()),
  apiKeyAuth5: types.optional(types.string()),
  apiKeyAuth6: types.optional(types.string()),
  apiKeyAuth7: types.optional(types.string()),
  apiKeyAuth8: types.optional(types.string()),
  apiKeyAuth9: types.optional(types.string()),
  apiKeyAuth10: types.optional(types.string()),
  apiKeyAuth11: types.optional(types.string()),
  apiKeyAuth12: types.optional(types.string()),
  apiKeyAuth13: types.optional(types.string()),
  apiKeyAuth14: types.optional(types.string()),
  apiKeyAuth15: types.optional(types.string()),
  apiKeyAuth16: types.optional(types.string()),
  apiKeyAuth17: types.optional(types.string()),
  apiKeyAuth18: types.optional(types.string()),
  apiKeyAuth19: types.optional(types.string()),
  apiKeyAuth20: types.optional(types.string()),
  apiKeyAuth21: types.optional(types.string()),
  apiKeyAuth22: types.optional(types.string()),
  apiKeyAuth23: types.optional(types.string()),
});
/** @internal */
export type VerificationLookupUserByEmailSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
};

/** @internal */
export const VerificationLookupUserByEmailSecurity$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailSecurity$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
  apiKeyAuth3: z.string().optional(),
  apiKeyAuth4: z.string().optional(),
  apiKeyAuth5: z.string().optional(),
  apiKeyAuth6: z.string().optional(),
  apiKeyAuth7: z.string().optional(),
  apiKeyAuth8: z.string().optional(),
  apiKeyAuth9: z.string().optional(),
  apiKeyAuth10: z.string().optional(),
  apiKeyAuth11: z.string().optional(),
  apiKeyAuth12: z.string().optional(),
  apiKeyAuth13: z.string().optional(),
  apiKeyAuth14: z.string().optional(),
  apiKeyAuth15: z.string().optional(),
  apiKeyAuth16: z.string().optional(),
  apiKeyAuth17: z.string().optional(),
  apiKeyAuth18: z.string().optional(),
  apiKeyAuth19: z.string().optional(),
  apiKeyAuth20: z.string().optional(),
  apiKeyAuth21: z.string().optional(),
  apiKeyAuth22: z.string().optional(),
  apiKeyAuth23: z.string().optional(),
});

export function verificationLookupUserByEmailSecurityToJSON(
  verificationLookupUserByEmailSecurity: VerificationLookupUserByEmailSecurity,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailSecurity$outboundSchema.parse(
      verificationLookupUserByEmailSecurity,
    ),
  );
}
export function verificationLookupUserByEmailSecurityFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailSecurity' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailRequest$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: types.string(),
});
/** @internal */
export type VerificationLookupUserByEmailRequest$Outbound = {
  email: string;
};

/** @internal */
export const VerificationLookupUserByEmailRequest$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailRequest$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailRequest
> = z.object({
  email: z.string(),
});

export function verificationLookupUserByEmailRequestToJSON(
  verificationLookupUserByEmailRequest: VerificationLookupUserByEmailRequest,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailRequest$outboundSchema.parse(
      verificationLookupUserByEmailRequest,
    ),
  );
}
export function verificationLookupUserByEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailRequest' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailData$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailData,
  z.ZodTypeDef,
  unknown
> = z.object({
  found: types.optional(types.boolean()),
  clerk_user_id: types.optional(types.string()),
  has_passkey: types.optional(types.boolean()),
  is_active: types.optional(types.boolean()),
}).transform((v) => {
  return remap$(v, {
    "clerk_user_id": "clerkUserId",
    "has_passkey": "hasPasskey",
    "is_active": "isActive",
  });
});
/** @internal */
export type VerificationLookupUserByEmailData$Outbound = {
  found?: boolean | undefined;
  clerk_user_id?: string | undefined;
  has_passkey?: boolean | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const VerificationLookupUserByEmailData$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailData$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailData
> = z.object({
  found: z.boolean().optional(),
  clerkUserId: z.string().optional(),
  hasPasskey: z.boolean().optional(),
  isActive: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    clerkUserId: "clerk_user_id",
    hasPasskey: "has_passkey",
    isActive: "is_active",
  });
});

export function verificationLookupUserByEmailDataToJSON(
  verificationLookupUserByEmailData: VerificationLookupUserByEmailData,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailData$outboundSchema.parse(
      verificationLookupUserByEmailData,
    ),
  );
}
export function verificationLookupUserByEmailDataFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationLookupUserByEmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailData' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailResponse$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => VerificationLookupUserByEmailData$inboundSchema),
});
/** @internal */
export type VerificationLookupUserByEmailResponse$Outbound = {
  data: VerificationLookupUserByEmailData$Outbound;
};

/** @internal */
export const VerificationLookupUserByEmailResponse$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailResponse$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailResponse
> = z.object({
  data: z.lazy(() => VerificationLookupUserByEmailData$outboundSchema),
});

export function verificationLookupUserByEmailResponseToJSON(
  verificationLookupUserByEmailResponse: VerificationLookupUserByEmailResponse,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailResponse$outboundSchema.parse(
      verificationLookupUserByEmailResponse,
    ),
  );
}
export function verificationLookupUserByEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailResponse' from JSON`,
  );
}
