/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VerificationLookupUserByEmailSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
  apiKeyAuth32?: string | undefined;
  apiKeyAuth33?: string | undefined;
  apiKeyAuth34?: string | undefined;
  apiKeyAuth35?: string | undefined;
  apiKeyAuth36?: string | undefined;
  apiKeyAuth37?: string | undefined;
  apiKeyAuth38?: string | undefined;
  apiKeyAuth39?: string | undefined;
  apiKeyAuth40?: string | undefined;
  apiKeyAuth41?: string | undefined;
  apiKeyAuth42?: string | undefined;
  apiKeyAuth43?: string | undefined;
  apiKeyAuth44?: string | undefined;
  apiKeyAuth45?: string | undefined;
  apiKeyAuth46?: string | undefined;
  apiKeyAuth47?: string | undefined;
  apiKeyAuth48?: string | undefined;
  apiKeyAuth49?: string | undefined;
  apiKeyAuth50?: string | undefined;
  apiKeyAuth51?: string | undefined;
  apiKeyAuth52?: string | undefined;
  apiKeyAuth53?: string | undefined;
  apiKeyAuth54?: string | undefined;
  apiKeyAuth55?: string | undefined;
  apiKeyAuth56?: string | undefined;
  apiKeyAuth57?: string | undefined;
};

export type VerificationLookupUserByEmailRequest = {
  email: string;
};

export type VerificationLookupUserByEmailData = {
  found?: boolean | undefined;
  clerkUserId?: string | undefined;
  hasPasskey?: boolean | undefined;
  isActive?: boolean | undefined;
};

/**
 * User lookup result
 */
export type VerificationLookupUserByEmailResponse = {
  data: VerificationLookupUserByEmailData;
};

/** @internal */
export const VerificationLookupUserByEmailSecurity$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
  apiKeyAuth3: types.optional(types.string()),
  apiKeyAuth4: types.optional(types.string()),
  apiKeyAuth5: types.optional(types.string()),
  apiKeyAuth6: types.optional(types.string()),
  apiKeyAuth7: types.optional(types.string()),
  apiKeyAuth8: types.optional(types.string()),
  apiKeyAuth9: types.optional(types.string()),
  apiKeyAuth10: types.optional(types.string()),
  apiKeyAuth11: types.optional(types.string()),
  apiKeyAuth12: types.optional(types.string()),
  apiKeyAuth13: types.optional(types.string()),
  apiKeyAuth14: types.optional(types.string()),
  apiKeyAuth15: types.optional(types.string()),
  apiKeyAuth16: types.optional(types.string()),
  apiKeyAuth17: types.optional(types.string()),
  apiKeyAuth18: types.optional(types.string()),
  apiKeyAuth19: types.optional(types.string()),
  apiKeyAuth20: types.optional(types.string()),
  apiKeyAuth21: types.optional(types.string()),
  apiKeyAuth22: types.optional(types.string()),
  apiKeyAuth23: types.optional(types.string()),
  apiKeyAuth24: types.optional(types.string()),
  apiKeyAuth25: types.optional(types.string()),
  apiKeyAuth26: types.optional(types.string()),
  apiKeyAuth27: types.optional(types.string()),
  apiKeyAuth28: types.optional(types.string()),
  apiKeyAuth29: types.optional(types.string()),
  apiKeyAuth30: types.optional(types.string()),
  apiKeyAuth31: types.optional(types.string()),
  apiKeyAuth32: types.optional(types.string()),
  apiKeyAuth33: types.optional(types.string()),
  apiKeyAuth34: types.optional(types.string()),
  apiKeyAuth35: types.optional(types.string()),
  apiKeyAuth36: types.optional(types.string()),
  apiKeyAuth37: types.optional(types.string()),
  apiKeyAuth38: types.optional(types.string()),
  apiKeyAuth39: types.optional(types.string()),
  apiKeyAuth40: types.optional(types.string()),
  apiKeyAuth41: types.optional(types.string()),
  apiKeyAuth42: types.optional(types.string()),
  apiKeyAuth43: types.optional(types.string()),
  apiKeyAuth44: types.optional(types.string()),
  apiKeyAuth45: types.optional(types.string()),
  apiKeyAuth46: types.optional(types.string()),
  apiKeyAuth47: types.optional(types.string()),
  apiKeyAuth48: types.optional(types.string()),
  apiKeyAuth49: types.optional(types.string()),
  apiKeyAuth50: types.optional(types.string()),
  apiKeyAuth51: types.optional(types.string()),
  apiKeyAuth52: types.optional(types.string()),
  apiKeyAuth53: types.optional(types.string()),
  apiKeyAuth54: types.optional(types.string()),
  apiKeyAuth55: types.optional(types.string()),
  apiKeyAuth56: types.optional(types.string()),
  apiKeyAuth57: types.optional(types.string()),
});
/** @internal */
export type VerificationLookupUserByEmailSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
  apiKeyAuth3?: string | undefined;
  apiKeyAuth4?: string | undefined;
  apiKeyAuth5?: string | undefined;
  apiKeyAuth6?: string | undefined;
  apiKeyAuth7?: string | undefined;
  apiKeyAuth8?: string | undefined;
  apiKeyAuth9?: string | undefined;
  apiKeyAuth10?: string | undefined;
  apiKeyAuth11?: string | undefined;
  apiKeyAuth12?: string | undefined;
  apiKeyAuth13?: string | undefined;
  apiKeyAuth14?: string | undefined;
  apiKeyAuth15?: string | undefined;
  apiKeyAuth16?: string | undefined;
  apiKeyAuth17?: string | undefined;
  apiKeyAuth18?: string | undefined;
  apiKeyAuth19?: string | undefined;
  apiKeyAuth20?: string | undefined;
  apiKeyAuth21?: string | undefined;
  apiKeyAuth22?: string | undefined;
  apiKeyAuth23?: string | undefined;
  apiKeyAuth24?: string | undefined;
  apiKeyAuth25?: string | undefined;
  apiKeyAuth26?: string | undefined;
  apiKeyAuth27?: string | undefined;
  apiKeyAuth28?: string | undefined;
  apiKeyAuth29?: string | undefined;
  apiKeyAuth30?: string | undefined;
  apiKeyAuth31?: string | undefined;
  apiKeyAuth32?: string | undefined;
  apiKeyAuth33?: string | undefined;
  apiKeyAuth34?: string | undefined;
  apiKeyAuth35?: string | undefined;
  apiKeyAuth36?: string | undefined;
  apiKeyAuth37?: string | undefined;
  apiKeyAuth38?: string | undefined;
  apiKeyAuth39?: string | undefined;
  apiKeyAuth40?: string | undefined;
  apiKeyAuth41?: string | undefined;
  apiKeyAuth42?: string | undefined;
  apiKeyAuth43?: string | undefined;
  apiKeyAuth44?: string | undefined;
  apiKeyAuth45?: string | undefined;
  apiKeyAuth46?: string | undefined;
  apiKeyAuth47?: string | undefined;
  apiKeyAuth48?: string | undefined;
  apiKeyAuth49?: string | undefined;
  apiKeyAuth50?: string | undefined;
  apiKeyAuth51?: string | undefined;
  apiKeyAuth52?: string | undefined;
  apiKeyAuth53?: string | undefined;
  apiKeyAuth54?: string | undefined;
  apiKeyAuth55?: string | undefined;
  apiKeyAuth56?: string | undefined;
  apiKeyAuth57?: string | undefined;
};

/** @internal */
export const VerificationLookupUserByEmailSecurity$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailSecurity$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
  apiKeyAuth3: z.string().optional(),
  apiKeyAuth4: z.string().optional(),
  apiKeyAuth5: z.string().optional(),
  apiKeyAuth6: z.string().optional(),
  apiKeyAuth7: z.string().optional(),
  apiKeyAuth8: z.string().optional(),
  apiKeyAuth9: z.string().optional(),
  apiKeyAuth10: z.string().optional(),
  apiKeyAuth11: z.string().optional(),
  apiKeyAuth12: z.string().optional(),
  apiKeyAuth13: z.string().optional(),
  apiKeyAuth14: z.string().optional(),
  apiKeyAuth15: z.string().optional(),
  apiKeyAuth16: z.string().optional(),
  apiKeyAuth17: z.string().optional(),
  apiKeyAuth18: z.string().optional(),
  apiKeyAuth19: z.string().optional(),
  apiKeyAuth20: z.string().optional(),
  apiKeyAuth21: z.string().optional(),
  apiKeyAuth22: z.string().optional(),
  apiKeyAuth23: z.string().optional(),
  apiKeyAuth24: z.string().optional(),
  apiKeyAuth25: z.string().optional(),
  apiKeyAuth26: z.string().optional(),
  apiKeyAuth27: z.string().optional(),
  apiKeyAuth28: z.string().optional(),
  apiKeyAuth29: z.string().optional(),
  apiKeyAuth30: z.string().optional(),
  apiKeyAuth31: z.string().optional(),
  apiKeyAuth32: z.string().optional(),
  apiKeyAuth33: z.string().optional(),
  apiKeyAuth34: z.string().optional(),
  apiKeyAuth35: z.string().optional(),
  apiKeyAuth36: z.string().optional(),
  apiKeyAuth37: z.string().optional(),
  apiKeyAuth38: z.string().optional(),
  apiKeyAuth39: z.string().optional(),
  apiKeyAuth40: z.string().optional(),
  apiKeyAuth41: z.string().optional(),
  apiKeyAuth42: z.string().optional(),
  apiKeyAuth43: z.string().optional(),
  apiKeyAuth44: z.string().optional(),
  apiKeyAuth45: z.string().optional(),
  apiKeyAuth46: z.string().optional(),
  apiKeyAuth47: z.string().optional(),
  apiKeyAuth48: z.string().optional(),
  apiKeyAuth49: z.string().optional(),
  apiKeyAuth50: z.string().optional(),
  apiKeyAuth51: z.string().optional(),
  apiKeyAuth52: z.string().optional(),
  apiKeyAuth53: z.string().optional(),
  apiKeyAuth54: z.string().optional(),
  apiKeyAuth55: z.string().optional(),
  apiKeyAuth56: z.string().optional(),
  apiKeyAuth57: z.string().optional(),
});

export function verificationLookupUserByEmailSecurityToJSON(
  verificationLookupUserByEmailSecurity: VerificationLookupUserByEmailSecurity,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailSecurity$outboundSchema.parse(
      verificationLookupUserByEmailSecurity,
    ),
  );
}
export function verificationLookupUserByEmailSecurityFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailSecurity' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailRequest$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: types.string(),
});
/** @internal */
export type VerificationLookupUserByEmailRequest$Outbound = {
  email: string;
};

/** @internal */
export const VerificationLookupUserByEmailRequest$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailRequest$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailRequest
> = z.object({
  email: z.string(),
});

export function verificationLookupUserByEmailRequestToJSON(
  verificationLookupUserByEmailRequest: VerificationLookupUserByEmailRequest,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailRequest$outboundSchema.parse(
      verificationLookupUserByEmailRequest,
    ),
  );
}
export function verificationLookupUserByEmailRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailRequest' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailData$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailData,
  z.ZodTypeDef,
  unknown
> = z.object({
  found: types.optional(types.boolean()),
  clerk_user_id: types.optional(types.string()),
  has_passkey: types.optional(types.boolean()),
  is_active: types.optional(types.boolean()),
}).transform((v) => {
  return remap$(v, {
    "clerk_user_id": "clerkUserId",
    "has_passkey": "hasPasskey",
    "is_active": "isActive",
  });
});
/** @internal */
export type VerificationLookupUserByEmailData$Outbound = {
  found?: boolean | undefined;
  clerk_user_id?: string | undefined;
  has_passkey?: boolean | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const VerificationLookupUserByEmailData$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailData$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailData
> = z.object({
  found: z.boolean().optional(),
  clerkUserId: z.string().optional(),
  hasPasskey: z.boolean().optional(),
  isActive: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    clerkUserId: "clerk_user_id",
    hasPasskey: "has_passkey",
    isActive: "is_active",
  });
});

export function verificationLookupUserByEmailDataToJSON(
  verificationLookupUserByEmailData: VerificationLookupUserByEmailData,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailData$outboundSchema.parse(
      verificationLookupUserByEmailData,
    ),
  );
}
export function verificationLookupUserByEmailDataFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationLookupUserByEmailData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailData' from JSON`,
  );
}

/** @internal */
export const VerificationLookupUserByEmailResponse$inboundSchema: z.ZodType<
  VerificationLookupUserByEmailResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => VerificationLookupUserByEmailData$inboundSchema),
});
/** @internal */
export type VerificationLookupUserByEmailResponse$Outbound = {
  data: VerificationLookupUserByEmailData$Outbound;
};

/** @internal */
export const VerificationLookupUserByEmailResponse$outboundSchema: z.ZodType<
  VerificationLookupUserByEmailResponse$Outbound,
  z.ZodTypeDef,
  VerificationLookupUserByEmailResponse
> = z.object({
  data: z.lazy(() => VerificationLookupUserByEmailData$outboundSchema),
});

export function verificationLookupUserByEmailResponseToJSON(
  verificationLookupUserByEmailResponse: VerificationLookupUserByEmailResponse,
): string {
  return JSON.stringify(
    VerificationLookupUserByEmailResponse$outboundSchema.parse(
      verificationLookupUserByEmailResponse,
    ),
  );
}
export function verificationLookupUserByEmailResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerificationLookupUserByEmailResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VerificationLookupUserByEmailResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationLookupUserByEmailResponse' from JSON`,
  );
}
