/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type VerificationGetStatusSecurity = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

export type VerificationGetStatusRequest = {
  requestId: string;
};

export const VerificationGetStatusStatus = {
  Pending: "pending",
  Completed: "completed",
  Expired: "expired",
  Failed: "failed",
  NotFound: "not_found",
  Error: "error",
} as const;
export type VerificationGetStatusStatus = OpenEnum<
  typeof VerificationGetStatusStatus
>;

export const VerificationGetStatusSDKType = {
  Signal: "signal",
  Presence: "presence",
} as const;
export type VerificationGetStatusSDKType = OpenEnum<
  typeof VerificationGetStatusSDKType
>;

export type Metadata = {
  /**
   * The gate.
   */
  scope?: string | null | undefined;
  sdkType?: string | null | undefined;
  environment?: string | null | undefined;
  returnUrl?: string | null | undefined;
  parentRequestId?: string | null | undefined;
};

export type VerificationGetStatusData = {
  found?: boolean | undefined;
  status?: VerificationGetStatusStatus | undefined;
  requestId?: string | undefined;
  organizationId?: string | undefined;
  createdAt?: Date | undefined;
  expiresAt?: Date | undefined;
  verifiedAt?: Date | null | undefined;
  signedToken?: string | null | undefined;
  /**
   * Legacy alias
   */
  verificationToken?: string | null | undefined;
  errorMessage?: string | null | undefined;
  sdkType?: VerificationGetStatusSDKType | null | undefined;
  scope?: string | null | undefined;
  /**
   * Only for sdk_type=presence; null on every other lane.
   */
  presenceAddress?: string | null | undefined;
  metadata?: Metadata | null | undefined;
  /**
   * Present on not_found / error.
   */
  message?: string | undefined;
  /**
   * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
   */
  error?: models.ErrorBody | undefined;
};

/**
 * Verification status. NOTE: handler errors also arrive here (HTTP 200) as data.error — codes for this operation: none — unknown ids return status not_found.
 */
export type VerificationGetStatusResponse = {
  data: VerificationGetStatusData;
};

/** @internal */
export const VerificationGetStatusSecurity$inboundSchema: z.ZodType<
  VerificationGetStatusSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  apiKeyAuth: types.optional(types.string()),
  apiKeyAuth1: types.optional(types.string()),
  apiKeyAuth2: types.optional(types.string()),
});
/** @internal */
export type VerificationGetStatusSecurity$Outbound = {
  apiKeyAuth?: string | undefined;
  apiKeyAuth1?: string | undefined;
  apiKeyAuth2?: string | undefined;
};

/** @internal */
export const VerificationGetStatusSecurity$outboundSchema: z.ZodType<
  VerificationGetStatusSecurity$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusSecurity
> = z.object({
  apiKeyAuth: z.string().optional(),
  apiKeyAuth1: z.string().optional(),
  apiKeyAuth2: z.string().optional(),
});

export function verificationGetStatusSecurityToJSON(
  verificationGetStatusSecurity: VerificationGetStatusSecurity,
): string {
  return JSON.stringify(
    VerificationGetStatusSecurity$outboundSchema.parse(
      verificationGetStatusSecurity,
    ),
  );
}
export function verificationGetStatusSecurityFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusSecurity' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusRequest$inboundSchema: z.ZodType<
  VerificationGetStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  request_id: types.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type VerificationGetStatusRequest$Outbound = {
  request_id: string;
};

/** @internal */
export const VerificationGetStatusRequest$outboundSchema: z.ZodType<
  VerificationGetStatusRequest$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusRequest
> = z.object({
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function verificationGetStatusRequestToJSON(
  verificationGetStatusRequest: VerificationGetStatusRequest,
): string {
  return JSON.stringify(
    VerificationGetStatusRequest$outboundSchema.parse(
      verificationGetStatusRequest,
    ),
  );
}
export function verificationGetStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusRequest' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusStatus$inboundSchema: z.ZodType<
  VerificationGetStatusStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(VerificationGetStatusStatus);
/** @internal */
export const VerificationGetStatusStatus$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  VerificationGetStatusStatus
> = openEnums.outboundSchema(VerificationGetStatusStatus);

/** @internal */
export const VerificationGetStatusSDKType$inboundSchema: z.ZodType<
  VerificationGetStatusSDKType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(VerificationGetStatusSDKType);
/** @internal */
export const VerificationGetStatusSDKType$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  VerificationGetStatusSDKType
> = openEnums.outboundSchema(VerificationGetStatusSDKType);

/** @internal */
export const Metadata$inboundSchema: z.ZodType<
  Metadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  scope: z.nullable(types.string()).optional(),
  sdk_type: z.nullable(types.string()).optional(),
  environment: z.nullable(types.string()).optional(),
  return_url: z.nullable(types.string()).optional(),
  parent_request_id: z.nullable(types.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "sdk_type": "sdkType",
    "return_url": "returnUrl",
    "parent_request_id": "parentRequestId",
  });
});
/** @internal */
export type Metadata$Outbound = {
  scope?: string | null | undefined;
  sdk_type?: string | null | undefined;
  environment?: string | null | undefined;
  return_url?: string | null | undefined;
  parent_request_id?: string | null | undefined;
};

/** @internal */
export const Metadata$outboundSchema: z.ZodType<
  Metadata$Outbound,
  z.ZodTypeDef,
  Metadata
> = z.object({
  scope: z.nullable(z.string()).optional(),
  sdkType: z.nullable(z.string()).optional(),
  environment: z.nullable(z.string()).optional(),
  returnUrl: z.nullable(z.string()).optional(),
  parentRequestId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    sdkType: "sdk_type",
    returnUrl: "return_url",
    parentRequestId: "parent_request_id",
  });
});

export function metadataToJSON(metadata: Metadata): string {
  return JSON.stringify(Metadata$outboundSchema.parse(metadata));
}
export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusData$inboundSchema: z.ZodType<
  VerificationGetStatusData,
  z.ZodTypeDef,
  unknown
> = z.object({
  found: types.optional(types.boolean()),
  status: types.optional(VerificationGetStatusStatus$inboundSchema),
  request_id: types.optional(types.string()),
  organization_id: types.optional(types.string()),
  created_at: types.optional(types.date()),
  expires_at: types.optional(types.date()),
  verified_at: z.nullable(types.date()).optional(),
  signed_token: z.nullable(types.string()).optional(),
  verification_token: z.nullable(types.string()).optional(),
  error_message: z.nullable(types.string()).optional(),
  sdk_type: z.nullable(VerificationGetStatusSDKType$inboundSchema).optional(),
  scope: z.nullable(types.string()).optional(),
  presence_address: z.nullable(types.string()).optional(),
  metadata: z.nullable(z.lazy(() => Metadata$inboundSchema)).optional(),
  message: types.optional(types.string()),
  error: types.optional(models.ErrorBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
    "organization_id": "organizationId",
    "created_at": "createdAt",
    "expires_at": "expiresAt",
    "verified_at": "verifiedAt",
    "signed_token": "signedToken",
    "verification_token": "verificationToken",
    "error_message": "errorMessage",
    "sdk_type": "sdkType",
    "presence_address": "presenceAddress",
  });
});
/** @internal */
export type VerificationGetStatusData$Outbound = {
  found?: boolean | undefined;
  status?: string | undefined;
  request_id?: string | undefined;
  organization_id?: string | undefined;
  created_at?: string | undefined;
  expires_at?: string | undefined;
  verified_at?: string | null | undefined;
  signed_token?: string | null | undefined;
  verification_token?: string | null | undefined;
  error_message?: string | null | undefined;
  sdk_type?: string | null | undefined;
  scope?: string | null | undefined;
  presence_address?: string | null | undefined;
  metadata?: Metadata$Outbound | null | undefined;
  message?: string | undefined;
  error?: models.ErrorBody$Outbound | undefined;
};

/** @internal */
export const VerificationGetStatusData$outboundSchema: z.ZodType<
  VerificationGetStatusData$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusData
> = z.object({
  found: z.boolean().optional(),
  status: VerificationGetStatusStatus$outboundSchema.optional(),
  requestId: z.string().optional(),
  organizationId: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  expiresAt: z.date().transform(v => v.toISOString()).optional(),
  verifiedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  signedToken: z.nullable(z.string()).optional(),
  verificationToken: z.nullable(z.string()).optional(),
  errorMessage: z.nullable(z.string()).optional(),
  sdkType: z.nullable(VerificationGetStatusSDKType$outboundSchema).optional(),
  scope: z.nullable(z.string()).optional(),
  presenceAddress: z.nullable(z.string()).optional(),
  metadata: z.nullable(z.lazy(() => Metadata$outboundSchema)).optional(),
  message: z.string().optional(),
  error: models.ErrorBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
    organizationId: "organization_id",
    createdAt: "created_at",
    expiresAt: "expires_at",
    verifiedAt: "verified_at",
    signedToken: "signed_token",
    verificationToken: "verification_token",
    errorMessage: "error_message",
    sdkType: "sdk_type",
    presenceAddress: "presence_address",
  });
});

export function verificationGetStatusDataToJSON(
  verificationGetStatusData: VerificationGetStatusData,
): string {
  return JSON.stringify(
    VerificationGetStatusData$outboundSchema.parse(verificationGetStatusData),
  );
}
export function verificationGetStatusDataFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusData' from JSON`,
  );
}

/** @internal */
export const VerificationGetStatusResponse$inboundSchema: z.ZodType<
  VerificationGetStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => VerificationGetStatusData$inboundSchema),
});
/** @internal */
export type VerificationGetStatusResponse$Outbound = {
  data: VerificationGetStatusData$Outbound;
};

/** @internal */
export const VerificationGetStatusResponse$outboundSchema: z.ZodType<
  VerificationGetStatusResponse$Outbound,
  z.ZodTypeDef,
  VerificationGetStatusResponse
> = z.object({
  data: z.lazy(() => VerificationGetStatusData$outboundSchema),
});

export function verificationGetStatusResponseToJSON(
  verificationGetStatusResponse: VerificationGetStatusResponse,
): string {
  return JSON.stringify(
    VerificationGetStatusResponse$outboundSchema.parse(
      verificationGetStatusResponse,
    ),
  );
}
export function verificationGetStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<VerificationGetStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VerificationGetStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VerificationGetStatusResponse' from JSON`,
  );
}
