/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Violation = {
  type?: string | undefined;
  path?: string | undefined;
  severity?: string | undefined;
};

/**
 * Handler error. Arrives inside data.error with HTTP 200 — check for it before reading the result.
 */
export type ErrorBody = {
  message: string;
  /**
   * The HTTP status the error stands for (401, 403, 404, 409, 422, 500, 502).
   */
  statusCode: number;
  /**
   * Machine code when present, e.g. ttl_below_floor, ttl_above_ceiling.
   */
  code?: string | undefined;
  minTtlSeconds?: number | undefined;
  maxTtlSeconds?: number | undefined;
  /**
   * Adaptive Card TRUST-layer rejections (statusCode 422).
   */
  violations?: Array<Violation> | undefined;
};

/** @internal */
export const Violation$inboundSchema: z.ZodType<
  Violation,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: types.optional(types.string()),
  path: types.optional(types.string()),
  severity: types.optional(types.string()),
});
/** @internal */
export type Violation$Outbound = {
  type?: string | undefined;
  path?: string | undefined;
  severity?: string | undefined;
};

/** @internal */
export const Violation$outboundSchema: z.ZodType<
  Violation$Outbound,
  z.ZodTypeDef,
  Violation
> = z.object({
  type: z.string().optional(),
  path: z.string().optional(),
  severity: z.string().optional(),
});

export function violationToJSON(violation: Violation): string {
  return JSON.stringify(Violation$outboundSchema.parse(violation));
}
export function violationFromJSON(
  jsonString: string,
): SafeParseResult<Violation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Violation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Violation' from JSON`,
  );
}

/** @internal */
export const ErrorBody$inboundSchema: z.ZodType<
  ErrorBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: types.string(),
  statusCode: types.number(),
  code: types.optional(types.string()),
  min_ttl_seconds: types.optional(types.number()),
  max_ttl_seconds: types.optional(types.number()),
  violations: types.optional(z.array(z.lazy(() => Violation$inboundSchema))),
}).transform((v) => {
  return remap$(v, {
    "min_ttl_seconds": "minTtlSeconds",
    "max_ttl_seconds": "maxTtlSeconds",
  });
});
/** @internal */
export type ErrorBody$Outbound = {
  message: string;
  statusCode: number;
  code?: string | undefined;
  min_ttl_seconds?: number | undefined;
  max_ttl_seconds?: number | undefined;
  violations?: Array<Violation$Outbound> | undefined;
};

/** @internal */
export const ErrorBody$outboundSchema: z.ZodType<
  ErrorBody$Outbound,
  z.ZodTypeDef,
  ErrorBody
> = z.object({
  message: z.string(),
  statusCode: z.number().int(),
  code: z.string().optional(),
  minTtlSeconds: z.number().int().optional(),
  maxTtlSeconds: z.number().int().optional(),
  violations: z.array(z.lazy(() => Violation$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    minTtlSeconds: "min_ttl_seconds",
    maxTtlSeconds: "max_ttl_seconds",
  });
});

export function errorBodyToJSON(errorBody: ErrorBody): string {
  return JSON.stringify(ErrorBody$outboundSchema.parse(errorBody));
}
export function errorBodyFromJSON(
  jsonString: string,
): SafeParseResult<ErrorBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorBody' from JSON`,
  );
}
