/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ErrorResponseError = {
  message: string;
  statusCode: number;
};

/** @internal */
export const ErrorResponseError$inboundSchema: z.ZodType<
  ErrorResponseError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: types.string(),
  statusCode: types.number(),
});
/** @internal */
export type ErrorResponseError$Outbound = {
  message: string;
  statusCode: number;
};

/** @internal */
export const ErrorResponseError$outboundSchema: z.ZodType<
  ErrorResponseError$Outbound,
  z.ZodTypeDef,
  ErrorResponseError
> = z.object({
  message: z.string(),
  statusCode: z.number().int(),
});

export function errorResponseErrorToJSON(
  errorResponseError: ErrorResponseError,
): string {
  return JSON.stringify(
    ErrorResponseError$outboundSchema.parse(errorResponseError),
  );
}
export function errorResponseErrorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorResponseError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorResponseError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorResponseError' from JSON`,
  );
}
