/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InvalidInputErrorError = {
  propertyPath: string;
  /**
   * The invalid value
   */
  invalidValue?: any | undefined;
  message: string;
};

/** @internal */
export const InvalidInputErrorError$inboundSchema: z.ZodType<
  InvalidInputErrorError,
  z.ZodTypeDef,
  unknown
> = z.object({
  propertyPath: types.string(),
  invalidValue: types.optional(z.any()),
  message: types.string(),
});
/** @internal */
export type InvalidInputErrorError$Outbound = {
  propertyPath: string;
  invalidValue?: any | undefined;
  message: string;
};

/** @internal */
export const InvalidInputErrorError$outboundSchema: z.ZodType<
  InvalidInputErrorError$Outbound,
  z.ZodTypeDef,
  InvalidInputErrorError
> = z.object({
  propertyPath: z.string(),
  invalidValue: z.any().optional(),
  message: z.string(),
});

export function invalidInputErrorErrorToJSON(
  invalidInputErrorError: InvalidInputErrorError,
): string {
  return JSON.stringify(
    InvalidInputErrorError$outboundSchema.parse(invalidInputErrorError),
  );
}
export function invalidInputErrorErrorFromJSON(
  jsonString: string,
): SafeParseResult<InvalidInputErrorError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvalidInputErrorError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvalidInputErrorError' from JSON`,
  );
}
