/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Security = {
  agentKeyAuth?: string | undefined;
  agentKeyAuth1?: string | undefined;
  agentKeyAuth2?: string | undefined;
};

/** @internal */
export const Security$inboundSchema: z.ZodType<
  Security,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentKeyAuth: types.optional(types.string()),
  agentKeyAuth1: types.optional(types.string()),
  agentKeyAuth2: types.optional(types.string()),
});
/** @internal */
export type Security$Outbound = {
  agentKeyAuth?: string | undefined;
  agentKeyAuth1?: string | undefined;
  agentKeyAuth2?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  agentKeyAuth: z.string().optional(),
  agentKeyAuth1: z.string().optional(),
  agentKeyAuth2: z.string().optional(),
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
export function securityFromJSON(
  jsonString: string,
): SafeParseResult<Security, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Security$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Security' from JSON`,
  );
}
