/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Security = {
  agentKeyAuth?: string | undefined;
  agentKeyAuth1?: string | undefined;
  agentKeyAuth2?: string | undefined;
  agentKeyAuth3?: string | undefined;
  agentKeyAuth4?: string | undefined;
  agentKeyAuth5?: string | undefined;
  agentKeyAuth6?: string | undefined;
  agentKeyAuth7?: string | undefined;
  agentKeyAuth8?: string | undefined;
  agentKeyAuth9?: string | undefined;
  agentKeyAuth10?: string | undefined;
  agentKeyAuth11?: string | undefined;
  agentKeyAuth12?: string | undefined;
  agentKeyAuth13?: string | undefined;
  agentKeyAuth14?: string | undefined;
  agentKeyAuth15?: string | undefined;
  agentKeyAuth16?: string | undefined;
  agentKeyAuth17?: string | undefined;
  agentKeyAuth18?: string | undefined;
  agentKeyAuth19?: string | undefined;
  agentKeyAuth20?: string | undefined;
  agentKeyAuth21?: string | undefined;
  agentKeyAuth22?: string | undefined;
  agentKeyAuth23?: string | undefined;
  agentKeyAuth24?: string | undefined;
  agentKeyAuth25?: string | undefined;
  agentKeyAuth26?: string | undefined;
  agentKeyAuth27?: string | undefined;
  agentKeyAuth28?: string | undefined;
  agentKeyAuth29?: string | undefined;
  agentKeyAuth30?: string | undefined;
  agentKeyAuth31?: string | undefined;
  agentKeyAuth32?: string | undefined;
  agentKeyAuth33?: string | undefined;
  agentKeyAuth34?: string | undefined;
  agentKeyAuth35?: string | undefined;
  agentKeyAuth36?: string | undefined;
  agentKeyAuth37?: string | undefined;
  agentKeyAuth38?: string | undefined;
  agentKeyAuth39?: string | undefined;
  agentKeyAuth40?: string | undefined;
  agentKeyAuth41?: string | undefined;
  agentKeyAuth42?: string | undefined;
  agentKeyAuth43?: string | undefined;
  agentKeyAuth44?: string | undefined;
  agentKeyAuth45?: string | undefined;
  agentKeyAuth46?: string | undefined;
  agentKeyAuth47?: string | undefined;
  agentKeyAuth48?: string | undefined;
  agentKeyAuth49?: string | undefined;
  agentKeyAuth50?: string | undefined;
  agentKeyAuth51?: string | undefined;
};

/** @internal */
export const Security$inboundSchema: z.ZodType<
  Security,
  z.ZodTypeDef,
  unknown
> = z.object({
  agentKeyAuth: types.optional(types.string()),
  agentKeyAuth1: types.optional(types.string()),
  agentKeyAuth2: types.optional(types.string()),
  agentKeyAuth3: types.optional(types.string()),
  agentKeyAuth4: types.optional(types.string()),
  agentKeyAuth5: types.optional(types.string()),
  agentKeyAuth6: types.optional(types.string()),
  agentKeyAuth7: types.optional(types.string()),
  agentKeyAuth8: types.optional(types.string()),
  agentKeyAuth9: types.optional(types.string()),
  agentKeyAuth10: types.optional(types.string()),
  agentKeyAuth11: types.optional(types.string()),
  agentKeyAuth12: types.optional(types.string()),
  agentKeyAuth13: types.optional(types.string()),
  agentKeyAuth14: types.optional(types.string()),
  agentKeyAuth15: types.optional(types.string()),
  agentKeyAuth16: types.optional(types.string()),
  agentKeyAuth17: types.optional(types.string()),
  agentKeyAuth18: types.optional(types.string()),
  agentKeyAuth19: types.optional(types.string()),
  agentKeyAuth20: types.optional(types.string()),
  agentKeyAuth21: types.optional(types.string()),
  agentKeyAuth22: types.optional(types.string()),
  agentKeyAuth23: types.optional(types.string()),
  agentKeyAuth24: types.optional(types.string()),
  agentKeyAuth25: types.optional(types.string()),
  agentKeyAuth26: types.optional(types.string()),
  agentKeyAuth27: types.optional(types.string()),
  agentKeyAuth28: types.optional(types.string()),
  agentKeyAuth29: types.optional(types.string()),
  agentKeyAuth30: types.optional(types.string()),
  agentKeyAuth31: types.optional(types.string()),
  agentKeyAuth32: types.optional(types.string()),
  agentKeyAuth33: types.optional(types.string()),
  agentKeyAuth34: types.optional(types.string()),
  agentKeyAuth35: types.optional(types.string()),
  agentKeyAuth36: types.optional(types.string()),
  agentKeyAuth37: types.optional(types.string()),
  agentKeyAuth38: types.optional(types.string()),
  agentKeyAuth39: types.optional(types.string()),
  agentKeyAuth40: types.optional(types.string()),
  agentKeyAuth41: types.optional(types.string()),
  agentKeyAuth42: types.optional(types.string()),
  agentKeyAuth43: types.optional(types.string()),
  agentKeyAuth44: types.optional(types.string()),
  agentKeyAuth45: types.optional(types.string()),
  agentKeyAuth46: types.optional(types.string()),
  agentKeyAuth47: types.optional(types.string()),
  agentKeyAuth48: types.optional(types.string()),
  agentKeyAuth49: types.optional(types.string()),
  agentKeyAuth50: types.optional(types.string()),
  agentKeyAuth51: types.optional(types.string()),
});
/** @internal */
export type Security$Outbound = {
  agentKeyAuth?: string | undefined;
  agentKeyAuth1?: string | undefined;
  agentKeyAuth2?: string | undefined;
  agentKeyAuth3?: string | undefined;
  agentKeyAuth4?: string | undefined;
  agentKeyAuth5?: string | undefined;
  agentKeyAuth6?: string | undefined;
  agentKeyAuth7?: string | undefined;
  agentKeyAuth8?: string | undefined;
  agentKeyAuth9?: string | undefined;
  agentKeyAuth10?: string | undefined;
  agentKeyAuth11?: string | undefined;
  agentKeyAuth12?: string | undefined;
  agentKeyAuth13?: string | undefined;
  agentKeyAuth14?: string | undefined;
  agentKeyAuth15?: string | undefined;
  agentKeyAuth16?: string | undefined;
  agentKeyAuth17?: string | undefined;
  agentKeyAuth18?: string | undefined;
  agentKeyAuth19?: string | undefined;
  agentKeyAuth20?: string | undefined;
  agentKeyAuth21?: string | undefined;
  agentKeyAuth22?: string | undefined;
  agentKeyAuth23?: string | undefined;
  agentKeyAuth24?: string | undefined;
  agentKeyAuth25?: string | undefined;
  agentKeyAuth26?: string | undefined;
  agentKeyAuth27?: string | undefined;
  agentKeyAuth28?: string | undefined;
  agentKeyAuth29?: string | undefined;
  agentKeyAuth30?: string | undefined;
  agentKeyAuth31?: string | undefined;
  agentKeyAuth32?: string | undefined;
  agentKeyAuth33?: string | undefined;
  agentKeyAuth34?: string | undefined;
  agentKeyAuth35?: string | undefined;
  agentKeyAuth36?: string | undefined;
  agentKeyAuth37?: string | undefined;
  agentKeyAuth38?: string | undefined;
  agentKeyAuth39?: string | undefined;
  agentKeyAuth40?: string | undefined;
  agentKeyAuth41?: string | undefined;
  agentKeyAuth42?: string | undefined;
  agentKeyAuth43?: string | undefined;
  agentKeyAuth44?: string | undefined;
  agentKeyAuth45?: string | undefined;
  agentKeyAuth46?: string | undefined;
  agentKeyAuth47?: string | undefined;
  agentKeyAuth48?: string | undefined;
  agentKeyAuth49?: string | undefined;
  agentKeyAuth50?: string | undefined;
  agentKeyAuth51?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  agentKeyAuth: z.string().optional(),
  agentKeyAuth1: z.string().optional(),
  agentKeyAuth2: z.string().optional(),
  agentKeyAuth3: z.string().optional(),
  agentKeyAuth4: z.string().optional(),
  agentKeyAuth5: z.string().optional(),
  agentKeyAuth6: z.string().optional(),
  agentKeyAuth7: z.string().optional(),
  agentKeyAuth8: z.string().optional(),
  agentKeyAuth9: z.string().optional(),
  agentKeyAuth10: z.string().optional(),
  agentKeyAuth11: z.string().optional(),
  agentKeyAuth12: z.string().optional(),
  agentKeyAuth13: z.string().optional(),
  agentKeyAuth14: z.string().optional(),
  agentKeyAuth15: z.string().optional(),
  agentKeyAuth16: z.string().optional(),
  agentKeyAuth17: z.string().optional(),
  agentKeyAuth18: z.string().optional(),
  agentKeyAuth19: z.string().optional(),
  agentKeyAuth20: z.string().optional(),
  agentKeyAuth21: z.string().optional(),
  agentKeyAuth22: z.string().optional(),
  agentKeyAuth23: z.string().optional(),
  agentKeyAuth24: z.string().optional(),
  agentKeyAuth25: z.string().optional(),
  agentKeyAuth26: z.string().optional(),
  agentKeyAuth27: z.string().optional(),
  agentKeyAuth28: z.string().optional(),
  agentKeyAuth29: z.string().optional(),
  agentKeyAuth30: z.string().optional(),
  agentKeyAuth31: z.string().optional(),
  agentKeyAuth32: z.string().optional(),
  agentKeyAuth33: z.string().optional(),
  agentKeyAuth34: z.string().optional(),
  agentKeyAuth35: z.string().optional(),
  agentKeyAuth36: z.string().optional(),
  agentKeyAuth37: z.string().optional(),
  agentKeyAuth38: z.string().optional(),
  agentKeyAuth39: z.string().optional(),
  agentKeyAuth40: z.string().optional(),
  agentKeyAuth41: z.string().optional(),
  agentKeyAuth42: z.string().optional(),
  agentKeyAuth43: z.string().optional(),
  agentKeyAuth44: z.string().optional(),
  agentKeyAuth45: z.string().optional(),
  agentKeyAuth46: z.string().optional(),
  agentKeyAuth47: z.string().optional(),
  agentKeyAuth48: z.string().optional(),
  agentKeyAuth49: z.string().optional(),
  agentKeyAuth50: z.string().optional(),
  agentKeyAuth51: z.string().optional(),
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
export function securityFromJSON(
  jsonString: string,
): SafeParseResult<Security, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Security$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Security' from JSON`,
  );
}
